///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10567
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10567Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("47597db9-5cb6-45dc-b0b2-90634804ff77")]
    public partial class TC10567Repo : RepoGenBaseFolder
    {
        static TC10567Repo instance = new TC10567Repo();
        TC10567RepoFolders.DataStudioAppFolder _datastudio;
        TC10567RepoFolders.SchemaScriptGenWindowAppFolder _schemascriptgenwindow;
        TC10567RepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        TC10567RepoFolders.ApplicationAppFolder _application;
        TC10567RepoFolders.SunAwtWindowToolsMenuAppFolder _sunawtwindowtoolsmenu;
        TC10567RepoFolders.ServerScriptGenWindowAppFolder _serverscriptgenwindow;

        /// <summary>
        /// Gets the singleton class instance representing the TC10567Repo element repository.
        /// </summary>
        [RepositoryFolder("47597db9-5cb6-45dc-b0b2-90634804ff77")]
        public static TC10567Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10567Repo() 
            : base("TC10567Repo", "/", null, 0, false, "47597db9-5cb6-45dc-b0b2-90634804ff77", ".\\RepositoryImages\\TC10567Repo47597db9.rximgres")
        {
            _datastudio = new TC10567RepoFolders.DataStudioAppFolder(this);
            _schemascriptgenwindow = new TC10567RepoFolders.SchemaScriptGenWindowAppFolder(this);
            _sunawtwindow = new TC10567RepoFolders.SunAwtWindowAppFolder(this);
            _application = new TC10567RepoFolders.ApplicationAppFolder(this);
            _sunawtwindowtoolsmenu = new TC10567RepoFolders.SunAwtWindowToolsMenuAppFolder(this);
            _serverscriptgenwindow = new TC10567RepoFolders.ServerScriptGenWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("47597db9-5cb6-45dc-b0b2-90634804ff77")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DataStudio folder.
        /// </summary>
        [RepositoryFolder("abadff79-3df9-4d41-869a-c4e0f15f0782")]
        public virtual TC10567RepoFolders.DataStudioAppFolder DataStudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The SchemaScriptGenWindow folder.
        /// </summary>
        [RepositoryFolder("c013ae28-f230-46ab-a829-7a59128c26c7")]
        public virtual TC10567RepoFolders.SchemaScriptGenWindowAppFolder SchemaScriptGenWindow
        {
            get { return _schemascriptgenwindow; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("2889ffc4-36d9-48f4-8961-a216c5802e1d")]
        public virtual TC10567RepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("5cfcb24b-3258-40b2-b72e-a8561f2b011d")]
        public virtual TC10567RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The SunAwtWindowToolsMenu folder.
        /// </summary>
        [RepositoryFolder("1248da03-1652-4a11-8280-8ff5f8e27051")]
        public virtual TC10567RepoFolders.SunAwtWindowToolsMenuAppFolder SunAwtWindowToolsMenu
        {
            get { return _sunawtwindowtoolsmenu; }
        }

        /// <summary>
        /// The ServerScriptGenWindow folder.
        /// </summary>
        [RepositoryFolder("ed8f919b-bd01-4718-9d4c-c2befe77c2f5")]
        public virtual TC10567RepoFolders.ServerScriptGenWindowAppFolder ServerScriptGenWindow
        {
            get { return _serverscriptgenwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10567RepoFolders
    {
        /// <summary>
        /// The DataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("abadff79-3df9-4d41-869a-c4e0f15f0782")]
        public partial class DataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toolsmenuInfo;
            RepoItemInfo _schemascriptgenmenuInfo;

            /// <summary>
            /// Creates a new DataStudio  folder.
            /// </summary>
            public DataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataStudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "abadff79-3df9-4d41-869a-c4e0f15f0782", "")
            {
                _toolsmenuInfo = new RepoItemInfo(this, "ToolsMenu", ".//menuitem[@text='Tools']", 30000, null, "a1bc582e-aecd-488f-b4d4-5ef8d260c7e4");
                _schemascriptgenmenuInfo = new RepoItemInfo(this, "SchemaScriptGenMenu", ".//menuitem[@text='Schema Script Generator']", 30000, null, "3a27cd9e-acdf-4e97-ae8b-b8d10d0d9bec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("abadff79-3df9-4d41-869a-c4e0f15f0782")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("abadff79-3df9-4d41-869a-c4e0f15f0782")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ToolsMenu item.
            /// </summary>
            [RepositoryItem("a1bc582e-aecd-488f-b4d4-5ef8d260c7e4")]
            public virtual Ranorex.MenuItem ToolsMenu
            {
                get
                {
                    return _toolsmenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ToolsMenu item info.
            /// </summary>
            [RepositoryItemInfo("a1bc582e-aecd-488f-b4d4-5ef8d260c7e4")]
            public virtual RepoItemInfo ToolsMenuInfo
            {
                get
                {
                    return _toolsmenuInfo;
                }
            }

            /// <summary>
            /// The SchemaScriptGenMenu item.
            /// </summary>
            [RepositoryItem("3a27cd9e-acdf-4e97-ae8b-b8d10d0d9bec")]
            public virtual Ranorex.MenuItem SchemaScriptGenMenu
            {
                get
                {
                    return _schemascriptgenmenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The SchemaScriptGenMenu item info.
            /// </summary>
            [RepositoryItemInfo("3a27cd9e-acdf-4e97-ae8b-b8d10d0d9bec")]
            public virtual RepoItemInfo SchemaScriptGenMenuInfo
            {
                get
                {
                    return _schemascriptgenmenuInfo;
                }
            }
        }

        /// <summary>
        /// The SchemaScriptGenWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("c013ae28-f230-46ab-a829-7a59128c26c7")]
        public partial class SchemaScriptGenWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _schematablenamecomboboxInfo;
            RepoItemInfo _unselectleftInfo;
            RepoItemInfo _unselectrightInfo;
            RepoItemInfo _lefttableInfo;
            RepoItemInfo _righttableInfo;
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _saveascomboboxInfo;
            RepoItemInfo _savefilepathtextboxInfo;
            RepoItemInfo _seperatorcomboboxInfo;
            RepoItemInfo _quotedcomboboxInfo;
            RepoItemInfo _checkboxcontainerInfo;
            RepoItemInfo _previousbuttonInfo;
            RepoItemInfo _closebuttonInfo;

            /// <summary>
            /// Creates a new SchemaScriptGenWindow  folder.
            /// </summary>
            public SchemaScriptGenWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SchemaScriptGenWindow", "/form[@title~'^Script\\ Generator']", parentFolder, 30000, null, true, "c013ae28-f230-46ab-a829-7a59128c26c7", "")
            {
                _schematablenamecomboboxInfo = new RepoItemInfo(this, "SchemaTableNameCombobox", ".//container[@type='JPanel']/container/container[2]//combobox[@name='schemaField']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "4be642e8-a69d-4bdc-80a8-9f952f240b34");
                _unselectleftInfo = new RepoItemInfo(this, "UnselectLeft", ".//container[@name='tabbedPane']/container[2]/?/?/container[@name='typeSelector']/container[@name='buttonPanel']/button[@name='deselectButton']", 30000, null, "7bcd106e-f96c-4498-8aa8-4a206792f986");
                _unselectrightInfo = new RepoItemInfo(this, "UnselectRight", ".//container[@name='tabbedPane']/container[2]/?/?/container[@name='objectSelector']/container[@name='buttonPanel']/button[@name='deselectButton']", 30000, null, "0b78d792-034f-441c-bf49-228dcef0de50");
                _lefttableInfo = new RepoItemInfo(this, "LeftTable", ".//container[@name='tabbedPane']/container[2]//container[@name='scroll']/container[5]/table[@name='table']", 30000, null, "9d9d01a0-161e-40e2-b97a-e2243acbc3b2");
                _righttableInfo = new RepoItemInfo(this, "RightTable", ".//container[@name='tabbedPane']/container[2]/?/?/container[@name='objectSelector']/container[@name='scroll']/container[5]/table[@name='table']", 30000, null, "9f6539bd-ac62-4ecf-9ae2-a67bceb478e6");
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", ".//button[@text='Next >>']", 30000, null, "c7bac1b2-71de-459e-9e44-809671513544");
                _saveascomboboxInfo = new RepoItemInfo(this, "SaveAsCombobox", ".//container[@name='tabbedPane']/container[3]/?/?/combobox[@name='cmboSave']", 30000, null, "c8da98da-c487-4978-958c-d8cb322d702b");
                _savefilepathtextboxInfo = new RepoItemInfo(this, "SaveFilePathTextbox", ".//container[@type='JPanel']/container/container[3]/?/?/text[@name='txtFile']", 30000, null, "e27d7aeb-bed5-4b01-af71-a76fbfbcdc7b");
                _seperatorcomboboxInfo = new RepoItemInfo(this, "SeperatorCombobox", ".//container[@type='JPanel']/container/container[3]//combobox[@name='cmboStmtSeparator']", 30000, null, "faff3f37-0cc5-476d-9a52-42ee9bc9c314");
                _quotedcomboboxInfo = new RepoItemInfo(this, "QuotedCombobox", ".//container[@type='JPanel']/container/container[3]//combobox[@name='quotedObjectCombo']", 30000, null, "81e5c0a9-eabe-4483-84c5-e259a3525a10");
                _checkboxcontainerInfo = new RepoItemInfo(this, "CheckBoxContainer", ".//container[@type='JPanel']/container/container[3]/container[@accessiblename=' Scripting Format ']/container[2]", 30000, null, "67316380-43e0-4ff0-b2fa-139bb8cecb36");
                _previousbuttonInfo = new RepoItemInfo(this, "PreviousButton", ".//button[@text='<< Previous']", 30000, null, "5267863b-f294-46d8-bfed-34bf734b5e47");
                _closebuttonInfo = new RepoItemInfo(this, "CloseButton", ".//button[@name='cancelButton']", 30000, null, "1e4b41ba-82cc-403d-af96-0b8704fb146b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c013ae28-f230-46ab-a829-7a59128c26c7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c013ae28-f230-46ab-a829-7a59128c26c7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SchemaTableNameCombobox item.
            /// </summary>
            [RepositoryItem("4be642e8-a69d-4bdc-80a8-9f952f240b34")]
            public virtual Ranorex.Text SchemaTableNameCombobox
            {
                get
                {
                    return _schematablenamecomboboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SchemaTableNameCombobox item info.
            /// </summary>
            [RepositoryItemInfo("4be642e8-a69d-4bdc-80a8-9f952f240b34")]
            public virtual RepoItemInfo SchemaTableNameComboboxInfo
            {
                get
                {
                    return _schematablenamecomboboxInfo;
                }
            }

            /// <summary>
            /// The UnselectLeft item.
            /// </summary>
            [RepositoryItem("7bcd106e-f96c-4498-8aa8-4a206792f986")]
            public virtual Ranorex.Button UnselectLeft
            {
                get
                {
                    return _unselectleftInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UnselectLeft item info.
            /// </summary>
            [RepositoryItemInfo("7bcd106e-f96c-4498-8aa8-4a206792f986")]
            public virtual RepoItemInfo UnselectLeftInfo
            {
                get
                {
                    return _unselectleftInfo;
                }
            }

            /// <summary>
            /// The UnselectRight item.
            /// </summary>
            [RepositoryItem("0b78d792-034f-441c-bf49-228dcef0de50")]
            public virtual Ranorex.Button UnselectRight
            {
                get
                {
                    return _unselectrightInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UnselectRight item info.
            /// </summary>
            [RepositoryItemInfo("0b78d792-034f-441c-bf49-228dcef0de50")]
            public virtual RepoItemInfo UnselectRightInfo
            {
                get
                {
                    return _unselectrightInfo;
                }
            }

            /// <summary>
            /// The LeftTable item.
            /// </summary>
            [RepositoryItem("9d9d01a0-161e-40e2-b97a-e2243acbc3b2")]
            public virtual Ranorex.Table LeftTable
            {
                get
                {
                    return _lefttableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The LeftTable item info.
            /// </summary>
            [RepositoryItemInfo("9d9d01a0-161e-40e2-b97a-e2243acbc3b2")]
            public virtual RepoItemInfo LeftTableInfo
            {
                get
                {
                    return _lefttableInfo;
                }
            }

            /// <summary>
            /// The RightTable item.
            /// </summary>
            [RepositoryItem("9f6539bd-ac62-4ecf-9ae2-a67bceb478e6")]
            public virtual Ranorex.Table RightTable
            {
                get
                {
                    return _righttableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The RightTable item info.
            /// </summary>
            [RepositoryItemInfo("9f6539bd-ac62-4ecf-9ae2-a67bceb478e6")]
            public virtual RepoItemInfo RightTableInfo
            {
                get
                {
                    return _righttableInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("c7bac1b2-71de-459e-9e44-809671513544")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("c7bac1b2-71de-459e-9e44-809671513544")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The SaveAsCombobox item.
            /// </summary>
            [RepositoryItem("c8da98da-c487-4978-958c-d8cb322d702b")]
            public virtual Ranorex.ComboBox SaveAsCombobox
            {
                get
                {
                    return _saveascomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SaveAsCombobox item info.
            /// </summary>
            [RepositoryItemInfo("c8da98da-c487-4978-958c-d8cb322d702b")]
            public virtual RepoItemInfo SaveAsComboboxInfo
            {
                get
                {
                    return _saveascomboboxInfo;
                }
            }

            /// <summary>
            /// The SaveFilePathTextbox item.
            /// </summary>
            [RepositoryItem("e27d7aeb-bed5-4b01-af71-a76fbfbcdc7b")]
            public virtual Ranorex.Text SaveFilePathTextbox
            {
                get
                {
                    return _savefilepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SaveFilePathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("e27d7aeb-bed5-4b01-af71-a76fbfbcdc7b")]
            public virtual RepoItemInfo SaveFilePathTextboxInfo
            {
                get
                {
                    return _savefilepathtextboxInfo;
                }
            }

            /// <summary>
            /// The SeperatorCombobox item.
            /// </summary>
            [RepositoryItem("faff3f37-0cc5-476d-9a52-42ee9bc9c314")]
            public virtual Ranorex.ComboBox SeperatorCombobox
            {
                get
                {
                    return _seperatorcomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SeperatorCombobox item info.
            /// </summary>
            [RepositoryItemInfo("faff3f37-0cc5-476d-9a52-42ee9bc9c314")]
            public virtual RepoItemInfo SeperatorComboboxInfo
            {
                get
                {
                    return _seperatorcomboboxInfo;
                }
            }

            /// <summary>
            /// The QuotedCombobox item.
            /// </summary>
            [RepositoryItem("81e5c0a9-eabe-4483-84c5-e259a3525a10")]
            public virtual Ranorex.ComboBox QuotedCombobox
            {
                get
                {
                    return _quotedcomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The QuotedCombobox item info.
            /// </summary>
            [RepositoryItemInfo("81e5c0a9-eabe-4483-84c5-e259a3525a10")]
            public virtual RepoItemInfo QuotedComboboxInfo
            {
                get
                {
                    return _quotedcomboboxInfo;
                }
            }

            /// <summary>
            /// The CheckBoxContainer item.
            /// </summary>
            [RepositoryItem("67316380-43e0-4ff0-b2fa-139bb8cecb36")]
            public virtual Ranorex.Container CheckBoxContainer
            {
                get
                {
                    return _checkboxcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CheckBoxContainer item info.
            /// </summary>
            [RepositoryItemInfo("67316380-43e0-4ff0-b2fa-139bb8cecb36")]
            public virtual RepoItemInfo CheckBoxContainerInfo
            {
                get
                {
                    return _checkboxcontainerInfo;
                }
            }

            /// <summary>
            /// The PreviousButton item.
            /// </summary>
            [RepositoryItem("5267863b-f294-46d8-bfed-34bf734b5e47")]
            public virtual Ranorex.Button PreviousButton
            {
                get
                {
                    return _previousbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PreviousButton item info.
            /// </summary>
            [RepositoryItemInfo("5267863b-f294-46d8-bfed-34bf734b5e47")]
            public virtual RepoItemInfo PreviousButtonInfo
            {
                get
                {
                    return _previousbuttonInfo;
                }
            }

            /// <summary>
            /// The CloseButton item.
            /// </summary>
            [RepositoryItem("1e4b41ba-82cc-403d-af96-0b8704fb146b")]
            public virtual Ranorex.Button CloseButton
            {
                get
                {
                    return _closebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseButton item info.
            /// </summary>
            [RepositoryItemInfo("1e4b41ba-82cc-403d-af96-0b8704fb146b")]
            public virtual RepoItemInfo CloseButtonInfo
            {
                get
                {
                    return _closebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("2889ffc4-36d9-48f4-8961-a216c5802e1d")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _serverscriptgenmenuInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow' and @type='Popup$HeavyWeightWindow' and @fulltype='javax.swing.Popup$HeavyWeightWindow' and @name='win0']", parentFolder, 30000, null, true, "2889ffc4-36d9-48f4-8961-a216c5802e1d", "")
            {
                _serverscriptgenmenuInfo = new RepoItemInfo(this, "ServerScriptGenMenu", ".//menuitem[@text='Server Script Generator']", 30000, null, "3ecab575-571e-4849-970f-42a60de0c5c2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2889ffc4-36d9-48f4-8961-a216c5802e1d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2889ffc4-36d9-48f4-8961-a216c5802e1d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ServerScriptGenMenu item.
            /// </summary>
            [RepositoryItem("3ecab575-571e-4849-970f-42a60de0c5c2")]
            public virtual Ranorex.MenuItem ServerScriptGenMenu
            {
                get
                {
                    return _serverscriptgenmenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ServerScriptGenMenu item info.
            /// </summary>
            [RepositoryItemInfo("3ecab575-571e-4849-970f-42a60de0c5c2")]
            public virtual RepoItemInfo ServerScriptGenMenuInfo
            {
                get
                {
                    return _serverscriptgenmenuInfo;
                }
            }
        }

        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("5cfcb24b-3258-40b2-b72e-a8561f2b011d")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toolsInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua Data Studio']", parentFolder, 30000, null, true, "5cfcb24b-3258-40b2-b72e-a8561f2b011d", "")
            {
                _toolsInfo = new RepoItemInfo(this, "Tools", ".//menuitem[@text='Tools']", 30000, null, "f6a3184c-3a21-4dc9-a3fb-ed7d48173bdd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5cfcb24b-3258-40b2-b72e-a8561f2b011d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5cfcb24b-3258-40b2-b72e-a8561f2b011d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tools item.
            /// </summary>
            [RepositoryItem("f6a3184c-3a21-4dc9-a3fb-ed7d48173bdd")]
            public virtual Ranorex.MenuItem Tools
            {
                get
                {
                    return _toolsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Tools item info.
            /// </summary>
            [RepositoryItemInfo("f6a3184c-3a21-4dc9-a3fb-ed7d48173bdd")]
            public virtual RepoItemInfo ToolsInfo
            {
                get
                {
                    return _toolsInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowToolsMenuAppFolder folder.
        /// </summary>
        [RepositoryFolder("1248da03-1652-4a11-8280-8ff5f8e27051")]
        public partial class SunAwtWindowToolsMenuAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _serverscriptgenInfo;

            /// <summary>
            /// Creates a new SunAwtWindowToolsMenu  folder.
            /// </summary>
            public SunAwtWindowToolsMenuAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindowToolsMenu", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "1248da03-1652-4a11-8280-8ff5f8e27051", "")
            {
                _serverscriptgenInfo = new RepoItemInfo(this, "ServerScriptGen", ".//menuitem[@text='Server Script Generator']", 30000, null, "4e1fd296-be36-4034-841b-df40bd08ae4d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1248da03-1652-4a11-8280-8ff5f8e27051")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1248da03-1652-4a11-8280-8ff5f8e27051")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ServerScriptGen item.
            /// </summary>
            [RepositoryItem("4e1fd296-be36-4034-841b-df40bd08ae4d")]
            public virtual Ranorex.MenuItem ServerScriptGen
            {
                get
                {
                    return _serverscriptgenInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ServerScriptGen item info.
            /// </summary>
            [RepositoryItemInfo("4e1fd296-be36-4034-841b-df40bd08ae4d")]
            public virtual RepoItemInfo ServerScriptGenInfo
            {
                get
                {
                    return _serverscriptgenInfo;
                }
            }
        }

        /// <summary>
        /// The ServerScriptGenWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("ed8f919b-bd01-4718-9d4c-c2befe77c2f5")]
        public partial class ServerScriptGenWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _schematablenamecomboboxInfo;
            RepoItemInfo _unselectleftInfo;
            RepoItemInfo _unselectrightInfo;
            RepoItemInfo _lefttableInfo;
            RepoItemInfo _righttableInfo;
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _saveascomboboxInfo;
            RepoItemInfo _savefilepathtextboxInfo;
            RepoItemInfo _seperatorcomboboxInfo;
            RepoItemInfo _quotedcomboboxInfo;
            RepoItemInfo _checkboxcontainerInfo;
            RepoItemInfo _previousbuttonInfo;
            RepoItemInfo _closebuttonInfo;

            /// <summary>
            /// Creates a new ServerScriptGenWindow  folder.
            /// </summary>
            public ServerScriptGenWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServerScriptGenWindow", "/form[@title~'^Server\\ Script\\ Generator\\ -']", parentFolder, 30000, null, true, "ed8f919b-bd01-4718-9d4c-c2befe77c2f5", "")
            {
                _schematablenamecomboboxInfo = new RepoItemInfo(this, "SchemaTableNameCombobox", ".//container[@type='JPanel']/container/container[2]//combobox[@name='schemaField']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "ddfb27bd-6721-4d29-88ff-7c0f95010b1a");
                _unselectleftInfo = new RepoItemInfo(this, "UnselectLeft", ".//container[@name='tab']/container[2]/?/?/container[@name='typeSelector']/container[@name='buttonPanel']/button[@name='deselectButton']", 30000, null, "3b0878d5-1452-4250-b4e3-9105dc298262");
                _unselectrightInfo = new RepoItemInfo(this, "UnselectRight", ".//container[@name='tab']/container[2]/?/?/container[@name='objectSelector']/container[@name='buttonPanel']/button[@name='deselectButton']", 30000, null, "76b4836e-4744-4892-bc88-4c51fcc6b4c6");
                _lefttableInfo = new RepoItemInfo(this, "LeftTable", ".//container[@name='tab']/container[2]//container[@name='scroll']/container[5]/table[@name='table']", 30000, null, "4c00ed64-b82c-42d2-b195-ef7fb3cd5fd6");
                _righttableInfo = new RepoItemInfo(this, "RightTable", ".//container[@name='tab']/container[2]/?/?/container[@name='objectSelector']/container[@name='scroll']/container[5]/table[@name='table']", 30000, null, "9d762df6-e9cb-4a35-bc40-50cd42ef3fa7");
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", ".//button[@text='Next >>']", 30000, null, "c709da94-5194-462d-975f-20f74075cfc1");
                _saveascomboboxInfo = new RepoItemInfo(this, "SaveAsCombobox", ".//container[@name='tab']/container[3]/?/?/combobox[@name='cmboSave']", 30000, null, "6ce53d8b-7acf-409b-864a-4baf732d2c9e");
                _savefilepathtextboxInfo = new RepoItemInfo(this, "SaveFilePathTextbox", ".//container[@type='JPanel']/container/container[3]/?/?/text[@name='txtFile']", 30000, null, "7ef13e0a-22a0-4df7-9c00-ba3b01f95aa2");
                _seperatorcomboboxInfo = new RepoItemInfo(this, "SeperatorCombobox", ".//container[@type='JPanel']/container/container[3]//combobox[@name='cmboStmtSeparator']", 30000, null, "9c70e9f5-d630-48ca-b8e7-0b6dc79ec019");
                _quotedcomboboxInfo = new RepoItemInfo(this, "QuotedCombobox", ".//container[@type='JPanel']/container/container[3]//combobox[@name='quotedObjectCombo']", 30000, null, "3f33f016-a3ab-462f-b29d-75a7dc9f7de3");
                _checkboxcontainerInfo = new RepoItemInfo(this, "CheckBoxContainer", ".//container[@type='JPanel']/container/container[3]/container[@accessiblename=' Scripting Format ']/container[2]", 30000, null, "b7136218-44d4-46ac-bb51-852fea6607d8");
                _previousbuttonInfo = new RepoItemInfo(this, "PreviousButton", ".//button[@text='<< Previous']", 30000, null, "a7dd942c-518b-4e7f-a5ea-7080fe19b24f");
                _closebuttonInfo = new RepoItemInfo(this, "CloseButton", ".//button[@text='Close']", 30000, null, "829e5860-3365-4bb6-8ea8-47ac5eb0dc0a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ed8f919b-bd01-4718-9d4c-c2befe77c2f5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ed8f919b-bd01-4718-9d4c-c2befe77c2f5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SchemaTableNameCombobox item.
            /// </summary>
            [RepositoryItem("ddfb27bd-6721-4d29-88ff-7c0f95010b1a")]
            public virtual Ranorex.Text SchemaTableNameCombobox
            {
                get
                {
                    return _schematablenamecomboboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SchemaTableNameCombobox item info.
            /// </summary>
            [RepositoryItemInfo("ddfb27bd-6721-4d29-88ff-7c0f95010b1a")]
            public virtual RepoItemInfo SchemaTableNameComboboxInfo
            {
                get
                {
                    return _schematablenamecomboboxInfo;
                }
            }

            /// <summary>
            /// The UnselectLeft item.
            /// </summary>
            [RepositoryItem("3b0878d5-1452-4250-b4e3-9105dc298262")]
            public virtual Ranorex.Button UnselectLeft
            {
                get
                {
                    return _unselectleftInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UnselectLeft item info.
            /// </summary>
            [RepositoryItemInfo("3b0878d5-1452-4250-b4e3-9105dc298262")]
            public virtual RepoItemInfo UnselectLeftInfo
            {
                get
                {
                    return _unselectleftInfo;
                }
            }

            /// <summary>
            /// The UnselectRight item.
            /// </summary>
            [RepositoryItem("76b4836e-4744-4892-bc88-4c51fcc6b4c6")]
            public virtual Ranorex.Button UnselectRight
            {
                get
                {
                    return _unselectrightInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UnselectRight item info.
            /// </summary>
            [RepositoryItemInfo("76b4836e-4744-4892-bc88-4c51fcc6b4c6")]
            public virtual RepoItemInfo UnselectRightInfo
            {
                get
                {
                    return _unselectrightInfo;
                }
            }

            /// <summary>
            /// The LeftTable item.
            /// </summary>
            [RepositoryItem("4c00ed64-b82c-42d2-b195-ef7fb3cd5fd6")]
            public virtual Ranorex.Table LeftTable
            {
                get
                {
                    return _lefttableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The LeftTable item info.
            /// </summary>
            [RepositoryItemInfo("4c00ed64-b82c-42d2-b195-ef7fb3cd5fd6")]
            public virtual RepoItemInfo LeftTableInfo
            {
                get
                {
                    return _lefttableInfo;
                }
            }

            /// <summary>
            /// The RightTable item.
            /// </summary>
            [RepositoryItem("9d762df6-e9cb-4a35-bc40-50cd42ef3fa7")]
            public virtual Ranorex.Table RightTable
            {
                get
                {
                    return _righttableInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The RightTable item info.
            /// </summary>
            [RepositoryItemInfo("9d762df6-e9cb-4a35-bc40-50cd42ef3fa7")]
            public virtual RepoItemInfo RightTableInfo
            {
                get
                {
                    return _righttableInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("c709da94-5194-462d-975f-20f74075cfc1")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("c709da94-5194-462d-975f-20f74075cfc1")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The SaveAsCombobox item.
            /// </summary>
            [RepositoryItem("6ce53d8b-7acf-409b-864a-4baf732d2c9e")]
            public virtual Ranorex.ComboBox SaveAsCombobox
            {
                get
                {
                    return _saveascomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SaveAsCombobox item info.
            /// </summary>
            [RepositoryItemInfo("6ce53d8b-7acf-409b-864a-4baf732d2c9e")]
            public virtual RepoItemInfo SaveAsComboboxInfo
            {
                get
                {
                    return _saveascomboboxInfo;
                }
            }

            /// <summary>
            /// The SaveFilePathTextbox item.
            /// </summary>
            [RepositoryItem("7ef13e0a-22a0-4df7-9c00-ba3b01f95aa2")]
            public virtual Ranorex.Text SaveFilePathTextbox
            {
                get
                {
                    return _savefilepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SaveFilePathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("7ef13e0a-22a0-4df7-9c00-ba3b01f95aa2")]
            public virtual RepoItemInfo SaveFilePathTextboxInfo
            {
                get
                {
                    return _savefilepathtextboxInfo;
                }
            }

            /// <summary>
            /// The SeperatorCombobox item.
            /// </summary>
            [RepositoryItem("9c70e9f5-d630-48ca-b8e7-0b6dc79ec019")]
            public virtual Ranorex.ComboBox SeperatorCombobox
            {
                get
                {
                    return _seperatorcomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The SeperatorCombobox item info.
            /// </summary>
            [RepositoryItemInfo("9c70e9f5-d630-48ca-b8e7-0b6dc79ec019")]
            public virtual RepoItemInfo SeperatorComboboxInfo
            {
                get
                {
                    return _seperatorcomboboxInfo;
                }
            }

            /// <summary>
            /// The QuotedCombobox item.
            /// </summary>
            [RepositoryItem("3f33f016-a3ab-462f-b29d-75a7dc9f7de3")]
            public virtual Ranorex.ComboBox QuotedCombobox
            {
                get
                {
                    return _quotedcomboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The QuotedCombobox item info.
            /// </summary>
            [RepositoryItemInfo("3f33f016-a3ab-462f-b29d-75a7dc9f7de3")]
            public virtual RepoItemInfo QuotedComboboxInfo
            {
                get
                {
                    return _quotedcomboboxInfo;
                }
            }

            /// <summary>
            /// The CheckBoxContainer item.
            /// </summary>
            [RepositoryItem("b7136218-44d4-46ac-bb51-852fea6607d8")]
            public virtual Ranorex.Container CheckBoxContainer
            {
                get
                {
                    return _checkboxcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The CheckBoxContainer item info.
            /// </summary>
            [RepositoryItemInfo("b7136218-44d4-46ac-bb51-852fea6607d8")]
            public virtual RepoItemInfo CheckBoxContainerInfo
            {
                get
                {
                    return _checkboxcontainerInfo;
                }
            }

            /// <summary>
            /// The PreviousButton item.
            /// </summary>
            [RepositoryItem("a7dd942c-518b-4e7f-a5ea-7080fe19b24f")]
            public virtual Ranorex.Button PreviousButton
            {
                get
                {
                    return _previousbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PreviousButton item info.
            /// </summary>
            [RepositoryItemInfo("a7dd942c-518b-4e7f-a5ea-7080fe19b24f")]
            public virtual RepoItemInfo PreviousButtonInfo
            {
                get
                {
                    return _previousbuttonInfo;
                }
            }

            /// <summary>
            /// The CloseButton item.
            /// </summary>
            [RepositoryItem("829e5860-3365-4bb6-8ea8-47ac5eb0dc0a")]
            public virtual Ranorex.Button CloseButton
            {
                get
                {
                    return _closebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseButton item info.
            /// </summary>
            [RepositoryItemInfo("829e5860-3365-4bb6-8ea8-47ac5eb0dc0a")]
            public virtual RepoItemInfo CloseButtonInfo
            {
                get
                {
                    return _closebuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}