///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.Preconditions
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PreconditionRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("c350295c-8dce-42ea-a15a-b3d424358fb2")]
    public partial class PreconditionRepo : RepoGenBaseFolder
    {
        static PreconditionRepo instance = new PreconditionRepo();
        PreconditionRepoFolders.ServersListAppFolder _serverslist;
        PreconditionRepoFolders.OpenAppFolder _open;
        PreconditionRepoFolders.QueryAnalyzerAppFolder _queryanalyzer;
        PreconditionRepoFolders.QueryAnalyzerComboListAppFolder _queryanalyzercombolist;
        PreconditionRepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        PreconditionRepoFolders.ConnectionAppFolder _connection;
        PreconditionRepoFolders.FileModifiedAppFolder _filemodified;

        /// <summary>
        /// Gets the singleton class instance representing the PreconditionRepo element repository.
        /// </summary>
        [RepositoryFolder("c350295c-8dce-42ea-a15a-b3d424358fb2")]
        public static PreconditionRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PreconditionRepo() 
            : base("PreconditionRepo", "/", null, 0, false, "c350295c-8dce-42ea-a15a-b3d424358fb2", ".\\RepositoryImages\\PreconditionRepoc350295c.rximgres")
        {
            _serverslist = new PreconditionRepoFolders.ServersListAppFolder(this);
            _open = new PreconditionRepoFolders.OpenAppFolder(this);
            _queryanalyzer = new PreconditionRepoFolders.QueryAnalyzerAppFolder(this);
            _queryanalyzercombolist = new PreconditionRepoFolders.QueryAnalyzerComboListAppFolder(this);
            _sunawtwindow = new PreconditionRepoFolders.SunAwtWindowAppFolder(this);
            _connection = new PreconditionRepoFolders.ConnectionAppFolder(this);
            _filemodified = new PreconditionRepoFolders.FileModifiedAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c350295c-8dce-42ea-a15a-b3d424358fb2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ServersList folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public virtual PreconditionRepoFolders.ServersListAppFolder ServersList
        {
            get { return _serverslist; }
        }

        /// <summary>
        /// The Open folder.
        /// </summary>
        [RepositoryFolder("a99d421a-97b3-4265-90b5-6107761dfe5a")]
        public virtual PreconditionRepoFolders.OpenAppFolder Open
        {
            get { return _open; }
        }

        /// <summary>
        /// The QueryAnalyzer folder.
        /// </summary>
        [RepositoryFolder("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
        public virtual PreconditionRepoFolders.QueryAnalyzerAppFolder QueryAnalyzer
        {
            get { return _queryanalyzer; }
        }

        /// <summary>
        /// The QueryAnalyzerComboList folder.
        /// </summary>
        [RepositoryFolder("de5f70d9-1502-4cd6-a43b-0af6a65cb1da")]
        public virtual PreconditionRepoFolders.QueryAnalyzerComboListAppFolder QueryAnalyzerComboList
        {
            get { return _queryanalyzercombolist; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("7ba75842-e062-4ee1-878c-350ec8f536fe")]
        public virtual PreconditionRepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The Connection folder.
        /// </summary>
        [RepositoryFolder("e599b4c8-b2ab-4900-bf15-d9fe4abbf4d0")]
        public virtual PreconditionRepoFolders.ConnectionAppFolder Connection
        {
            get { return _connection; }
        }

        /// <summary>
        /// The FileModified folder.
        /// </summary>
        [RepositoryFolder("81da30cb-ca00-4399-8303-a8969123f60e")]
        public virtual PreconditionRepoFolders.FileModifiedAppFolder FileModified
        {
            get { return _filemodified; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class PreconditionRepoFolders
    {
        /// <summary>
        /// The ServersListAppFolder folder.
        /// </summary>
        [RepositoryFolder("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
        public partial class ServersListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _localdbserverstreeitemInfo;
            RepoItemInfo _amazonredshiftInfo;
            RepoItemInfo _cassandra37Info;
            RepoItemInfo _cassandra22Info;
            RepoItemInfo _derby1014Info;
            RepoItemInfo _derby1013Info;
            RepoItemInfo _db2111Info;
            RepoItemInfo _db2105Info;
            RepoItemInfo _excellInfo;
            RepoItemInfo _greenplum50Info;
            RepoItemInfo _greenplum4312Info;
            RepoItemInfo _informix1210Info;
            RepoItemInfo _informix1170Info;
            RepoItemInfo _mariadbInfo;
            RepoItemInfo _mongodb341Info;
            RepoItemInfo _mongodb321Info;
            RepoItemInfo _mysql80Info;
            RepoItemInfo _mysql57Info;
            RepoItemInfo _netezza72Info;
            RepoItemInfo _oracle20Info;
            RepoItemInfo _oracler2Info;
            RepoItemInfo _postgresql100Info;
            RepoItemInfo _postgresql96Info;
            RepoItemInfo _saphana20Info;
            RepoItemInfo _microsoftsqlazure08Info;
            RepoItemInfo _sqlserver2017Info;
            RepoItemInfo _sqlserver2016Info;
            RepoItemInfo _sybaseany17Info;
            RepoItemInfo _sybaseany16Info;
            RepoItemInfo _sybasease16Info;
            RepoItemInfo _sybasease157Info;
            RepoItemInfo _sybaseiq160Info;
            RepoItemInfo _sybaseiq154Info;
            RepoItemInfo _teradata1620Info;
            RepoItemInfo _teradata150Info;
            RepoItemInfo _vertica91Info;
            RepoItemInfo _vertica80Info;

            /// <summary>
            /// Creates a new ServersList  folder.
            /// </summary>
            public ServersListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServersList", "/form[@title~'^Aqua Data Studio']", parentFolder, 30000, null, true, "074e9ce7-9035-4f66-9c1e-6128b4f5101b", "")
            {
                _localdbserverstreeitemInfo = new RepoItemInfo(this, "LocalDBServersTreeItem", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']", 30000, null, "0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44");
                _amazonredshiftInfo = new RepoItemInfo(this, "AmazonRedshift", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Amazon Redshift']", 30000, null, "42455817-093b-43f2-a874-6b64bbf54c32");
                _cassandra37Info = new RepoItemInfo(this, "Cassandra37", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Cassandra 172.24.1.77 3.7']", 30000, null, "687b1d8a-8279-4b44-b9b9-df583870cdde");
                _cassandra22Info = new RepoItemInfo(this, "Cassandra22", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Cassandra\\ 172\\.24\\.1\\.122\\ 2\\.']", 30000, null, "c3acc780-3500-40ab-9700-abe57717e048");
                _derby1014Info = new RepoItemInfo(this, "Derby1014", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Derby 172.24.1.199 v10.14']", 30000, null, "1ebfbf8a-748c-4072-9785-c73c555586e0");
                _derby1013Info = new RepoItemInfo(this, "Derby1013", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Derby 172.24.1.8 v10.13']", 30000, null, "8951d885-6114-41bb-88a4-8e67f1954167");
                _db2111Info = new RepoItemInfo(this, "DB2111", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='DB2 LUW 172.24.1.8 v11.1']", 30000, null, "e4c2b412-7fed-4196-b33f-034a187a4270");
                _db2105Info = new RepoItemInfo(this, "DB2105", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^DB2\\ LUW\\ 172\\.24\\.1\\.145\\ v10\\.']", 30000, null, "e41fea87-364c-402d-a3df-f6ed69c45513");
                _excellInfo = new RepoItemInfo(this, "Excell", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MS Excel']", 30000, null, "d8a9f856-d6ec-46a3-94a2-3317bc42b65c");
                _greenplum50Info = new RepoItemInfo(this, "Greenplum50", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Greenplum\\ 10\\.90\\.1\\.146\\ v5\\.']", 30000, null, "838dd8c3-66c0-4e84-99ea-420f63697081");
                _greenplum4312Info = new RepoItemInfo(this, "Greenplum4312", "element", 30000, null, "bc650173-6ba2-4fad-9143-134c4b4d3593");
                _informix1210Info = new RepoItemInfo(this, "Informix1210", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.145\\ v12']", 30000, null, "f6382d4e-bc5c-411b-ae82-7b65ff2c0cdf");
                _informix1170Info = new RepoItemInfo(this, "Informix1170", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Informix\\ 172\\.24\\.1\\.140\\ v11']", 30000, null, "9684e933-b68d-4b42-93a7-2bc40e524ea1");
                _mariadbInfo = new RepoItemInfo(this, "MariaDB", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MariaDB 172.24.1.8 v10.2']", 30000, null, "f96380ae-605b-4713-9452-d6d45b55a5e0");
                _mongodb341Info = new RepoItemInfo(this, "MongoDB341", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.4']", 30000, null, "d96209e6-546a-46ae-8862-6e64bcafd706");
                _mongodb321Info = new RepoItemInfo(this, "MongoDB321", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^MongoDB\\ 172\\.24\\.1\\.155\\ v3\\.2']", 30000, null, "f46006da-8173-4ad0-93ae-1ba2488ead71");
                _mysql80Info = new RepoItemInfo(this, "MySQL80", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MySQL 172.24.1.199 v8.0']", 30000, null, "1ea11b55-56ac-41f6-a396-99a59261cf39");
                _mysql57Info = new RepoItemInfo(this, "MySQL57", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='MySQL 172.24.1.8 v5.7']", 30000, null, "af69ff7f-c42b-40b6-b521-f1466fc88fc2");
                _netezza72Info = new RepoItemInfo(this, "Netezza72", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Netezza 10.90.1.21 7.2']", 30000, null, "b9e30ee4-c403-479d-9c2c-af188bc556ef");
                _oracle20Info = new RepoItemInfo(this, "Oracle20", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Oracle\\ 172\\.24\\.1\\.199\\ v12\\.1']", 30000, null, "46b9549f-4d70-4b3f-9b34-f91e64c1dab7");
                _oracler2Info = new RepoItemInfo(this, "OracleR2", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Oracle\\ 172\\.24\\.1\\.140\\ v11g\\ ']", 30000, null, "0d531f2c-4e88-4c2b-988b-345f9722315e");
                _postgresql100Info = new RepoItemInfo(this, "PostgreSQL100", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^PostgreSQL\\ 172\\.24\\.1\\.8\\ v10']", 30000, null, "4b654434-fcde-4b00-bc6f-3e0c6de44651");
                _postgresql96Info = new RepoItemInfo(this, "PostgreSQL96", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^PostgreSQL\\ 172\\.24\\.1\\.122\\ v']", 30000, null, "ce8e4ab7-a4c7-458d-a8c3-e42e960c816d");
                _saphana20Info = new RepoItemInfo(this, "SAPHana20", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='SAP Hana 10.90.1.96 v2.0']", 30000, null, "d91e6c77-cf8b-4d98-938f-48566c07a731");
                _microsoftsqlazure08Info = new RepoItemInfo(this, "MicrosoftSQLAzure08", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Microsoft\\ SQL\\ Azure\\ \\(RTM\\)']", 30000, null, "b01f3092-c3c6-48da-80d3-abb083de9746");
                _sqlserver2017Info = new RepoItemInfo(this, "SQLServer2017", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^SQL\\ Server\\ 172\\.24\\.1\\.154\\ 2']", 30000, null, "dbfecece-a98f-4969-b1c3-f088d6e75c94");
                _sqlserver2016Info = new RepoItemInfo(this, "SQLServer2016", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']/treeitem[@text='SQL Server 172.24.1.199 2016']", 30000, null, "0493e619-8f91-4948-8791-4c4122367fda");
                _sybaseany17Info = new RepoItemInfo(this, "SybaseAny17", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Sybase\\ Any\\ 172\\.24\\.1\\.50\\ v1']", 30000, null, "f64bde53-820a-4717-9d82-bd032061a4d9");
                _sybaseany16Info = new RepoItemInfo(this, "SybaseAny16", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Sybase\\ Any\\ 172\\.24\\.1\\.145\\ v']", 30000, null, "2f78d471-85e8-419c-bfe9-989e0a8c739c");
                _sybasease16Info = new RepoItemInfo(this, "SybaseASE16", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Sybase\\ ASE\\ 172\\.24\\.1\\.145\\ v']", 30000, null, "46abdc2b-d4ef-45cf-b3d5-c66482c46a1d");
                _sybasease157Info = new RepoItemInfo(this, "SybaseASE157", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']/?/?/treeitem[@text='Local Database Servers']/treeitem[@text='Sybase ASE 172.24.1.6 v15.7']", 30000, null, "fb521a3e-9b7b-4db4-868e-516474301981");
                _sybaseiq160Info = new RepoItemInfo(this, "SybaseIQ160", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Sybase\\ IQ\\ 172\\.24\\.1\\.140\\ 16']", 30000, null, "7b4d3898-b708-4347-8da9-3af19c86388a");
                _sybaseiq154Info = new RepoItemInfo(this, "SybaseIQ154", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Sybase IQ 172.24.1.6 15.4']", 30000, null, "79930e44-c2c4-4e15-90f7-2e9e70ec5e6b");
                _teradata1620Info = new RepoItemInfo(this, "Teradata1620", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Teradata\\ 10\\.90\\.1\\.169\\ v16\\.']", 30000, null, "651cc99b-3c81-43c3-9fb6-d85c85049e36");
                _teradata150Info = new RepoItemInfo(this, "Teradata150", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^Teradata 10.90.1.175 v15.0']", 30000, null, "906ee06c-bcdf-4e8e-aa54-0f94890646b5");
                _vertica91Info = new RepoItemInfo(this, "Vertica91", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Vertica 10.90.1.54 v9.1']", 30000, null, "e8b4899d-57ca-4936-8568-a1d20a783207");
                _vertica80Info = new RepoItemInfo(this, "Vertica80", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']/?/?/container[@type='NonOpaquePanel']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Vertica 10.90.1.176 v8.0']", 30000, null, "8295a42b-eddd-44e0-a636-222c74a9b3cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("074e9ce7-9035-4f66-9c1e-6128b4f5101b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item.
            /// </summary>
            [RepositoryItem("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual Ranorex.TreeItem LocalDBServersTreeItem
            {
                get
                {
                    return _localdbserverstreeitemInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The LocalDBServersTreeItem item info.
            /// </summary>
            [RepositoryItemInfo("0f6e214a-25ee-4eaa-81ac-a97c7eb5ef44")]
            public virtual RepoItemInfo LocalDBServersTreeItemInfo
            {
                get
                {
                    return _localdbserverstreeitemInfo;
                }
            }

            /// <summary>
            /// The AmazonRedshift item.
            /// </summary>
            [RepositoryItem("42455817-093b-43f2-a874-6b64bbf54c32")]
            public virtual Ranorex.TreeItem AmazonRedshift
            {
                get
                {
                    return _amazonredshiftInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The AmazonRedshift item info.
            /// </summary>
            [RepositoryItemInfo("42455817-093b-43f2-a874-6b64bbf54c32")]
            public virtual RepoItemInfo AmazonRedshiftInfo
            {
                get
                {
                    return _amazonredshiftInfo;
                }
            }

            /// <summary>
            /// The Cassandra37 item.
            /// </summary>
            [RepositoryItem("687b1d8a-8279-4b44-b9b9-df583870cdde")]
            public virtual Ranorex.TreeItem Cassandra37
            {
                get
                {
                    return _cassandra37Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Cassandra37 item info.
            /// </summary>
            [RepositoryItemInfo("687b1d8a-8279-4b44-b9b9-df583870cdde")]
            public virtual RepoItemInfo Cassandra37Info
            {
                get
                {
                    return _cassandra37Info;
                }
            }

            /// <summary>
            /// The Cassandra22 item.
            /// </summary>
            [RepositoryItem("c3acc780-3500-40ab-9700-abe57717e048")]
            public virtual Ranorex.TreeItem Cassandra22
            {
                get
                {
                    return _cassandra22Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Cassandra22 item info.
            /// </summary>
            [RepositoryItemInfo("c3acc780-3500-40ab-9700-abe57717e048")]
            public virtual RepoItemInfo Cassandra22Info
            {
                get
                {
                    return _cassandra22Info;
                }
            }

            /// <summary>
            /// The Derby1014 item.
            /// </summary>
            [RepositoryItem("1ebfbf8a-748c-4072-9785-c73c555586e0")]
            public virtual Ranorex.TreeItem Derby1014
            {
                get
                {
                    return _derby1014Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Derby1014 item info.
            /// </summary>
            [RepositoryItemInfo("1ebfbf8a-748c-4072-9785-c73c555586e0")]
            public virtual RepoItemInfo Derby1014Info
            {
                get
                {
                    return _derby1014Info;
                }
            }

            /// <summary>
            /// The Derby1013 item.
            /// </summary>
            [RepositoryItem("8951d885-6114-41bb-88a4-8e67f1954167")]
            public virtual Ranorex.TreeItem Derby1013
            {
                get
                {
                    return _derby1013Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Derby1013 item info.
            /// </summary>
            [RepositoryItemInfo("8951d885-6114-41bb-88a4-8e67f1954167")]
            public virtual RepoItemInfo Derby1013Info
            {
                get
                {
                    return _derby1013Info;
                }
            }

            /// <summary>
            /// The DB2111 item.
            /// </summary>
            [RepositoryItem("e4c2b412-7fed-4196-b33f-034a187a4270")]
            public virtual Ranorex.TreeItem DB2111
            {
                get
                {
                    return _db2111Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DB2111 item info.
            /// </summary>
            [RepositoryItemInfo("e4c2b412-7fed-4196-b33f-034a187a4270")]
            public virtual RepoItemInfo DB2111Info
            {
                get
                {
                    return _db2111Info;
                }
            }

            /// <summary>
            /// The DB2105 item.
            /// </summary>
            [RepositoryItem("e41fea87-364c-402d-a3df-f6ed69c45513")]
            public virtual Ranorex.TreeItem DB2105
            {
                get
                {
                    return _db2105Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DB2105 item info.
            /// </summary>
            [RepositoryItemInfo("e41fea87-364c-402d-a3df-f6ed69c45513")]
            public virtual RepoItemInfo DB2105Info
            {
                get
                {
                    return _db2105Info;
                }
            }

            /// <summary>
            /// The Excell item.
            /// </summary>
            [RepositoryItem("d8a9f856-d6ec-46a3-94a2-3317bc42b65c")]
            public virtual Ranorex.TreeItem Excell
            {
                get
                {
                    return _excellInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Excell item info.
            /// </summary>
            [RepositoryItemInfo("d8a9f856-d6ec-46a3-94a2-3317bc42b65c")]
            public virtual RepoItemInfo ExcellInfo
            {
                get
                {
                    return _excellInfo;
                }
            }

            /// <summary>
            /// The Greenplum50 item.
            /// </summary>
            [RepositoryItem("838dd8c3-66c0-4e84-99ea-420f63697081")]
            public virtual Ranorex.TreeItem Greenplum50
            {
                get
                {
                    return _greenplum50Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Greenplum50 item info.
            /// </summary>
            [RepositoryItemInfo("838dd8c3-66c0-4e84-99ea-420f63697081")]
            public virtual RepoItemInfo Greenplum50Info
            {
                get
                {
                    return _greenplum50Info;
                }
            }

            /// <summary>
            /// The Greenplum4312 item.
            /// </summary>
            [RepositoryItem("bc650173-6ba2-4fad-9143-134c4b4d3593")]
            public virtual Ranorex.Unknown Greenplum4312
            {
                get
                {
                    return _greenplum4312Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Greenplum4312 item info.
            /// </summary>
            [RepositoryItemInfo("bc650173-6ba2-4fad-9143-134c4b4d3593")]
            public virtual RepoItemInfo Greenplum4312Info
            {
                get
                {
                    return _greenplum4312Info;
                }
            }

            /// <summary>
            /// The Informix1210 item.
            /// </summary>
            [RepositoryItem("f6382d4e-bc5c-411b-ae82-7b65ff2c0cdf")]
            public virtual Ranorex.TreeItem Informix1210
            {
                get
                {
                    return _informix1210Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix1210 item info.
            /// </summary>
            [RepositoryItemInfo("f6382d4e-bc5c-411b-ae82-7b65ff2c0cdf")]
            public virtual RepoItemInfo Informix1210Info
            {
                get
                {
                    return _informix1210Info;
                }
            }

            /// <summary>
            /// The Informix1170 item.
            /// </summary>
            [RepositoryItem("9684e933-b68d-4b42-93a7-2bc40e524ea1")]
            public virtual Ranorex.TreeItem Informix1170
            {
                get
                {
                    return _informix1170Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Informix1170 item info.
            /// </summary>
            [RepositoryItemInfo("9684e933-b68d-4b42-93a7-2bc40e524ea1")]
            public virtual RepoItemInfo Informix1170Info
            {
                get
                {
                    return _informix1170Info;
                }
            }

            /// <summary>
            /// The MariaDB item.
            /// </summary>
            [RepositoryItem("f96380ae-605b-4713-9452-d6d45b55a5e0")]
            public virtual Ranorex.TreeItem MariaDB
            {
                get
                {
                    return _mariadbInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MariaDB item info.
            /// </summary>
            [RepositoryItemInfo("f96380ae-605b-4713-9452-d6d45b55a5e0")]
            public virtual RepoItemInfo MariaDBInfo
            {
                get
                {
                    return _mariadbInfo;
                }
            }

            /// <summary>
            /// The MongoDB341 item.
            /// </summary>
            [RepositoryItem("d96209e6-546a-46ae-8862-6e64bcafd706")]
            public virtual Ranorex.TreeItem MongoDB341
            {
                get
                {
                    return _mongodb341Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB341 item info.
            /// </summary>
            [RepositoryItemInfo("d96209e6-546a-46ae-8862-6e64bcafd706")]
            public virtual RepoItemInfo MongoDB341Info
            {
                get
                {
                    return _mongodb341Info;
                }
            }

            /// <summary>
            /// The MongoDB321 item.
            /// </summary>
            [RepositoryItem("f46006da-8173-4ad0-93ae-1ba2488ead71")]
            public virtual Ranorex.TreeItem MongoDB321
            {
                get
                {
                    return _mongodb321Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MongoDB321 item info.
            /// </summary>
            [RepositoryItemInfo("f46006da-8173-4ad0-93ae-1ba2488ead71")]
            public virtual RepoItemInfo MongoDB321Info
            {
                get
                {
                    return _mongodb321Info;
                }
            }

            /// <summary>
            /// The MySQL80 item.
            /// </summary>
            [RepositoryItem("1ea11b55-56ac-41f6-a396-99a59261cf39")]
            public virtual Ranorex.TreeItem MySQL80
            {
                get
                {
                    return _mysql80Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MySQL80 item info.
            /// </summary>
            [RepositoryItemInfo("1ea11b55-56ac-41f6-a396-99a59261cf39")]
            public virtual RepoItemInfo MySQL80Info
            {
                get
                {
                    return _mysql80Info;
                }
            }

            /// <summary>
            /// The MySQL57 item.
            /// </summary>
            [RepositoryItem("af69ff7f-c42b-40b6-b521-f1466fc88fc2")]
            public virtual Ranorex.TreeItem MySQL57
            {
                get
                {
                    return _mysql57Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MySQL57 item info.
            /// </summary>
            [RepositoryItemInfo("af69ff7f-c42b-40b6-b521-f1466fc88fc2")]
            public virtual RepoItemInfo MySQL57Info
            {
                get
                {
                    return _mysql57Info;
                }
            }

            /// <summary>
            /// The Netezza72 item.
            /// </summary>
            [RepositoryItem("b9e30ee4-c403-479d-9c2c-af188bc556ef")]
            public virtual Ranorex.TreeItem Netezza72
            {
                get
                {
                    return _netezza72Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Netezza72 item info.
            /// </summary>
            [RepositoryItemInfo("b9e30ee4-c403-479d-9c2c-af188bc556ef")]
            public virtual RepoItemInfo Netezza72Info
            {
                get
                {
                    return _netezza72Info;
                }
            }

            /// <summary>
            /// The Oracle20 item.
            /// </summary>
            [RepositoryItem("46b9549f-4d70-4b3f-9b34-f91e64c1dab7")]
            public virtual Ranorex.TreeItem Oracle20
            {
                get
                {
                    return _oracle20Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Oracle20 item info.
            /// </summary>
            [RepositoryItemInfo("46b9549f-4d70-4b3f-9b34-f91e64c1dab7")]
            public virtual RepoItemInfo Oracle20Info
            {
                get
                {
                    return _oracle20Info;
                }
            }

            /// <summary>
            /// The OracleR2 item.
            /// </summary>
            [RepositoryItem("0d531f2c-4e88-4c2b-988b-345f9722315e")]
            public virtual Ranorex.TreeItem OracleR2
            {
                get
                {
                    return _oracler2Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The OracleR2 item info.
            /// </summary>
            [RepositoryItemInfo("0d531f2c-4e88-4c2b-988b-345f9722315e")]
            public virtual RepoItemInfo OracleR2Info
            {
                get
                {
                    return _oracler2Info;
                }
            }

            /// <summary>
            /// The PostgreSQL100 item.
            /// </summary>
            [RepositoryItem("4b654434-fcde-4b00-bc6f-3e0c6de44651")]
            public virtual Ranorex.TreeItem PostgreSQL100
            {
                get
                {
                    return _postgresql100Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The PostgreSQL100 item info.
            /// </summary>
            [RepositoryItemInfo("4b654434-fcde-4b00-bc6f-3e0c6de44651")]
            public virtual RepoItemInfo PostgreSQL100Info
            {
                get
                {
                    return _postgresql100Info;
                }
            }

            /// <summary>
            /// The PostgreSQL96 item.
            /// </summary>
            [RepositoryItem("ce8e4ab7-a4c7-458d-a8c3-e42e960c816d")]
            public virtual Ranorex.TreeItem PostgreSQL96
            {
                get
                {
                    return _postgresql96Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The PostgreSQL96 item info.
            /// </summary>
            [RepositoryItemInfo("ce8e4ab7-a4c7-458d-a8c3-e42e960c816d")]
            public virtual RepoItemInfo PostgreSQL96Info
            {
                get
                {
                    return _postgresql96Info;
                }
            }

            /// <summary>
            /// The SAPHana20 item.
            /// </summary>
            [RepositoryItem("d91e6c77-cf8b-4d98-938f-48566c07a731")]
            public virtual Ranorex.TreeItem SAPHana20
            {
                get
                {
                    return _saphana20Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SAPHana20 item info.
            /// </summary>
            [RepositoryItemInfo("d91e6c77-cf8b-4d98-938f-48566c07a731")]
            public virtual RepoItemInfo SAPHana20Info
            {
                get
                {
                    return _saphana20Info;
                }
            }

            /// <summary>
            /// The MicrosoftSQLAzure08 item.
            /// </summary>
            [RepositoryItem("b01f3092-c3c6-48da-80d3-abb083de9746")]
            public virtual Ranorex.TreeItem MicrosoftSQLAzure08
            {
                get
                {
                    return _microsoftsqlazure08Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MicrosoftSQLAzure08 item info.
            /// </summary>
            [RepositoryItemInfo("b01f3092-c3c6-48da-80d3-abb083de9746")]
            public virtual RepoItemInfo MicrosoftSQLAzure08Info
            {
                get
                {
                    return _microsoftsqlazure08Info;
                }
            }

            /// <summary>
            /// The SQLServer2017 item.
            /// </summary>
            [RepositoryItem("dbfecece-a98f-4969-b1c3-f088d6e75c94")]
            public virtual Ranorex.TreeItem SQLServer2017
            {
                get
                {
                    return _sqlserver2017Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SQLServer2017 item info.
            /// </summary>
            [RepositoryItemInfo("dbfecece-a98f-4969-b1c3-f088d6e75c94")]
            public virtual RepoItemInfo SQLServer2017Info
            {
                get
                {
                    return _sqlserver2017Info;
                }
            }

            /// <summary>
            /// The SQLServer2016 item.
            /// </summary>
            [RepositoryItem("0493e619-8f91-4948-8791-4c4122367fda")]
            public virtual Ranorex.TreeItem SQLServer2016
            {
                get
                {
                    return _sqlserver2016Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SQLServer2016 item info.
            /// </summary>
            [RepositoryItemInfo("0493e619-8f91-4948-8791-4c4122367fda")]
            public virtual RepoItemInfo SQLServer2016Info
            {
                get
                {
                    return _sqlserver2016Info;
                }
            }

            /// <summary>
            /// The SybaseAny17 item.
            /// </summary>
            [RepositoryItem("f64bde53-820a-4717-9d82-bd032061a4d9")]
            public virtual Ranorex.TreeItem SybaseAny17
            {
                get
                {
                    return _sybaseany17Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SybaseAny17 item info.
            /// </summary>
            [RepositoryItemInfo("f64bde53-820a-4717-9d82-bd032061a4d9")]
            public virtual RepoItemInfo SybaseAny17Info
            {
                get
                {
                    return _sybaseany17Info;
                }
            }

            /// <summary>
            /// The SybaseAny16 item.
            /// </summary>
            [RepositoryItem("2f78d471-85e8-419c-bfe9-989e0a8c739c")]
            public virtual Ranorex.TreeItem SybaseAny16
            {
                get
                {
                    return _sybaseany16Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SybaseAny16 item info.
            /// </summary>
            [RepositoryItemInfo("2f78d471-85e8-419c-bfe9-989e0a8c739c")]
            public virtual RepoItemInfo SybaseAny16Info
            {
                get
                {
                    return _sybaseany16Info;
                }
            }

            /// <summary>
            /// The SybaseASE16 item.
            /// </summary>
            [RepositoryItem("46abdc2b-d4ef-45cf-b3d5-c66482c46a1d")]
            public virtual Ranorex.TreeItem SybaseASE16
            {
                get
                {
                    return _sybasease16Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SybaseASE16 item info.
            /// </summary>
            [RepositoryItemInfo("46abdc2b-d4ef-45cf-b3d5-c66482c46a1d")]
            public virtual RepoItemInfo SybaseASE16Info
            {
                get
                {
                    return _sybasease16Info;
                }
            }

            /// <summary>
            /// The SybaseASE157 item.
            /// </summary>
            [RepositoryItem("fb521a3e-9b7b-4db4-868e-516474301981")]
            public virtual Ranorex.TreeItem SybaseASE157
            {
                get
                {
                    return _sybasease157Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SybaseASE157 item info.
            /// </summary>
            [RepositoryItemInfo("fb521a3e-9b7b-4db4-868e-516474301981")]
            public virtual RepoItemInfo SybaseASE157Info
            {
                get
                {
                    return _sybasease157Info;
                }
            }

            /// <summary>
            /// The SybaseIQ160 item.
            /// </summary>
            [RepositoryItem("7b4d3898-b708-4347-8da9-3af19c86388a")]
            public virtual Ranorex.TreeItem SybaseIQ160
            {
                get
                {
                    return _sybaseiq160Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SybaseIQ160 item info.
            /// </summary>
            [RepositoryItemInfo("7b4d3898-b708-4347-8da9-3af19c86388a")]
            public virtual RepoItemInfo SybaseIQ160Info
            {
                get
                {
                    return _sybaseiq160Info;
                }
            }

            /// <summary>
            /// The SybaseIQ154 item.
            /// </summary>
            [RepositoryItem("79930e44-c2c4-4e15-90f7-2e9e70ec5e6b")]
            public virtual Ranorex.TreeItem SybaseIQ154
            {
                get
                {
                    return _sybaseiq154Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The SybaseIQ154 item info.
            /// </summary>
            [RepositoryItemInfo("79930e44-c2c4-4e15-90f7-2e9e70ec5e6b")]
            public virtual RepoItemInfo SybaseIQ154Info
            {
                get
                {
                    return _sybaseiq154Info;
                }
            }

            /// <summary>
            /// The Teradata1620 item.
            /// </summary>
            [RepositoryItem("651cc99b-3c81-43c3-9fb6-d85c85049e36")]
            public virtual Ranorex.TreeItem Teradata1620
            {
                get
                {
                    return _teradata1620Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Teradata1620 item info.
            /// </summary>
            [RepositoryItemInfo("651cc99b-3c81-43c3-9fb6-d85c85049e36")]
            public virtual RepoItemInfo Teradata1620Info
            {
                get
                {
                    return _teradata1620Info;
                }
            }

            /// <summary>
            /// The Teradata150 item.
            /// </summary>
            [RepositoryItem("906ee06c-bcdf-4e8e-aa54-0f94890646b5")]
            public virtual Ranorex.TreeItem Teradata150
            {
                get
                {
                    return _teradata150Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Teradata150 item info.
            /// </summary>
            [RepositoryItemInfo("906ee06c-bcdf-4e8e-aa54-0f94890646b5")]
            public virtual RepoItemInfo Teradata150Info
            {
                get
                {
                    return _teradata150Info;
                }
            }

            /// <summary>
            /// The Vertica91 item.
            /// </summary>
            [RepositoryItem("e8b4899d-57ca-4936-8568-a1d20a783207")]
            public virtual Ranorex.TreeItem Vertica91
            {
                get
                {
                    return _vertica91Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Vertica91 item info.
            /// </summary>
            [RepositoryItemInfo("e8b4899d-57ca-4936-8568-a1d20a783207")]
            public virtual RepoItemInfo Vertica91Info
            {
                get
                {
                    return _vertica91Info;
                }
            }

            /// <summary>
            /// The Vertica80 item.
            /// </summary>
            [RepositoryItem("8295a42b-eddd-44e0-a636-222c74a9b3cc")]
            public virtual Ranorex.TreeItem Vertica80
            {
                get
                {
                    return _vertica80Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Vertica80 item info.
            /// </summary>
            [RepositoryItemInfo("8295a42b-eddd-44e0-a636-222c74a9b3cc")]
            public virtual RepoItemInfo Vertica80Info
            {
                get
                {
                    return _vertica80Info;
                }
            }
        }

        /// <summary>
        /// The OpenAppFolder folder.
        /// </summary>
        [RepositoryFolder("a99d421a-97b3-4265-90b5-6107761dfe5a")]
        public partial class OpenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filepathtextboxInfo;
            RepoItemInfo _openbuttonInfo;
            RepoItemInfo _queryscriptlistInfo;

            /// <summary>
            /// Creates a new Open  folder.
            /// </summary>
            public OpenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open", "/form[@title='Open']", parentFolder, 30000, null, true, "a99d421a-97b3-4265-90b5-6107761dfe5a", "")
            {
                _filepathtextboxInfo = new RepoItemInfo(this, "FilePathTextbox", ".//element/container[@type='JPanel']/container[3]/container[2]/text[@accessiblename='File name:']", 30000, null, "47729d75-6bd1-41a2-a48d-8f6c2a1e4e67");
                _openbuttonInfo = new RepoItemInfo(this, "OpenButton", ".//element/container[@type='JPanel']/container[3]/container[3]/button[@text='Open']", 30000, null, "7af65833-2a49-4b15-825e-494d8b0a72d5");
                _queryscriptlistInfo = new RepoItemInfo(this, "QueryScriptList", ".//element/container[@type='JPanel']/container[@type='FilePane']//container[@name='viewport']/list[@name='list']", 30000, null, "e8594f2f-3579-49eb-9749-0642268827f5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a99d421a-97b3-4265-90b5-6107761dfe5a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a99d421a-97b3-4265-90b5-6107761dfe5a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilePathTextbox item.
            /// </summary>
            [RepositoryItem("47729d75-6bd1-41a2-a48d-8f6c2a1e4e67")]
            public virtual Ranorex.Text FilePathTextbox
            {
                get
                {
                    return _filepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilePathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("47729d75-6bd1-41a2-a48d-8f6c2a1e4e67")]
            public virtual RepoItemInfo FilePathTextboxInfo
            {
                get
                {
                    return _filepathtextboxInfo;
                }
            }

            /// <summary>
            /// The OpenButton item.
            /// </summary>
            [RepositoryItem("7af65833-2a49-4b15-825e-494d8b0a72d5")]
            public virtual Ranorex.Button OpenButton
            {
                get
                {
                    return _openbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenButton item info.
            /// </summary>
            [RepositoryItemInfo("7af65833-2a49-4b15-825e-494d8b0a72d5")]
            public virtual RepoItemInfo OpenButtonInfo
            {
                get
                {
                    return _openbuttonInfo;
                }
            }

            /// <summary>
            /// The QueryScriptList item.
            /// </summary>
            [RepositoryItem("e8594f2f-3579-49eb-9749-0642268827f5")]
            public virtual Ranorex.List QueryScriptList
            {
                get
                {
                    return _queryscriptlistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The QueryScriptList item info.
            /// </summary>
            [RepositoryItemInfo("e8594f2f-3579-49eb-9749-0642268827f5")]
            public virtual RepoItemInfo QueryScriptListInfo
            {
                get
                {
                    return _queryscriptlistInfo;
                }
            }
        }

        /// <summary>
        /// The QueryAnalyzerAppFolder folder.
        /// </summary>
        [RepositoryFolder("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
        public partial class QueryAnalyzerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _qacombotextboxInfo;
            RepoItemInfo _tab2qacombotextboxInfo;
            RepoItemInfo _tabInfo;
            RepoItemInfo _schemaqacombotextboxInfo;
            RepoItemInfo _tab2schemaqacombotextboxInfo;
            RepoItemInfo _tabcontainerInfo;
            RepoItemInfo _openqueryscriptInfo;

            /// <summary>
            /// Creates a new QueryAnalyzer  folder.
            /// </summary>
            public QueryAnalyzerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QueryAnalyzer", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "f6b88477-0d52-45f6-b295-5d8cf5cea688", "")
            {
                _qacombotextboxInfo = new RepoItemInfo(this, "QAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[1]/container[2]//container[@name='panelBar']//combobox[@name='databaseField']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "09d3daa1-1798-48ca-99ca-306a7b1572fe");
                _tab2qacombotextboxInfo = new RepoItemInfo(this, "Tab2QAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[1]/container[3]//container[@name='panelBar']//combobox[@name='databaseField']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "2e185ac3-4ea0-42db-b67b-2eebff89eb85");
                _tabInfo = new RepoItemInfo(this, "Tab", ".//container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//tabpage", 30000, null, "e2c06e88-20ad-4410-be03-61eeb00e94dd");
                _schemaqacombotextboxInfo = new RepoItemInfo(this, "SchemaQAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='schemaComboPanel']/combobox[@name='schemaCombo']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "92695ac7-b5a3-4868-9f78-b347027a7d80");
                _tab2schemaqacombotextboxInfo = new RepoItemInfo(this, "Tab2SchemaQAComboTextbox", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']/?/?/container[1]/container[3]//container[@name='schemaComboPanel']/combobox[@name='schemaCombo']/text[@type='BasicComboBoxEditor$BorderlessTextField']", 30000, null, "35c96d7a-7965-4c2a-a10e-ba6ad010759d");
                _tabcontainerInfo = new RepoItemInfo(this, "TabContainer", ".//container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']", 30000, null, "28f098d2-0f72-48ab-8e8a-dfef47934a3c");
                _openqueryscriptInfo = new RepoItemInfo(this, "OpenQueryScript", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='editorToolBar']/button[2]", 30000, null, "4aca1bf9-54b1-4316-b193-5c73f0614575");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f6b88477-0d52-45f6-b295-5d8cf5cea688")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QAComboTextbox item.
            /// </summary>
            [RepositoryItem("09d3daa1-1798-48ca-99ca-306a7b1572fe")]
            public virtual Ranorex.Text QAComboTextbox
            {
                get
                {
                    return _qacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The QAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("09d3daa1-1798-48ca-99ca-306a7b1572fe")]
            public virtual RepoItemInfo QAComboTextboxInfo
            {
                get
                {
                    return _qacombotextboxInfo;
                }
            }

            /// <summary>
            /// The Tab2QAComboTextbox item.
            /// </summary>
            [RepositoryItem("2e185ac3-4ea0-42db-b67b-2eebff89eb85")]
            public virtual Ranorex.Text Tab2QAComboTextbox
            {
                get
                {
                    return _tab2qacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Tab2QAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("2e185ac3-4ea0-42db-b67b-2eebff89eb85")]
            public virtual RepoItemInfo Tab2QAComboTextboxInfo
            {
                get
                {
                    return _tab2qacombotextboxInfo;
                }
            }

            /// <summary>
            /// The Tab item.
            /// </summary>
            [RepositoryItem("e2c06e88-20ad-4410-be03-61eeb00e94dd")]
            public virtual Ranorex.TabPage Tab
            {
                get
                {
                    return _tabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab item info.
            /// </summary>
            [RepositoryItemInfo("e2c06e88-20ad-4410-be03-61eeb00e94dd")]
            public virtual RepoItemInfo TabInfo
            {
                get
                {
                    return _tabInfo;
                }
            }

            /// <summary>
            /// The SchemaQAComboTextbox item.
            /// </summary>
            [RepositoryItem("92695ac7-b5a3-4868-9f78-b347027a7d80")]
            public virtual Ranorex.Text SchemaQAComboTextbox
            {
                get
                {
                    return _schemaqacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SchemaQAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("92695ac7-b5a3-4868-9f78-b347027a7d80")]
            public virtual RepoItemInfo SchemaQAComboTextboxInfo
            {
                get
                {
                    return _schemaqacombotextboxInfo;
                }
            }

            /// <summary>
            /// The Tab2SchemaQAComboTextbox item.
            /// </summary>
            [RepositoryItem("35c96d7a-7965-4c2a-a10e-ba6ad010759d")]
            public virtual Ranorex.Text Tab2SchemaQAComboTextbox
            {
                get
                {
                    return _tab2schemaqacombotextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Tab2SchemaQAComboTextbox item info.
            /// </summary>
            [RepositoryItemInfo("35c96d7a-7965-4c2a-a10e-ba6ad010759d")]
            public virtual RepoItemInfo Tab2SchemaQAComboTextboxInfo
            {
                get
                {
                    return _tab2schemaqacombotextboxInfo;
                }
            }

            /// <summary>
            /// The TabContainer item.
            /// </summary>
            [RepositoryItem("28f098d2-0f72-48ab-8e8a-dfef47934a3c")]
            public virtual Ranorex.Container TabContainer
            {
                get
                {
                    return _tabcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The TabContainer item info.
            /// </summary>
            [RepositoryItemInfo("28f098d2-0f72-48ab-8e8a-dfef47934a3c")]
            public virtual RepoItemInfo TabContainerInfo
            {
                get
                {
                    return _tabcontainerInfo;
                }
            }

            /// <summary>
            /// The OpenQueryScript item.
            /// </summary>
            [RepositoryItem("4aca1bf9-54b1-4316-b193-5c73f0614575")]
            public virtual Ranorex.Button OpenQueryScript
            {
                get
                {
                    return _openqueryscriptInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenQueryScript item info.
            /// </summary>
            [RepositoryItemInfo("4aca1bf9-54b1-4316-b193-5c73f0614575")]
            public virtual RepoItemInfo OpenQueryScriptInfo
            {
                get
                {
                    return _openqueryscriptInfo;
                }
            }
        }

        /// <summary>
        /// The QueryAnalyzerComboListAppFolder folder.
        /// </summary>
        [RepositoryFolder("de5f70d9-1502-4cd6-a43b-0af6a65cb1da")]
        public partial class QueryAnalyzerComboListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _dbserverlistInfo;

            /// <summary>
            /// Creates a new QueryAnalyzerComboList  folder.
            /// </summary>
            public QueryAnalyzerComboListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("QueryAnalyzerComboList", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "de5f70d9-1502-4cd6-a43b-0af6a65cb1da", "")
            {
                _dbserverlistInfo = new RepoItemInfo(this, "DBServerList", ".//container/list[@name='ComboBox.list']", 30000, null, "8d7a4e32-5d3b-4671-808f-779dad01ab9b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("de5f70d9-1502-4cd6-a43b-0af6a65cb1da")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("de5f70d9-1502-4cd6-a43b-0af6a65cb1da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DBServerList item.
            /// </summary>
            [RepositoryItem("8d7a4e32-5d3b-4671-808f-779dad01ab9b")]
            public virtual Ranorex.List DBServerList
            {
                get
                {
                    return _dbserverlistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The DBServerList item info.
            /// </summary>
            [RepositoryItemInfo("8d7a4e32-5d3b-4671-808f-779dad01ab9b")]
            public virtual RepoItemInfo DBServerListInfo
            {
                get
                {
                    return _dbserverlistInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ba75842-e062-4ee1-878c-350ec8f536fe")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closetabInfo;
            RepoItemInfo _closealltabsInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "7ba75842-e062-4ee1-878c-350ec8f536fe", "")
            {
                _closetabInfo = new RepoItemInfo(this, "CloseTab", ".//menuitem[@name='TabDocumentPane.close']", 30000, null, "eb500414-461b-4b47-ab8a-2c04c611db2b");
                _closealltabsInfo = new RepoItemInfo(this, "CloseAllTabs", ".//menuitem[@name='TabDocumentPane.closeAll']", 30000, null, "5b0bad73-9b95-4fbe-8c2b-3e3f8776a9ef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ba75842-e062-4ee1-878c-350ec8f536fe")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ba75842-e062-4ee1-878c-350ec8f536fe")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseTab item.
            /// </summary>
            [RepositoryItem("eb500414-461b-4b47-ab8a-2c04c611db2b")]
            public virtual Ranorex.MenuItem CloseTab
            {
                get
                {
                    return _closetabInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CloseTab item info.
            /// </summary>
            [RepositoryItemInfo("eb500414-461b-4b47-ab8a-2c04c611db2b")]
            public virtual RepoItemInfo CloseTabInfo
            {
                get
                {
                    return _closetabInfo;
                }
            }

            /// <summary>
            /// The CloseAllTabs item.
            /// </summary>
            [RepositoryItem("5b0bad73-9b95-4fbe-8c2b-3e3f8776a9ef")]
            public virtual Ranorex.MenuItem CloseAllTabs
            {
                get
                {
                    return _closealltabsInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The CloseAllTabs item info.
            /// </summary>
            [RepositoryItemInfo("5b0bad73-9b95-4fbe-8c2b-3e3f8776a9ef")]
            public virtual RepoItemInfo CloseAllTabsInfo
            {
                get
                {
                    return _closealltabsInfo;
                }
            }
        }

        /// <summary>
        /// The ConnectionAppFolder folder.
        /// </summary>
        [RepositoryFolder("e599b4c8-b2ab-4900-bf15-d9fe4abbf4d0")]
        public partial class ConnectionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _serverconnectionInfo;
            RepoItemInfo _retrybuttonInfo;
            RepoItemInfo _closebuttonInfo;

            /// <summary>
            /// Creates a new Connection  folder.
            /// </summary>
            public ConnectionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Connection", "/form[@title~'^Aqua Data Studio']", parentFolder, 30000, null, true, "e599b4c8-b2ab-4900-bf15-d9fe4abbf4d0", "")
            {
                _serverconnectionInfo = new RepoItemInfo(this, "ServerConnection", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text~'^{0}']/treeitem[@text~'^Databases' or @text~'^Keyspaces' or @text~'^Schema']", 30000, null, "1f42b2e7-f708-4fcc-980e-77acbd16e1b0");
                _retrybuttonInfo = new RepoItemInfo(this, "RetryButton", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//button[@text='Retry']", 30000, null, "3e736ddd-c22f-4337-b4e4-34055be540bd");
                _closebuttonInfo = new RepoItemInfo(this, "CloseButton", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//button[@text='Close']", 30000, null, "e83204f2-6db8-481e-8667-ce8e32c30bc5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e599b4c8-b2ab-4900-bf15-d9fe4abbf4d0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e599b4c8-b2ab-4900-bf15-d9fe4abbf4d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ServerConnection item.
            /// </summary>
            [RepositoryItem("1f42b2e7-f708-4fcc-980e-77acbd16e1b0")]
            public virtual Ranorex.TreeItem ServerConnection
            {
                get
                {
                    return _serverconnectionInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The ServerConnection item info.
            /// </summary>
            [RepositoryItemInfo("1f42b2e7-f708-4fcc-980e-77acbd16e1b0")]
            public virtual RepoItemInfo ServerConnectionInfo
            {
                get
                {
                    return _serverconnectionInfo;
                }
            }

            /// <summary>
            /// The RetryButton item.
            /// </summary>
            [RepositoryItem("3e736ddd-c22f-4337-b4e4-34055be540bd")]
            public virtual Ranorex.Button RetryButton
            {
                get
                {
                    return _retrybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RetryButton item info.
            /// </summary>
            [RepositoryItemInfo("3e736ddd-c22f-4337-b4e4-34055be540bd")]
            public virtual RepoItemInfo RetryButtonInfo
            {
                get
                {
                    return _retrybuttonInfo;
                }
            }

            /// <summary>
            /// The CloseButton item.
            /// </summary>
            [RepositoryItem("e83204f2-6db8-481e-8667-ce8e32c30bc5")]
            public virtual Ranorex.Button CloseButton
            {
                get
                {
                    return _closebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseButton item info.
            /// </summary>
            [RepositoryItemInfo("e83204f2-6db8-481e-8667-ce8e32c30bc5")]
            public virtual RepoItemInfo CloseButtonInfo
            {
                get
                {
                    return _closebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The FileModifiedAppFolder folder.
        /// </summary>
        [RepositoryFolder("81da30cb-ca00-4399-8303-a8969123f60e")]
        public partial class FileModifiedAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardbuttonInfo;

            /// <summary>
            /// Creates a new FileModified  folder.
            /// </summary>
            public FileModifiedAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FileModified", "/form[@title='File Modified']", parentFolder, 30000, null, true, "81da30cb-ca00-4399-8303-a8969123f60e", "")
            {
                _discardbuttonInfo = new RepoItemInfo(this, "DiscardButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "b3dc419b-e38e-45be-944f-cac3c1b2ebf1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("81da30cb-ca00-4399-8303-a8969123f60e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("81da30cb-ca00-4399-8303-a8969123f60e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DiscardButton item.
            /// </summary>
            [RepositoryItem("b3dc419b-e38e-45be-944f-cac3c1b2ebf1")]
            public virtual Ranorex.Button DiscardButton
            {
                get
                {
                    return _discardbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DiscardButton item info.
            /// </summary>
            [RepositoryItemInfo("b3dc419b-e38e-45be-944f-cac3c1b2ebf1")]
            public virtual RepoItemInfo DiscardButtonInfo
            {
                get
                {
                    return _discardbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}