///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10560
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10560Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("45fa9af7-c8e5-43bc-8ced-cb4c6ec99156")]
    public partial class TC10560Repo : RepoGenBaseFolder
    {
        static TC10560Repo instance = new TC10560Repo();
        TC10560RepoFolders.ApplicationAppFolder _application;
        TC10560RepoFolders.DataStudioAppFolder _datastudio;
        TC10560RepoFolders.OpenWindowAppFolder _openwindow;
        TC10560RepoFolders.ChartPropertiesWindowAppFolder _chartpropertieswindow;
        TC10560RepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        TC10560RepoFolders.SaveChangesAppFolder _savechanges;
        TC10560RepoFolders.LabelWindowAppFolder _labelwindow;
        TC10560RepoFolders.VAWindowAppFolder _vawindow;
        TC10560RepoFolders.VATestAppFolder _vatest;

        /// <summary>
        /// Gets the singleton class instance representing the TC10560Repo element repository.
        /// </summary>
        [RepositoryFolder("45fa9af7-c8e5-43bc-8ced-cb4c6ec99156")]
        public static TC10560Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10560Repo() 
            : base("TC10560Repo", "/", null, 0, false, "45fa9af7-c8e5-43bc-8ced-cb4c6ec99156", ".\\RepositoryImages\\TC10560Repo45fa9af7.rximgres")
        {
            _application = new TC10560RepoFolders.ApplicationAppFolder(this);
            _datastudio = new TC10560RepoFolders.DataStudioAppFolder(this);
            _openwindow = new TC10560RepoFolders.OpenWindowAppFolder(this);
            _chartpropertieswindow = new TC10560RepoFolders.ChartPropertiesWindowAppFolder(this);
            _sunawtwindow = new TC10560RepoFolders.SunAwtWindowAppFolder(this);
            _savechanges = new TC10560RepoFolders.SaveChangesAppFolder(this);
            _labelwindow = new TC10560RepoFolders.LabelWindowAppFolder(this);
            _vawindow = new TC10560RepoFolders.VAWindowAppFolder(this);
            _vatest = new TC10560RepoFolders.VATestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("45fa9af7-c8e5-43bc-8ced-cb4c6ec99156")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public virtual TC10560RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The DataStudio folder.
        /// </summary>
        [RepositoryFolder("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
        public virtual TC10560RepoFolders.DataStudioAppFolder DataStudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The OpenWindow folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public virtual TC10560RepoFolders.OpenWindowAppFolder OpenWindow
        {
            get { return _openwindow; }
        }

        /// <summary>
        /// The ChartPropertiesWindow folder.
        /// </summary>
        [RepositoryFolder("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
        public virtual TC10560RepoFolders.ChartPropertiesWindowAppFolder ChartPropertiesWindow
        {
            get { return _chartpropertieswindow; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
        public virtual TC10560RepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The SaveChanges folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public virtual TC10560RepoFolders.SaveChangesAppFolder SaveChanges
        {
            get { return _savechanges; }
        }

        /// <summary>
        /// The LabelWindow folder.
        /// </summary>
        [RepositoryFolder("86c48c36-7d84-41a5-9bfd-48688233bff3")]
        public virtual TC10560RepoFolders.LabelWindowAppFolder LabelWindow
        {
            get { return _labelwindow; }
        }

        /// <summary>
        /// The VAWindow folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public virtual TC10560RepoFolders.VAWindowAppFolder VAWindow
        {
            get { return _vawindow; }
        }

        /// <summary>
        /// The VATest folder.
        /// </summary>
        [RepositoryFolder("4d7a938e-e7f8-4452-b177-5e7e99b536d0")]
        public virtual TC10560RepoFolders.VATestAppFolder VATest
        {
            get { return _vatest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10560RepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filemenuInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "d54a3fac-3b92-4b4a-9c2b-770fb3053792", "")
            {
                _filemenuInfo = new RepoItemInfo(this, "FileMenu", ".//menuitem[@text='File']", 30000, null, "da992c0f-dfcc-4c8a-a60b-60218253b432");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileMenu item.
            /// </summary>
            [RepositoryItem("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual Ranorex.MenuItem FileMenu
            {
                get
                {
                    return _filemenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FileMenu item info.
            /// </summary>
            [RepositoryItemInfo("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual RepoItemInfo FileMenuInfo
            {
                get
                {
                    return _filemenuInfo;
                }
            }
        }

        /// <summary>
        /// The DataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
        public partial class DataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openfileInfo;

            /// <summary>
            /// Creates a new DataStudio  folder.
            /// </summary>
            public DataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataStudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "bd2e48e4-5445-4ec3-a9b7-23d20f08afdb", "")
            {
                _openfileInfo = new RepoItemInfo(this, "OpenFile", ".//menuitem[@text='Open']", 30000, null, "4f2dba1a-2292-46cf-a03d-955d59d8f39c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenFile item.
            /// </summary>
            [RepositoryItem("4f2dba1a-2292-46cf-a03d-955d59d8f39c")]
            public virtual Ranorex.MenuItem OpenFile
            {
                get
                {
                    return _openfileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The OpenFile item info.
            /// </summary>
            [RepositoryItemInfo("4f2dba1a-2292-46cf-a03d-955d59d8f39c")]
            public virtual RepoItemInfo OpenFileInfo
            {
                get
                {
                    return _openfileInfo;
                }
            }
        }

        /// <summary>
        /// The OpenWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public partial class OpenWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filepathtextboxInfo;
            RepoItemInfo _openbuttonInfo;

            /// <summary>
            /// Creates a new OpenWindow  folder.
            /// </summary>
            public OpenWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenWindow", "/form[@title='Open']", parentFolder, 30000, null, true, "951fcb26-33b8-49e9-9d15-b9683c621e3f", "")
            {
                _filepathtextboxInfo = new RepoItemInfo(this, "FilePathTextbox", ".//element/container[@type='JPanel']/container[3]/container[2]/text[@accessiblename='File name:']", 30000, null, "5d62603f-d3ac-4200-9d2a-4347326a6699");
                _openbuttonInfo = new RepoItemInfo(this, "OpenButton", ".//element/container[@type='JPanel']/container[3]/container[3]/button[@text='Open']", 30000, null, "89dcbd3d-2d03-4a6b-ad50-32f672ff7e54");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilePathTextbox item.
            /// </summary>
            [RepositoryItem("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual Ranorex.Text FilePathTextbox
            {
                get
                {
                    return _filepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilePathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual RepoItemInfo FilePathTextboxInfo
            {
                get
                {
                    return _filepathtextboxInfo;
                }
            }

            /// <summary>
            /// The OpenButton item.
            /// </summary>
            [RepositoryItem("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual Ranorex.Button OpenButton
            {
                get
                {
                    return _openbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenButton item info.
            /// </summary>
            [RepositoryItemInfo("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual RepoItemInfo OpenButtonInfo
            {
                get
                {
                    return _openbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ChartPropertiesWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
        public partial class ChartPropertiesWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _automaticInfo;
            RepoItemInfo _selectpointInfo;
            RepoItemInfo _labelInfo;
            RepoItemInfo _axesInfo;
            RepoItemInfo _yearInfo;
            RepoItemInfo _standardcomboInfo;

            /// <summary>
            /// Creates a new ChartPropertiesWindow  folder.
            /// </summary>
            public ChartPropertiesWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ChartPropertiesWindow", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[VA-te']", parentFolder, 30000, null, true, "7c7be239-e782-4085-b7f6-08e0c4bd0bc5", "")
            {
                _automaticInfo = new RepoItemInfo(this, "Automatic", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']", 30000, null, "bd98091f-27c9-409b-80fb-c1053d253c93");
                _selectpointInfo = new RepoItemInfo(this, "SelectPoint", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']/button[@text='']", 30000, null, "0920f1be-53cf-4c78-a2d8-266f9c5f1f73");
                _labelInfo = new RepoItemInfo(this, "Label", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Label']", 30000, null, "6b010cb4-fd39-4b79-bf27-00f442d6bc6d");
                _axesInfo = new RepoItemInfo(this, "Axes", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Axes']", 30000, null, "c8237154-5d8f-48a6-b244-206645e5de9a");
                _yearInfo = new RepoItemInfo(this, "Year", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='cols']//text[@caption='YEAR(ShipDate)']", 30000, null, "e90efb67-ad2a-41c2-a64d-fa0831b973da");
                _standardcomboInfo = new RepoItemInfo(this, "StandardCombo", ".//container[@type='CPanel']/combobox[@type='CComboBox']", 30000, null, "003db0ab-cc1b-4c36-873f-49a6d23d6e29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Automatic item.
            /// </summary>
            [RepositoryItem("bd98091f-27c9-409b-80fb-c1053d253c93")]
            public virtual Ranorex.ComboBox Automatic
            {
                get
                {
                    return _automaticInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Automatic item info.
            /// </summary>
            [RepositoryItemInfo("bd98091f-27c9-409b-80fb-c1053d253c93")]
            public virtual RepoItemInfo AutomaticInfo
            {
                get
                {
                    return _automaticInfo;
                }
            }

            /// <summary>
            /// The SelectPoint item.
            /// </summary>
            [RepositoryItem("0920f1be-53cf-4c78-a2d8-266f9c5f1f73")]
            public virtual Ranorex.Button SelectPoint
            {
                get
                {
                    return _selectpointInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SelectPoint item info.
            /// </summary>
            [RepositoryItemInfo("0920f1be-53cf-4c78-a2d8-266f9c5f1f73")]
            public virtual RepoItemInfo SelectPointInfo
            {
                get
                {
                    return _selectpointInfo;
                }
            }

            /// <summary>
            /// The Label item.
            /// </summary>
            [RepositoryItem("6b010cb4-fd39-4b79-bf27-00f442d6bc6d")]
            public virtual Ranorex.Text Label
            {
                get
                {
                    return _labelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label item info.
            /// </summary>
            [RepositoryItemInfo("6b010cb4-fd39-4b79-bf27-00f442d6bc6d")]
            public virtual RepoItemInfo LabelInfo
            {
                get
                {
                    return _labelInfo;
                }
            }

            /// <summary>
            /// The Axes item.
            /// </summary>
            [RepositoryItem("c8237154-5d8f-48a6-b244-206645e5de9a")]
            public virtual Ranorex.Text Axes
            {
                get
                {
                    return _axesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Axes item info.
            /// </summary>
            [RepositoryItemInfo("c8237154-5d8f-48a6-b244-206645e5de9a")]
            public virtual RepoItemInfo AxesInfo
            {
                get
                {
                    return _axesInfo;
                }
            }

            /// <summary>
            /// The Year item.
            /// </summary>
            [RepositoryItem("e90efb67-ad2a-41c2-a64d-fa0831b973da")]
            public virtual Ranorex.Text Year
            {
                get
                {
                    return _yearInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Year item info.
            /// </summary>
            [RepositoryItemInfo("e90efb67-ad2a-41c2-a64d-fa0831b973da")]
            public virtual RepoItemInfo YearInfo
            {
                get
                {
                    return _yearInfo;
                }
            }

            /// <summary>
            /// The StandardCombo item.
            /// </summary>
            [RepositoryItem("003db0ab-cc1b-4c36-873f-49a6d23d6e29")]
            public virtual Ranorex.ComboBox StandardCombo
            {
                get
                {
                    return _standardcomboInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The StandardCombo item info.
            /// </summary>
            [RepositoryItemInfo("003db0ab-cc1b-4c36-873f-49a6d23d6e29")]
            public virtual RepoItemInfo StandardComboInfo
            {
                get
                {
                    return _standardcomboInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contextmenuInfo;
            RepoItemInfo _areaInfo;
            RepoItemInfo _removeInfo;
            RepoItemInfo _entirewindowInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "84776f98-4aaa-4246-9a0b-9355abb3cff6", "")
            {
                _contextmenuInfo = new RepoItemInfo(this, "ContextMenu", ".//contextmenu", 30000, null, "a21e0391-83f9-4568-8f40-951dfd79f0c6");
                _areaInfo = new RepoItemInfo(this, "Area", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Area']", 30000, null, "6003f470-3702-4ba4-a527-bb6064c8e8c5");
                _removeInfo = new RepoItemInfo(this, "Remove", ".//menuitem[@text='Remove']", 30000, null, "0f45ee56-4ec4-4009-a610-615a5f57b460");
                _entirewindowInfo = new RepoItemInfo(this, "EntireWindow", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Entire View']", 30000, null, "01c44355-2853-40fd-b196-fa0c15e2f64f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContextMenu item.
            /// </summary>
            [RepositoryItem("a21e0391-83f9-4568-8f40-951dfd79f0c6")]
            public virtual Ranorex.ContextMenu ContextMenu
            {
                get
                {
                    return _contextmenuInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The ContextMenu item info.
            /// </summary>
            [RepositoryItemInfo("a21e0391-83f9-4568-8f40-951dfd79f0c6")]
            public virtual RepoItemInfo ContextMenuInfo
            {
                get
                {
                    return _contextmenuInfo;
                }
            }

            /// <summary>
            /// The Area item.
            /// </summary>
            [RepositoryItem("6003f470-3702-4ba4-a527-bb6064c8e8c5")]
            public virtual Ranorex.ListItem Area
            {
                get
                {
                    return _areaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Area item info.
            /// </summary>
            [RepositoryItemInfo("6003f470-3702-4ba4-a527-bb6064c8e8c5")]
            public virtual RepoItemInfo AreaInfo
            {
                get
                {
                    return _areaInfo;
                }
            }

            /// <summary>
            /// The Remove item.
            /// </summary>
            [RepositoryItem("0f45ee56-4ec4-4009-a610-615a5f57b460")]
            public virtual Ranorex.MenuItem Remove
            {
                get
                {
                    return _removeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Remove item info.
            /// </summary>
            [RepositoryItemInfo("0f45ee56-4ec4-4009-a610-615a5f57b460")]
            public virtual RepoItemInfo RemoveInfo
            {
                get
                {
                    return _removeInfo;
                }
            }

            /// <summary>
            /// The EntireWindow item.
            /// </summary>
            [RepositoryItem("01c44355-2853-40fd-b196-fa0c15e2f64f")]
            public virtual Ranorex.ListItem EntireWindow
            {
                get
                {
                    return _entirewindowInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The EntireWindow item info.
            /// </summary>
            [RepositoryItemInfo("01c44355-2853-40fd-b196-fa0c15e2f64f")]
            public virtual RepoItemInfo EntireWindowInfo
            {
                get
                {
                    return _entirewindowInfo;
                }
            }
        }

        /// <summary>
        /// The SaveChangesAppFolder folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public partial class SaveChangesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardbuttonInfo;

            /// <summary>
            /// Creates a new SaveChanges  folder.
            /// </summary>
            public SaveChangesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveChanges", "/form[@title='Save Changes']", parentFolder, 30000, null, true, "e023f516-9d72-4d93-987f-b52734da129a", "")
            {
                _discardbuttonInfo = new RepoItemInfo(this, "DiscardButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "2f6a6708-f14b-4f61-b831-60b96d7c607d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DiscardButton item.
            /// </summary>
            [RepositoryItem("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual Ranorex.Button DiscardButton
            {
                get
                {
                    return _discardbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DiscardButton item info.
            /// </summary>
            [RepositoryItemInfo("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual RepoItemInfo DiscardButtonInfo
            {
                get
                {
                    return _discardbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The LabelWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("86c48c36-7d84-41a5-9bfd-48688233bff3")]
        public partial class LabelWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _showdataInfo;
            RepoItemInfo _mergedaxesInfo;
            RepoItemInfo _mergedseparateInfo;
            RepoItemInfo _dualaxesInfo;
            RepoItemInfo _unstackedInfo;

            /// <summary>
            /// Creates a new LabelWindow  folder.
            /// </summary>
            public LabelWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LabelWindow", "/form", parentFolder, 30000, null, true, "86c48c36-7d84-41a5-9bfd-48688233bff3", "")
            {
                _showdataInfo = new RepoItemInfo(this, "ShowData", ".//container[@accessiblename='Data Labels']/?/?/checkbox[@text='Show Data Labels']", 30000, null, "dfa9df49-e585-431d-8d78-85532a0b7e78");
                _mergedaxesInfo = new RepoItemInfo(this, "MergedAxes", ".//container[@accessiblename='Axes Type']/?/?/radiobutton[@text='Merged Axes, Shared Scale']", 30000, null, "5718b02d-ac1f-40fe-852e-9db70fd8ec38");
                _mergedseparateInfo = new RepoItemInfo(this, "MergedSeparate", ".//container[@accessiblename='Axes Type']/?/?/radiobutton[@text~'^Merged\\ Axes,\\ Separate\\ Sca']", 30000, null, "c7e7237c-c04c-48cc-8518-993387324f50");
                _dualaxesInfo = new RepoItemInfo(this, "DualAxes", ".//container[@accessiblename='Axes Type']/?/?/radiobutton[@text='Dual Axes']", 30000, null, "d186d8f1-bd36-4a65-9cdc-7d1fcb95138e");
                _unstackedInfo = new RepoItemInfo(this, "Unstacked", ".//container[@accessiblename='Display Style']/?/?/radiobutton[@text='Unstacked']", 30000, null, "38a3f9bd-becc-4fd2-9963-f5f7dbb65acc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86c48c36-7d84-41a5-9bfd-48688233bff3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86c48c36-7d84-41a5-9bfd-48688233bff3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ShowData item.
            /// </summary>
            [RepositoryItem("dfa9df49-e585-431d-8d78-85532a0b7e78")]
            public virtual Ranorex.CheckBox ShowData
            {
                get
                {
                    return _showdataInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ShowData item info.
            /// </summary>
            [RepositoryItemInfo("dfa9df49-e585-431d-8d78-85532a0b7e78")]
            public virtual RepoItemInfo ShowDataInfo
            {
                get
                {
                    return _showdataInfo;
                }
            }

            /// <summary>
            /// The MergedAxes item.
            /// </summary>
            [RepositoryItem("5718b02d-ac1f-40fe-852e-9db70fd8ec38")]
            public virtual Ranorex.RadioButton MergedAxes
            {
                get
                {
                    return _mergedaxesInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MergedAxes item info.
            /// </summary>
            [RepositoryItemInfo("5718b02d-ac1f-40fe-852e-9db70fd8ec38")]
            public virtual RepoItemInfo MergedAxesInfo
            {
                get
                {
                    return _mergedaxesInfo;
                }
            }

            /// <summary>
            /// The MergedSeparate item.
            /// </summary>
            [RepositoryItem("c7e7237c-c04c-48cc-8518-993387324f50")]
            public virtual Ranorex.RadioButton MergedSeparate
            {
                get
                {
                    return _mergedseparateInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MergedSeparate item info.
            /// </summary>
            [RepositoryItemInfo("c7e7237c-c04c-48cc-8518-993387324f50")]
            public virtual RepoItemInfo MergedSeparateInfo
            {
                get
                {
                    return _mergedseparateInfo;
                }
            }

            /// <summary>
            /// The DualAxes item.
            /// </summary>
            [RepositoryItem("d186d8f1-bd36-4a65-9cdc-7d1fcb95138e")]
            public virtual Ranorex.RadioButton DualAxes
            {
                get
                {
                    return _dualaxesInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The DualAxes item info.
            /// </summary>
            [RepositoryItemInfo("d186d8f1-bd36-4a65-9cdc-7d1fcb95138e")]
            public virtual RepoItemInfo DualAxesInfo
            {
                get
                {
                    return _dualaxesInfo;
                }
            }

            /// <summary>
            /// The Unstacked item.
            /// </summary>
            [RepositoryItem("38a3f9bd-becc-4fd2-9963-f5f7dbb65acc")]
            public virtual Ranorex.RadioButton Unstacked
            {
                get
                {
                    return _unstackedInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Unstacked item info.
            /// </summary>
            [RepositoryItemInfo("38a3f9bd-becc-4fd2-9963-f5f7dbb65acc")]
            public virtual RepoItemInfo UnstackedInfo
            {
                get
                {
                    return _unstackedInfo;
                }
            }
        }

        /// <summary>
        /// The VAWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public partial class VAWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closewindowInfo;

            /// <summary>
            /// Creates a new VAWindow  folder.
            /// </summary>
            public VAWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VAWindow", "/form[@title~'^Visual\\ Analytics']", parentFolder, 30000, null, true, "28ef3ff7-5142-4c80-9fe2-5119aa3572c6", "")
            {
                _closewindowInfo = new RepoItemInfo(this, "CloseWindow", ".//button[@accessiblename='Close']", 30000, null, "eb7f4e53-1ab2-4471-9058-e4ab8e63fccd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseWindow item.
            /// </summary>
            [RepositoryItem("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual Ranorex.Button CloseWindow
            {
                get
                {
                    return _closewindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseWindow item info.
            /// </summary>
            [RepositoryItemInfo("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual RepoItemInfo CloseWindowInfo
            {
                get
                {
                    return _closewindowInfo;
                }
            }
        }

        /// <summary>
        /// The VATestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4d7a938e-e7f8-4452-b177-5e7e99b536d0")]
        public partial class VATestAppFolder : RepoGenBaseFolder
        {
            TC10560RepoFolders.ContainerContentPanelFolder _containercontentpanel;
            RepoItemInfo _colorInfo;
            RepoItemInfo _panelInfo;
            BIChartOverlayPanelInfoClass _bichartoverlaypanelInfo;
            PivotTableOverlayPanelInfoClass _pivottableoverlaypanelInfo;
            StartWindowInfoClass _startwindowInfo;

            /// <summary>
            /// Creates a new VATest  folder.
            /// </summary>
            public VATestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VATest", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[VA-te']", parentFolder, 30000, null, true, "4d7a938e-e7f8-4452-b177-5e7e99b536d0", "")
            {
                _containercontentpanel = new TC10560RepoFolders.ContainerContentPanelFolder(this);
                _colorInfo = new RepoItemInfo(this, "Color", "container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Color']", 30000, null, "59941f81-7a36-40a8-815e-8ffebdfbdb77");
                _panelInfo = new RepoItemInfo(this, "Panel", "container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='rows']//container[@name='panel']", 30000, null, "1b19b7f6-9a0d-4b6b-b898-4c79d2b94763");
                _bichartoverlaypanelInfo = new BIChartOverlayPanelInfoClass(this);
                _pivottableoverlaypanelInfo = new PivotTableOverlayPanelInfoClass(this);
                _startwindowInfo = new StartWindowInfoClass(this);
            }

            /// <summary>
            /// The BIChartOverlayPanelInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("02536ff8-fe68-476a-945b-297d2d9735c0")]
            public class BIChartOverlayPanelInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BIChartOverlayPanelInfoClass class constructor.
                /// </summary>
                public BIChartOverlayPanelInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "BIChartOverlayPanel", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container", 30000, null, "02536ff8-fe68-476a-945b-297d2d9735c0")
                { }

                /// <summary>
                /// Gets the AreaChart item image.
                /// </summary>
                /// <returns>The AreaChart image.</returns>
                [RepositoryImage("a80b9609-6bb5-441c-b852-db5c235a8ba6")]
                public CompressedImage GetAreaChart()
                {
                    return GetImage("a80b9609-6bb5-441c-b852-db5c235a8ba6");
                }

                /// <summary>
                /// Gets the AreaChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a80b9609-6bb5-441c-b852-db5c235a8ba6")]
                public CompressedImage GetAreaChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a80b9609-6bb5-441c-b852-db5c235a8ba6", cropRect);
                }

                /// <summary>
                /// Gets the CurrencycodeColorChart item image.
                /// </summary>
                /// <returns>The CurrencycodeColorChart image.</returns>
                [RepositoryImage("d0abfd2c-901b-4d69-96f0-26fdd1c6b2ad")]
                public CompressedImage GetCurrencycodeColorChart()
                {
                    return GetImage("d0abfd2c-901b-4d69-96f0-26fdd1c6b2ad");
                }

                /// <summary>
                /// Gets the CurrencycodeColorChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d0abfd2c-901b-4d69-96f0-26fdd1c6b2ad")]
                public CompressedImage GetCurrencycodeColorChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d0abfd2c-901b-4d69-96f0-26fdd1c6b2ad", cropRect);
                }

                /// <summary>
                /// Gets the DragFreightrowChart item image.
                /// </summary>
                /// <returns>The DragFreightrowChart image.</returns>
                [RepositoryImage("ab66263d-a015-462a-bd15-e4b6840e1543")]
                public CompressedImage GetDragFreightrowChart()
                {
                    return GetImage("ab66263d-a015-462a-bd15-e4b6840e1543");
                }

                /// <summary>
                /// Gets the DragFreightrowChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ab66263d-a015-462a-bd15-e4b6840e1543")]
                public CompressedImage GetDragFreightrowChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ab66263d-a015-462a-bd15-e4b6840e1543", cropRect);
                }

                /// <summary>
                /// Gets the DualAxesOption item image.
                /// </summary>
                /// <returns>The DualAxesOption image.</returns>
                [RepositoryImage("f4649017-6c90-4a92-8f90-4d975fc59bad")]
                public CompressedImage GetDualAxesOption()
                {
                    return GetImage("f4649017-6c90-4a92-8f90-4d975fc59bad");
                }

                /// <summary>
                /// Gets the DualAxesOption item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("f4649017-6c90-4a92-8f90-4d975fc59bad")]
                public CompressedImage GetDualAxesOption(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("f4649017-6c90-4a92-8f90-4d975fc59bad", cropRect);
                }

                /// <summary>
                /// Gets the MergedScaleOption item image.
                /// </summary>
                /// <returns>The MergedScaleOption image.</returns>
                [RepositoryImage("53768174-3507-403a-a843-a9132a915fa6")]
                public CompressedImage GetMergedScaleOption()
                {
                    return GetImage("53768174-3507-403a-a843-a9132a915fa6");
                }

                /// <summary>
                /// Gets the MergedScaleOption item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("53768174-3507-403a-a843-a9132a915fa6")]
                public CompressedImage GetMergedScaleOption(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("53768174-3507-403a-a843-a9132a915fa6", cropRect);
                }

                /// <summary>
                /// Gets the MergedSeparateOption item image.
                /// </summary>
                /// <returns>The MergedSeparateOption image.</returns>
                [RepositoryImage("d78b0fd7-6922-4de3-a6aa-2bf7a1bed6c3")]
                public CompressedImage GetMergedSeparateOption()
                {
                    return GetImage("d78b0fd7-6922-4de3-a6aa-2bf7a1bed6c3");
                }

                /// <summary>
                /// Gets the MergedSeparateOption item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d78b0fd7-6922-4de3-a6aa-2bf7a1bed6c3")]
                public CompressedImage GetMergedSeparateOption(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d78b0fd7-6922-4de3-a6aa-2bf7a1bed6c3", cropRect);
                }

                /// <summary>
                /// Gets the ShowData item image.
                /// </summary>
                /// <returns>The ShowData image.</returns>
                [RepositoryImage("90cad4ca-7b4e-4c33-8e3f-1e992ca44f45")]
                public CompressedImage GetShowData()
                {
                    return GetImage("90cad4ca-7b4e-4c33-8e3f-1e992ca44f45");
                }

                /// <summary>
                /// Gets the ShowData item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("90cad4ca-7b4e-4c33-8e3f-1e992ca44f45")]
                public CompressedImage GetShowData(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("90cad4ca-7b4e-4c33-8e3f-1e992ca44f45", cropRect);
                }

                /// <summary>
                /// Gets the UnstackedOption item image.
                /// </summary>
                /// <returns>The UnstackedOption image.</returns>
                [RepositoryImage("056eeb4c-2c55-4cf6-8f00-8e1e817b643c")]
                public CompressedImage GetUnstackedOption()
                {
                    return GetImage("056eeb4c-2c55-4cf6-8f00-8e1e817b643c");
                }

                /// <summary>
                /// Gets the UnstackedOption item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("056eeb4c-2c55-4cf6-8f00-8e1e817b643c")]
                public CompressedImage GetUnstackedOption(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("056eeb4c-2c55-4cf6-8f00-8e1e817b643c", cropRect);
                }
            }

            /// <summary>
            /// The PivotTableOverlayPanelInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("01571173-7974-4b59-92e2-9a482151b49b")]
            public class PivotTableOverlayPanelInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PivotTableOverlayPanelInfoClass class constructor.
                /// </summary>
                public PivotTableOverlayPanelInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PivotTableOverlayPanel", "container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_gridPanel']/?/?/container[@type='PivotTableOverlayPanel']", 30000, null, "01571173-7974-4b59-92e2-9a482151b49b")
                { }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <returns>The VizxDataWindow image.</returns>
                [RepositoryImage("0603a1af-d45d-4988-bcac-4b79eff752c9")]
                public CompressedImage GetVizxDataWindow()
                {
                    return GetImage("0603a1af-d45d-4988-bcac-4b79eff752c9");
                }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0603a1af-d45d-4988-bcac-4b79eff752c9")]
                public CompressedImage GetVizxDataWindow(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0603a1af-d45d-4988-bcac-4b79eff752c9", cropRect);
                }
            }

            /// <summary>
            /// The StartWindowInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9f200710-0a18-4c35-806d-41bf4c188604")]
            public class StartWindowInfoClass : RepoItemInfo
            {
                /// <summary>
                /// StartWindowInfoClass class constructor.
                /// </summary>
                public StartWindowInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "StartWindow", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container", 30000, null, "9f200710-0a18-4c35-806d-41bf4c188604")
                { }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <returns>The VizxDataWindow image.</returns>
                [RepositoryImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e")]
                public CompressedImage GetVizxDataWindow()
                {
                    return GetImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e");
                }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e")]
                public CompressedImage GetVizxDataWindow(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4d7a938e-e7f8-4452-b177-5e7e99b536d0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4d7a938e-e7f8-4452-b177-5e7e99b536d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Color item.
            /// </summary>
            [RepositoryItem("59941f81-7a36-40a8-815e-8ffebdfbdb77")]
            public virtual Ranorex.Text Color
            {
                get
                {
                    return _colorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Color item info.
            /// </summary>
            [RepositoryItemInfo("59941f81-7a36-40a8-815e-8ffebdfbdb77")]
            public virtual RepoItemInfo ColorInfo
            {
                get
                {
                    return _colorInfo;
                }
            }

            /// <summary>
            /// The Panel item.
            /// </summary>
            [RepositoryItem("1b19b7f6-9a0d-4b6b-b898-4c79d2b94763")]
            public virtual Ranorex.Container Panel
            {
                get
                {
                    return _panelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel item info.
            /// </summary>
            [RepositoryItemInfo("1b19b7f6-9a0d-4b6b-b898-4c79d2b94763")]
            public virtual RepoItemInfo PanelInfo
            {
                get
                {
                    return _panelInfo;
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel item.
            /// </summary>
            [RepositoryItem("02536ff8-fe68-476a-945b-297d2d9735c0")]
            public virtual Ranorex.Container BIChartOverlayPanel
            {
                get
                {
                    return _bichartoverlaypanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel item info.
            /// </summary>
            [RepositoryItemInfo("02536ff8-fe68-476a-945b-297d2d9735c0")]
            public virtual BIChartOverlayPanelInfoClass BIChartOverlayPanelInfo
            {
                get
                {
                    return _bichartoverlaypanelInfo;
                }
            }

            /// <summary>
            /// The PivotTableOverlayPanel item.
            /// </summary>
            [RepositoryItem("01571173-7974-4b59-92e2-9a482151b49b")]
            public virtual Ranorex.Container PivotTableOverlayPanel
            {
                get
                {
                    return _pivottableoverlaypanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PivotTableOverlayPanel item info.
            /// </summary>
            [RepositoryItemInfo("01571173-7974-4b59-92e2-9a482151b49b")]
            public virtual PivotTableOverlayPanelInfoClass PivotTableOverlayPanelInfo
            {
                get
                {
                    return _pivottableoverlaypanelInfo;
                }
            }

            /// <summary>
            /// The StartWindow item.
            /// </summary>
            [RepositoryItem("9f200710-0a18-4c35-806d-41bf4c188604")]
            public virtual Ranorex.Container StartWindow
            {
                get
                {
                    return _startwindowInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The StartWindow item info.
            /// </summary>
            [RepositoryItemInfo("9f200710-0a18-4c35-806d-41bf4c188604")]
            public virtual StartWindowInfoClass StartWindowInfo
            {
                get
                {
                    return _startwindowInfo;
                }
            }

            /// <summary>
            /// The ContainerContentPanel folder.
            /// </summary>
            [RepositoryFolder("171f6188-0cbf-493d-bd7d-5febbb601506")]
            public virtual TC10560RepoFolders.ContainerContentPanelFolder ContainerContentPanel
            {
                get { return _containercontentpanel; }
            }
        }

        /// <summary>
        /// The ContainerContentPanelFolder folder.
        /// </summary>
        [RepositoryFolder("171f6188-0cbf-493d-bd7d-5febbb601506")]
        public partial class ContainerContentPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _currencycodeInfo;
            RepoItemInfo _sumfreightInfo;
            RepoItemInfo _rowsInfo;
            RepoItemInfo _multisplitworksheetdollarmultiglasspaneInfo;

            /// <summary>
            /// Creates a new ContainerContentPanel  folder.
            /// </summary>
            public ContainerContentPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerContentPanel", "container[@name='_mainPanel']/container[@name='_contentPanel']", parentFolder, 30000, null, false, "171f6188-0cbf-493d-bd7d-5febbb601506", "")
            {
                _currencycodeInfo = new RepoItemInfo(this, "CurrencyCode", "?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Currency Code']", 30000, null, "361681c9-436f-4e4d-a193-eacb87b0b1cf");
                _sumfreightInfo = new RepoItemInfo(this, "SUMFreight", "?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(Freight)']", 30000, null, "37dc8caa-d130-429e-a483-027c98292d19");
                _rowsInfo = new RepoItemInfo(this, "Rows", "?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='rows']/?/?/text[@caption='Rows']", 30000, null, "da58be8f-8608-4ef5-8894-5a15475b9d84");
                _multisplitworksheetdollarmultiglasspaneInfo = new RepoItemInfo(this, "MultiSplitWorksheetDollarMultiGlassPane", "?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']//element[@type='MultiSplitWorksheet$MultiGlassPane']", 30000, null, "d3cfbcc6-b267-4d45-8f6a-b2d4dc123a96");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("171f6188-0cbf-493d-bd7d-5febbb601506")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("171f6188-0cbf-493d-bd7d-5febbb601506")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CurrencyCode item.
            /// </summary>
            [RepositoryItem("361681c9-436f-4e4d-a193-eacb87b0b1cf")]
            public virtual Ranorex.ListItem CurrencyCode
            {
                get
                {
                    return _currencycodeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CurrencyCode item info.
            /// </summary>
            [RepositoryItemInfo("361681c9-436f-4e4d-a193-eacb87b0b1cf")]
            public virtual RepoItemInfo CurrencyCodeInfo
            {
                get
                {
                    return _currencycodeInfo;
                }
            }

            /// <summary>
            /// The SUMFreight item.
            /// </summary>
            [RepositoryItem("37dc8caa-d130-429e-a483-027c98292d19")]
            public virtual Ranorex.ListItem SUMFreight
            {
                get
                {
                    return _sumfreightInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMFreight item info.
            /// </summary>
            [RepositoryItemInfo("37dc8caa-d130-429e-a483-027c98292d19")]
            public virtual RepoItemInfo SUMFreightInfo
            {
                get
                {
                    return _sumfreightInfo;
                }
            }

            /// <summary>
            /// The Rows item.
            /// </summary>
            [RepositoryItem("da58be8f-8608-4ef5-8894-5a15475b9d84")]
            public virtual Ranorex.Text Rows
            {
                get
                {
                    return _rowsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Rows item info.
            /// </summary>
            [RepositoryItemInfo("da58be8f-8608-4ef5-8894-5a15475b9d84")]
            public virtual RepoItemInfo RowsInfo
            {
                get
                {
                    return _rowsInfo;
                }
            }

            /// <summary>
            /// The MultiSplitWorksheetDollarMultiGlassPane item.
            /// </summary>
            [RepositoryItem("d3cfbcc6-b267-4d45-8f6a-b2d4dc123a96")]
            public virtual Ranorex.Unknown MultiSplitWorksheetDollarMultiGlassPane
            {
                get
                {
                    return _multisplitworksheetdollarmultiglasspaneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MultiSplitWorksheetDollarMultiGlassPane item info.
            /// </summary>
            [RepositoryItemInfo("d3cfbcc6-b267-4d45-8f6a-b2d4dc123a96")]
            public virtual RepoItemInfo MultiSplitWorksheetDollarMultiGlassPaneInfo
            {
                get
                {
                    return _multisplitworksheetdollarmultiglasspaneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}