///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10598
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10598 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("830e38f1-7934-4b8f-873f-19f457318aa3")]
    public partial class TC10598 : RepoGenBaseFolder
    {
        static TC10598 instance = new TC10598();
        TC10598Folders.VisualAnalyticsAppFolder _visualanalytics;
        TC10598Folders.DatastudioAppFolder _datastudio;
        TC10598Folders.SunAwtWindowAppFolder _sunawtwindow;

        /// <summary>
        /// Gets the singleton class instance representing the TC10598 element repository.
        /// </summary>
        [RepositoryFolder("830e38f1-7934-4b8f-873f-19f457318aa3")]
        public static TC10598 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10598() 
            : base("TC10598", "/", null, 0, false, "830e38f1-7934-4b8f-873f-19f457318aa3", ".\\RepositoryImages\\TC10598830e38f1.rximgres")
        {
            _visualanalytics = new TC10598Folders.VisualAnalyticsAppFolder(this);
            _datastudio = new TC10598Folders.DatastudioAppFolder(this);
            _sunawtwindow = new TC10598Folders.SunAwtWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("830e38f1-7934-4b8f-873f-19f457318aa3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The VisualAnalytics folder.
        /// </summary>
        [RepositoryFolder("a1e51d5d-f245-40f0-871d-ac8cce7c4bcb")]
        public virtual TC10598Folders.VisualAnalyticsAppFolder VisualAnalytics
        {
            get { return _visualanalytics; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("16f74faa-49d4-4423-8635-2c28d9e3abc4")]
        public virtual TC10598Folders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("4f4b9be4-4109-47d2-bc08-f72804f963d1")]
        public virtual TC10598Folders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10598Folders
    {
        /// <summary>
        /// The VisualAnalyticsAppFolder folder.
        /// </summary>
        [RepositoryFolder("a1e51d5d-f245-40f0-871d-ac8cce7c4bcb")]
        public partial class VisualAnalyticsAppFolder : RepoGenBaseFolder
        {
            TC10598Folders.ContainerContentPanelFolder _containercontentpanel;
            RepoItemInfo _radarmapInfo;
            RadarMapChartInfoClass _radarmapchartInfo;
            RepoItemInfo _labelInfo;
            RepoItemInfo _optionsInfo;
            AreaFillChartInfoClass _areafillchartInfo;
            RepoItemInfo _colorInfo;
            RepoItemInfo _athleteInfo;
            RepoItemInfo _sumgoldmedalsInfo;
            SplitGraphsInfoClass _splitgraphsInfo;
            RepoItemInfo _axesInfo;
            MergeGraphsInfoClass _mergegraphsInfo;

            /// <summary>
            /// Creates a new VisualAnalytics  folder.
            /// </summary>
            public VisualAnalyticsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VisualAnalytics", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[Sampl']", parentFolder, 30000, null, false, "a1e51d5d-f245-40f0-871d-ac8cce7c4bcb", "")
            {
                _containercontentpanel = new TC10598Folders.ContainerContentPanelFolder(this);
                _radarmapInfo = new RepoItemInfo(this, "RadarMap", ".//container[@type='PaletteState$4']/container[1]/button[18]", 30000, null, "5aa2c645-06b0-4ed1-9107-6151e4f2343f");
                _radarmapchartInfo = new RadarMapChartInfoClass(this);
                _labelInfo = new RepoItemInfo(this, "Label", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 4']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Label']", 30000, null, "06da6952-ce77-4db3-8ea1-da8da3c0d2fd");
                _optionsInfo = new RepoItemInfo(this, "Options", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 4']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Options']", 30000, null, "1e5eb9bb-5902-4565-bf03-0c01d183dd00");
                _areafillchartInfo = new AreaFillChartInfoClass(this);
                _colorInfo = new RepoItemInfo(this, "Color", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 4']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Color']", 30000, null, "7b5a91e2-51e9-4186-84be-90f0f595ee3c");
                _athleteInfo = new RepoItemInfo(this, "Athlete", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Athlete']", 30000, null, "7a2ac600-24fc-4bf1-acd6-93be48663426");
                _sumgoldmedalsInfo = new RepoItemInfo(this, "SUMGoldMedals", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(Gold Medals)']", 30000, null, "02b3a69e-c119-4f44-b931-bdecbbf3a336");
                _splitgraphsInfo = new SplitGraphsInfoClass(this);
                _axesInfo = new RepoItemInfo(this, "Axes", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 4']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Axes']", 30000, null, "5b0374ba-fa7e-4cee-b587-29a524b19ef4");
                _mergegraphsInfo = new MergeGraphsInfoClass(this);
            }

            /// <summary>
            /// The RadarMapChartInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("7a14a899-b937-47c0-b244-3e6aabdf1140")]
            public class RadarMapChartInfoClass : RepoItemInfo
            {
                /// <summary>
                /// RadarMapChartInfoClass class constructor.
                /// </summary>
                public RadarMapChartInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "RadarMapChart", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 4']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container[@name='_canvas']", 30000, null, "7a14a899-b937-47c0-b244-3e6aabdf1140")
                { }

                /// <summary>
                /// Gets the AtheleteChart item image.
                /// </summary>
                /// <returns>The AtheleteChart image.</returns>
                [RepositoryImage("d34ba2eb-56aa-42b8-8631-d7124f73e15e")]
                public CompressedImage GetAtheleteChart()
                {
                    return GetImage("d34ba2eb-56aa-42b8-8631-d7124f73e15e");
                }

                /// <summary>
                /// Gets the AtheleteChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d34ba2eb-56aa-42b8-8631-d7124f73e15e")]
                public CompressedImage GetAtheleteChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d34ba2eb-56aa-42b8-8631-d7124f73e15e", cropRect);
                }
            }

            /// <summary>
            /// The AreaFillChartInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("1e0dfcad-35d6-4996-9fac-330efae9fc62")]
            public class AreaFillChartInfoClass : RepoItemInfo
            {
                /// <summary>
                /// AreaFillChartInfoClass class constructor.
                /// </summary>
                public AreaFillChartInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "AreaFillChart", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 4']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container[@name='_canvas']", 30000, null, "1e0dfcad-35d6-4996-9fac-330efae9fc62")
                { }

                /// <summary>
                /// Gets the AreaChart item image.
                /// </summary>
                /// <returns>The AreaChart image.</returns>
                [RepositoryImage("409fc057-65de-4d48-8665-80dc620b3140")]
                public CompressedImage GetAreaChart()
                {
                    return GetImage("409fc057-65de-4d48-8665-80dc620b3140");
                }

                /// <summary>
                /// Gets the AreaChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("409fc057-65de-4d48-8665-80dc620b3140")]
                public CompressedImage GetAreaChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("409fc057-65de-4d48-8665-80dc620b3140", cropRect);
                }
            }

            /// <summary>
            /// The SplitGraphsInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("989720ff-06ba-4cd0-8a6a-998395326abd")]
            public class SplitGraphsInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SplitGraphsInfoClass class constructor.
                /// </summary>
                public SplitGraphsInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SplitGraphs", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 4']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container/container[26]", 30000, null, "989720ff-06ba-4cd0-8a6a-998395326abd")
                { }

                /// <summary>
                /// Gets the SplitGraph item image.
                /// </summary>
                /// <returns>The SplitGraph image.</returns>
                [RepositoryImage("ebc99c51-c6c8-46db-8f19-9ef73db9f605")]
                public CompressedImage GetSplitGraph()
                {
                    return GetImage("ebc99c51-c6c8-46db-8f19-9ef73db9f605");
                }

                /// <summary>
                /// Gets the SplitGraph item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ebc99c51-c6c8-46db-8f19-9ef73db9f605")]
                public CompressedImage GetSplitGraph(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ebc99c51-c6c8-46db-8f19-9ef73db9f605", cropRect);
                }
            }

            /// <summary>
            /// The MergeGraphsInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3bbc2549-de8a-46f6-9d36-90d99c9905f5")]
            public class MergeGraphsInfoClass : RepoItemInfo
            {
                /// <summary>
                /// MergeGraphsInfoClass class constructor.
                /// </summary>
                public MergeGraphsInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "MergeGraphs", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 4']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container[@name='_canvas']", 30000, null, "3bbc2549-de8a-46f6-9d36-90d99c9905f5")
                { }

                /// <summary>
                /// Gets the MergeGraph item image.
                /// </summary>
                /// <returns>The MergeGraph image.</returns>
                [RepositoryImage("c57ef657-67e5-4c37-9d04-9ab32d5a34e6")]
                public CompressedImage GetMergeGraph()
                {
                    return GetImage("c57ef657-67e5-4c37-9d04-9ab32d5a34e6");
                }

                /// <summary>
                /// Gets the MergeGraph item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c57ef657-67e5-4c37-9d04-9ab32d5a34e6")]
                public CompressedImage GetMergeGraph(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c57ef657-67e5-4c37-9d04-9ab32d5a34e6", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a1e51d5d-f245-40f0-871d-ac8cce7c4bcb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1e51d5d-f245-40f0-871d-ac8cce7c4bcb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RadarMap item.
            /// </summary>
            [RepositoryItem("5aa2c645-06b0-4ed1-9107-6151e4f2343f")]
            public virtual Ranorex.Button RadarMap
            {
                get
                {
                    return _radarmapInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RadarMap item info.
            /// </summary>
            [RepositoryItemInfo("5aa2c645-06b0-4ed1-9107-6151e4f2343f")]
            public virtual RepoItemInfo RadarMapInfo
            {
                get
                {
                    return _radarmapInfo;
                }
            }

            /// <summary>
            /// The RadarMapChart item.
            /// </summary>
            [RepositoryItem("7a14a899-b937-47c0-b244-3e6aabdf1140")]
            public virtual Ranorex.Container RadarMapChart
            {
                get
                {
                    return _radarmapchartInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RadarMapChart item info.
            /// </summary>
            [RepositoryItemInfo("7a14a899-b937-47c0-b244-3e6aabdf1140")]
            public virtual RadarMapChartInfoClass RadarMapChartInfo
            {
                get
                {
                    return _radarmapchartInfo;
                }
            }

            /// <summary>
            /// The Label item.
            /// </summary>
            [RepositoryItem("06da6952-ce77-4db3-8ea1-da8da3c0d2fd")]
            public virtual Ranorex.Text Label
            {
                get
                {
                    return _labelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label item info.
            /// </summary>
            [RepositoryItemInfo("06da6952-ce77-4db3-8ea1-da8da3c0d2fd")]
            public virtual RepoItemInfo LabelInfo
            {
                get
                {
                    return _labelInfo;
                }
            }

            /// <summary>
            /// The Options item.
            /// </summary>
            [RepositoryItem("1e5eb9bb-5902-4565-bf03-0c01d183dd00")]
            public virtual Ranorex.Text Options
            {
                get
                {
                    return _optionsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Options item info.
            /// </summary>
            [RepositoryItemInfo("1e5eb9bb-5902-4565-bf03-0c01d183dd00")]
            public virtual RepoItemInfo OptionsInfo
            {
                get
                {
                    return _optionsInfo;
                }
            }

            /// <summary>
            /// The AreaFillChart item.
            /// </summary>
            [RepositoryItem("1e0dfcad-35d6-4996-9fac-330efae9fc62")]
            public virtual Ranorex.Container AreaFillChart
            {
                get
                {
                    return _areafillchartInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AreaFillChart item info.
            /// </summary>
            [RepositoryItemInfo("1e0dfcad-35d6-4996-9fac-330efae9fc62")]
            public virtual AreaFillChartInfoClass AreaFillChartInfo
            {
                get
                {
                    return _areafillchartInfo;
                }
            }

            /// <summary>
            /// The Color item.
            /// </summary>
            [RepositoryItem("7b5a91e2-51e9-4186-84be-90f0f595ee3c")]
            public virtual Ranorex.Text Color
            {
                get
                {
                    return _colorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Color item info.
            /// </summary>
            [RepositoryItemInfo("7b5a91e2-51e9-4186-84be-90f0f595ee3c")]
            public virtual RepoItemInfo ColorInfo
            {
                get
                {
                    return _colorInfo;
                }
            }

            /// <summary>
            /// The Athlete item.
            /// </summary>
            [RepositoryItem("7a2ac600-24fc-4bf1-acd6-93be48663426")]
            public virtual Ranorex.ListItem Athlete
            {
                get
                {
                    return _athleteInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Athlete item info.
            /// </summary>
            [RepositoryItemInfo("7a2ac600-24fc-4bf1-acd6-93be48663426")]
            public virtual RepoItemInfo AthleteInfo
            {
                get
                {
                    return _athleteInfo;
                }
            }

            /// <summary>
            /// The SUMGoldMedals item.
            /// </summary>
            [RepositoryItem("02b3a69e-c119-4f44-b931-bdecbbf3a336")]
            public virtual Ranorex.ListItem SUMGoldMedals
            {
                get
                {
                    return _sumgoldmedalsInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMGoldMedals item info.
            /// </summary>
            [RepositoryItemInfo("02b3a69e-c119-4f44-b931-bdecbbf3a336")]
            public virtual RepoItemInfo SUMGoldMedalsInfo
            {
                get
                {
                    return _sumgoldmedalsInfo;
                }
            }

            /// <summary>
            /// The SplitGraphs item.
            /// </summary>
            [RepositoryItem("989720ff-06ba-4cd0-8a6a-998395326abd")]
            public virtual Ranorex.Container SplitGraphs
            {
                get
                {
                    return _splitgraphsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SplitGraphs item info.
            /// </summary>
            [RepositoryItemInfo("989720ff-06ba-4cd0-8a6a-998395326abd")]
            public virtual SplitGraphsInfoClass SplitGraphsInfo
            {
                get
                {
                    return _splitgraphsInfo;
                }
            }

            /// <summary>
            /// The Axes item.
            /// </summary>
            [RepositoryItem("5b0374ba-fa7e-4cee-b587-29a524b19ef4")]
            public virtual Ranorex.Text Axes
            {
                get
                {
                    return _axesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Axes item info.
            /// </summary>
            [RepositoryItemInfo("5b0374ba-fa7e-4cee-b587-29a524b19ef4")]
            public virtual RepoItemInfo AxesInfo
            {
                get
                {
                    return _axesInfo;
                }
            }

            /// <summary>
            /// The MergeGraphs item.
            /// </summary>
            [RepositoryItem("3bbc2549-de8a-46f6-9d36-90d99c9905f5")]
            public virtual Ranorex.Container MergeGraphs
            {
                get
                {
                    return _mergegraphsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The MergeGraphs item info.
            /// </summary>
            [RepositoryItemInfo("3bbc2549-de8a-46f6-9d36-90d99c9905f5")]
            public virtual MergeGraphsInfoClass MergeGraphsInfo
            {
                get
                {
                    return _mergegraphsInfo;
                }
            }

            /// <summary>
            /// The ContainerContentPanel folder.
            /// </summary>
            [RepositoryFolder("0e10fbb0-075f-4b17-bc63-91473fa48087")]
            public virtual TC10598Folders.ContainerContentPanelFolder ContainerContentPanel
            {
                get { return _containercontentpanel; }
            }
        }

        /// <summary>
        /// The ContainerContentPanelFolder folder.
        /// </summary>
        [RepositoryFolder("0e10fbb0-075f-4b17-bc63-91473fa48087")]
        public partial class ContainerContentPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _athleteInfo;
            RepoItemInfo _sumtotalmedalsInfo;
            RepoItemInfo _columnpanelInfo;
            RepoItemInfo _rowpanelInfo;

            /// <summary>
            /// Creates a new ContainerContentPanel  folder.
            /// </summary>
            public ContainerContentPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerContentPanel", "container[@name='_mainPanel']/container[@name='_contentPanel']", parentFolder, 30000, null, false, "0e10fbb0-075f-4b17-bc63-91473fa48087", "")
            {
                _athleteInfo = new RepoItemInfo(this, "Athlete", "?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Athlete']", 30000, null, "819828a9-1711-4b03-a268-a0560ad748a0");
                _sumtotalmedalsInfo = new RepoItemInfo(this, "SUMTotalMedals", "?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(Total Medals)']", 30000, null, "3de37f08-cdd0-432b-bf7e-37d10120e12b");
                _columnpanelInfo = new RepoItemInfo(this, "ColumnPanel", "container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 4']/container[@name='_worksheetPanel']//container[@name='cols']//container[@name='panel']", 30000, null, "4a0185f9-51e0-472c-bc65-214437023067");
                _rowpanelInfo = new RepoItemInfo(this, "RowPanel", "container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 4']/container[@name='_worksheetPanel']//container[@name='rows']//container[@name='panel']", 30000, null, "f3b280e2-7f57-4eeb-a6c0-e4b9b08a86e7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0e10fbb0-075f-4b17-bc63-91473fa48087")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0e10fbb0-075f-4b17-bc63-91473fa48087")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Athlete item.
            /// </summary>
            [RepositoryItem("819828a9-1711-4b03-a268-a0560ad748a0")]
            public virtual Ranorex.ListItem Athlete
            {
                get
                {
                    return _athleteInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Athlete item info.
            /// </summary>
            [RepositoryItemInfo("819828a9-1711-4b03-a268-a0560ad748a0")]
            public virtual RepoItemInfo AthleteInfo
            {
                get
                {
                    return _athleteInfo;
                }
            }

            /// <summary>
            /// The SUMTotalMedals item.
            /// </summary>
            [RepositoryItem("3de37f08-cdd0-432b-bf7e-37d10120e12b")]
            public virtual Ranorex.ListItem SUMTotalMedals
            {
                get
                {
                    return _sumtotalmedalsInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMTotalMedals item info.
            /// </summary>
            [RepositoryItemInfo("3de37f08-cdd0-432b-bf7e-37d10120e12b")]
            public virtual RepoItemInfo SUMTotalMedalsInfo
            {
                get
                {
                    return _sumtotalmedalsInfo;
                }
            }

            /// <summary>
            /// The ColumnPanel item.
            /// </summary>
            [RepositoryItem("4a0185f9-51e0-472c-bc65-214437023067")]
            public virtual Ranorex.Container ColumnPanel
            {
                get
                {
                    return _columnpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ColumnPanel item info.
            /// </summary>
            [RepositoryItemInfo("4a0185f9-51e0-472c-bc65-214437023067")]
            public virtual RepoItemInfo ColumnPanelInfo
            {
                get
                {
                    return _columnpanelInfo;
                }
            }

            /// <summary>
            /// The RowPanel item.
            /// </summary>
            [RepositoryItem("f3b280e2-7f57-4eeb-a6c0-e4b9b08a86e7")]
            public virtual Ranorex.Container RowPanel
            {
                get
                {
                    return _rowpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RowPanel item info.
            /// </summary>
            [RepositoryItemInfo("f3b280e2-7f57-4eeb-a6c0-e4b9b08a86e7")]
            public virtual RepoItemInfo RowPanelInfo
            {
                get
                {
                    return _rowpanelInfo;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("16f74faa-49d4-4423-8635-2c28d9e3abc4")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _areaInfo;
            RepoItemInfo _circularInfo;
            RepoItemInfo _showmeasurevaluesInfo;
            RepoItemInfo _mergedmeasureInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@title='' and @processname='datastudio']", parentFolder, 30000, null, false, "16f74faa-49d4-4423-8635-2c28d9e3abc4", "")
            {
                _areaInfo = new RepoItemInfo(this, "Area", "?/?/container[@accessiblename='Display Style']/?/?/radiobutton[@text='Area']", 30000, null, "fbfcbca8-cd72-41f6-b332-ae2247bc46df");
                _circularInfo = new RepoItemInfo(this, "Circular", "?/?/container[@accessiblename='Grid Style Selection']/?/?/radiobutton[@text='Circular']", 30000, null, "59c020ac-e030-4107-a172-40675805227e");
                _showmeasurevaluesInfo = new RepoItemInfo(this, "ShowMeasureValues", "?/?/container[@accessiblename='Data Labels']/?/?/checkbox[@text='Show Measure Values']", 30000, null, "8d7b04b6-26a5-4665-9517-c37022ef76c1");
                _mergedmeasureInfo = new RepoItemInfo(this, "MergedMeasure", ".//container[@accessiblename='Axis Type']/?/?/checkbox[@text='Merged measure']", 30000, null, "b5b190d4-7f2b-4375-8647-d35c13e35152");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("16f74faa-49d4-4423-8635-2c28d9e3abc4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("16f74faa-49d4-4423-8635-2c28d9e3abc4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Area item.
            /// </summary>
            [RepositoryItem("fbfcbca8-cd72-41f6-b332-ae2247bc46df")]
            public virtual Ranorex.RadioButton Area
            {
                get
                {
                    return _areaInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Area item info.
            /// </summary>
            [RepositoryItemInfo("fbfcbca8-cd72-41f6-b332-ae2247bc46df")]
            public virtual RepoItemInfo AreaInfo
            {
                get
                {
                    return _areaInfo;
                }
            }

            /// <summary>
            /// The Circular item.
            /// </summary>
            [RepositoryItem("59c020ac-e030-4107-a172-40675805227e")]
            public virtual Ranorex.RadioButton Circular
            {
                get
                {
                    return _circularInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Circular item info.
            /// </summary>
            [RepositoryItemInfo("59c020ac-e030-4107-a172-40675805227e")]
            public virtual RepoItemInfo CircularInfo
            {
                get
                {
                    return _circularInfo;
                }
            }

            /// <summary>
            /// The ShowMeasureValues item.
            /// </summary>
            [RepositoryItem("8d7b04b6-26a5-4665-9517-c37022ef76c1")]
            public virtual Ranorex.CheckBox ShowMeasureValues
            {
                get
                {
                    return _showmeasurevaluesInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ShowMeasureValues item info.
            /// </summary>
            [RepositoryItemInfo("8d7b04b6-26a5-4665-9517-c37022ef76c1")]
            public virtual RepoItemInfo ShowMeasureValuesInfo
            {
                get
                {
                    return _showmeasurevaluesInfo;
                }
            }

            /// <summary>
            /// The MergedMeasure item.
            /// </summary>
            [RepositoryItem("b5b190d4-7f2b-4375-8647-d35c13e35152")]
            public virtual Ranorex.CheckBox MergedMeasure
            {
                get
                {
                    return _mergedmeasureInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The MergedMeasure item info.
            /// </summary>
            [RepositoryItemInfo("b5b190d4-7f2b-4375-8647-d35c13e35152")]
            public virtual RepoItemInfo MergedMeasureInfo
            {
                get
                {
                    return _mergedmeasureInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("4f4b9be4-4109-47d2-bc08-f72804f963d1")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _removeInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "4f4b9be4-4109-47d2-bc08-f72804f963d1", "")
            {
                _removeInfo = new RepoItemInfo(this, "Remove", ".//menuitem[@text='Remove']", 30000, null, "0ae15a1e-eee9-4f7b-861b-ff2c1eaedd74");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f4b9be4-4109-47d2-bc08-f72804f963d1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f4b9be4-4109-47d2-bc08-f72804f963d1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Remove item.
            /// </summary>
            [RepositoryItem("0ae15a1e-eee9-4f7b-861b-ff2c1eaedd74")]
            public virtual Ranorex.MenuItem Remove
            {
                get
                {
                    return _removeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Remove item info.
            /// </summary>
            [RepositoryItemInfo("0ae15a1e-eee9-4f7b-861b-ff2c1eaedd74")]
            public virtual RepoItemInfo RemoveInfo
            {
                get
                {
                    return _removeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}