///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10557
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10557Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("8c6fc3c0-3456-4a66-b934-69eddc89683a")]
    public partial class TC10557Repo : RepoGenBaseFolder
    {
        static TC10557Repo instance = new TC10557Repo();
        TC10557RepoFolders.ApplicationAppFolder _application;
        TC10557RepoFolders.DataStudioAppFolder _datastudio;
        TC10557RepoFolders.OpenWindowAppFolder _openwindow;
        TC10557RepoFolders.ChartPropertiesWindowAppFolder _chartpropertieswindow;
        TC10557RepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        TC10557RepoFolders.VAWindowAppFolder _vawindow;
        TC10557RepoFolders.VisualAnalyticsVATestsVizxAsteriAppFolder _visualanalyticsvatestsvizxasteri;
        TC10557RepoFolders.DisplayWindowAppFolder _displaywindow;
        TC10557RepoFolders.SaveChangesAppFolder _savechanges;

        /// <summary>
        /// Gets the singleton class instance representing the TC10557Repo element repository.
        /// </summary>
        [RepositoryFolder("8c6fc3c0-3456-4a66-b934-69eddc89683a")]
        public static TC10557Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10557Repo() 
            : base("TC10557Repo", "/", null, 0, false, "8c6fc3c0-3456-4a66-b934-69eddc89683a", ".\\RepositoryImages\\TC10557Repo8c6fc3c0.rximgres")
        {
            _application = new TC10557RepoFolders.ApplicationAppFolder(this);
            _datastudio = new TC10557RepoFolders.DataStudioAppFolder(this);
            _openwindow = new TC10557RepoFolders.OpenWindowAppFolder(this);
            _chartpropertieswindow = new TC10557RepoFolders.ChartPropertiesWindowAppFolder(this);
            _sunawtwindow = new TC10557RepoFolders.SunAwtWindowAppFolder(this);
            _vawindow = new TC10557RepoFolders.VAWindowAppFolder(this);
            _visualanalyticsvatestsvizxasteri = new TC10557RepoFolders.VisualAnalyticsVATestsVizxAsteriAppFolder(this);
            _displaywindow = new TC10557RepoFolders.DisplayWindowAppFolder(this);
            _savechanges = new TC10557RepoFolders.SaveChangesAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8c6fc3c0-3456-4a66-b934-69eddc89683a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public virtual TC10557RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The DataStudio folder.
        /// </summary>
        [RepositoryFolder("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
        public virtual TC10557RepoFolders.DataStudioAppFolder DataStudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The OpenWindow folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public virtual TC10557RepoFolders.OpenWindowAppFolder OpenWindow
        {
            get { return _openwindow; }
        }

        /// <summary>
        /// The ChartPropertiesWindow folder.
        /// </summary>
        [RepositoryFolder("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
        public virtual TC10557RepoFolders.ChartPropertiesWindowAppFolder ChartPropertiesWindow
        {
            get { return _chartpropertieswindow; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
        public virtual TC10557RepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The VAWindow folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public virtual TC10557RepoFolders.VAWindowAppFolder VAWindow
        {
            get { return _vawindow; }
        }

        /// <summary>
        /// The VisualAnalyticsVATestsVizxAsteri folder.
        /// </summary>
        [RepositoryFolder("4dd0e420-bbed-4779-9a51-55df336bc07f")]
        public virtual TC10557RepoFolders.VisualAnalyticsVATestsVizxAsteriAppFolder VisualAnalyticsVATestsVizxAsteri
        {
            get { return _visualanalyticsvatestsvizxasteri; }
        }

        /// <summary>
        /// The DisplayWindow folder.
        /// </summary>
        [RepositoryFolder("86c48c36-7d84-41a5-9bfd-48688233bff3")]
        public virtual TC10557RepoFolders.DisplayWindowAppFolder DisplayWindow
        {
            get { return _displaywindow; }
        }

        /// <summary>
        /// The SaveChanges folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public virtual TC10557RepoFolders.SaveChangesAppFolder SaveChanges
        {
            get { return _savechanges; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10557RepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filemenuInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "d54a3fac-3b92-4b4a-9c2b-770fb3053792", "")
            {
                _filemenuInfo = new RepoItemInfo(this, "FileMenu", ".//menuitem[@text='File']", 30000, null, "da992c0f-dfcc-4c8a-a60b-60218253b432");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileMenu item.
            /// </summary>
            [RepositoryItem("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual Ranorex.MenuItem FileMenu
            {
                get
                {
                    return _filemenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FileMenu item info.
            /// </summary>
            [RepositoryItemInfo("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual RepoItemInfo FileMenuInfo
            {
                get
                {
                    return _filemenuInfo;
                }
            }
        }

        /// <summary>
        /// The DataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
        public partial class DataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openfileInfo;

            /// <summary>
            /// Creates a new DataStudio  folder.
            /// </summary>
            public DataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataStudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "bd2e48e4-5445-4ec3-a9b7-23d20f08afdb", "")
            {
                _openfileInfo = new RepoItemInfo(this, "OpenFile", ".//menuitem[@text='Open']", 30000, null, "4f2dba1a-2292-46cf-a03d-955d59d8f39c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenFile item.
            /// </summary>
            [RepositoryItem("4f2dba1a-2292-46cf-a03d-955d59d8f39c")]
            public virtual Ranorex.MenuItem OpenFile
            {
                get
                {
                    return _openfileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The OpenFile item info.
            /// </summary>
            [RepositoryItemInfo("4f2dba1a-2292-46cf-a03d-955d59d8f39c")]
            public virtual RepoItemInfo OpenFileInfo
            {
                get
                {
                    return _openfileInfo;
                }
            }
        }

        /// <summary>
        /// The OpenWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public partial class OpenWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filepathtextboxInfo;
            RepoItemInfo _openbuttonInfo;

            /// <summary>
            /// Creates a new OpenWindow  folder.
            /// </summary>
            public OpenWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenWindow", "/form[@title='Open']", parentFolder, 30000, null, true, "951fcb26-33b8-49e9-9d15-b9683c621e3f", "")
            {
                _filepathtextboxInfo = new RepoItemInfo(this, "FilePathTextbox", ".//element/container[@type='JPanel']/container[3]/container[2]/text[@accessiblename='File name:']", 30000, null, "5d62603f-d3ac-4200-9d2a-4347326a6699");
                _openbuttonInfo = new RepoItemInfo(this, "OpenButton", ".//element/container[@type='JPanel']/container[3]/container[3]/button[@text='Open']", 30000, null, "89dcbd3d-2d03-4a6b-ad50-32f672ff7e54");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilePathTextbox item.
            /// </summary>
            [RepositoryItem("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual Ranorex.Text FilePathTextbox
            {
                get
                {
                    return _filepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilePathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual RepoItemInfo FilePathTextboxInfo
            {
                get
                {
                    return _filepathtextboxInfo;
                }
            }

            /// <summary>
            /// The OpenButton item.
            /// </summary>
            [RepositoryItem("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual Ranorex.Button OpenButton
            {
                get
                {
                    return _openbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenButton item info.
            /// </summary>
            [RepositoryItemInfo("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual RepoItemInfo OpenButtonInfo
            {
                get
                {
                    return _openbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ChartPropertiesWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
        public partial class ChartPropertiesWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _automaticInfo;
            RepoItemInfo _selectpointInfo;
            RepoItemInfo _settingtabInfo;

            /// <summary>
            /// Creates a new ChartPropertiesWindow  folder.
            /// </summary>
            public ChartPropertiesWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ChartPropertiesWindow", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[VA-te']", parentFolder, 30000, null, true, "7c7be239-e782-4085-b7f6-08e0c4bd0bc5", "")
            {
                _automaticInfo = new RepoItemInfo(this, "Automatic", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']", 30000, null, "bd98091f-27c9-409b-80fb-c1053d253c93");
                _selectpointInfo = new RepoItemInfo(this, "SelectPoint", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']/button[@text='']", 30000, null, "0920f1be-53cf-4c78-a2d8-266f9c5f1f73");
                _settingtabInfo = new RepoItemInfo(this, "SettingTab", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Options']", 30000, null, "080e7107-f5e2-4910-876b-08e613c409b1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Automatic item.
            /// </summary>
            [RepositoryItem("bd98091f-27c9-409b-80fb-c1053d253c93")]
            public virtual Ranorex.ComboBox Automatic
            {
                get
                {
                    return _automaticInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Automatic item info.
            /// </summary>
            [RepositoryItemInfo("bd98091f-27c9-409b-80fb-c1053d253c93")]
            public virtual RepoItemInfo AutomaticInfo
            {
                get
                {
                    return _automaticInfo;
                }
            }

            /// <summary>
            /// The SelectPoint item.
            /// </summary>
            [RepositoryItem("0920f1be-53cf-4c78-a2d8-266f9c5f1f73")]
            public virtual Ranorex.Button SelectPoint
            {
                get
                {
                    return _selectpointInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SelectPoint item info.
            /// </summary>
            [RepositoryItemInfo("0920f1be-53cf-4c78-a2d8-266f9c5f1f73")]
            public virtual RepoItemInfo SelectPointInfo
            {
                get
                {
                    return _selectpointInfo;
                }
            }

            /// <summary>
            /// The SettingTab item.
            /// </summary>
            [RepositoryItem("080e7107-f5e2-4910-876b-08e613c409b1")]
            public virtual Ranorex.Text SettingTab
            {
                get
                {
                    return _settingtabInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SettingTab item info.
            /// </summary>
            [RepositoryItemInfo("080e7107-f5e2-4910-876b-08e613c409b1")]
            public virtual RepoItemInfo SettingTabInfo
            {
                get
                {
                    return _settingtabInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contextmenuInfo;
            RepoItemInfo _tableInfo;
            RepoItemInfo _highlighttableInfo;
            RepoItemInfo _highlightbuttonInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "84776f98-4aaa-4246-9a0b-9355abb3cff6", "")
            {
                _contextmenuInfo = new RepoItemInfo(this, "ContextMenu", ".//contextmenu", 30000, null, "a21e0391-83f9-4568-8f40-951dfd79f0c6");
                _tableInfo = new RepoItemInfo(this, "Table", ".//container/list[@name='ComboBox.list']/listitem[@text='Table']", 30000, null, "aaa6d739-c14a-4868-849b-fd2223826546");
                _highlighttableInfo = new RepoItemInfo(this, "HighlightTable", ".//container[@type='PropertiesPopup']", 30000, null, "c4250010-645e-429e-bc6d-400051412e07");
                _highlightbuttonInfo = new RepoItemInfo(this, "HighlightButton", ".//container[@accessiblename='Display Style']/?/?/radiobutton[@text='Highlight Table']", 30000, null, "314b1892-ea41-423e-bbc9-a5f5a90aaee9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContextMenu item.
            /// </summary>
            [RepositoryItem("a21e0391-83f9-4568-8f40-951dfd79f0c6")]
            public virtual Ranorex.ContextMenu ContextMenu
            {
                get
                {
                    return _contextmenuInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The ContextMenu item info.
            /// </summary>
            [RepositoryItemInfo("a21e0391-83f9-4568-8f40-951dfd79f0c6")]
            public virtual RepoItemInfo ContextMenuInfo
            {
                get
                {
                    return _contextmenuInfo;
                }
            }

            /// <summary>
            /// The Table item.
            /// </summary>
            [RepositoryItem("aaa6d739-c14a-4868-849b-fd2223826546")]
            public virtual Ranorex.ListItem Table
            {
                get
                {
                    return _tableInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Table item info.
            /// </summary>
            [RepositoryItemInfo("aaa6d739-c14a-4868-849b-fd2223826546")]
            public virtual RepoItemInfo TableInfo
            {
                get
                {
                    return _tableInfo;
                }
            }

            /// <summary>
            /// The HighlightTable item.
            /// </summary>
            [RepositoryItem("c4250010-645e-429e-bc6d-400051412e07")]
            public virtual Ranorex.Container HighlightTable
            {
                get
                {
                    return _highlighttableInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The HighlightTable item info.
            /// </summary>
            [RepositoryItemInfo("c4250010-645e-429e-bc6d-400051412e07")]
            public virtual RepoItemInfo HighlightTableInfo
            {
                get
                {
                    return _highlighttableInfo;
                }
            }

            /// <summary>
            /// The HighlightButton item.
            /// </summary>
            [RepositoryItem("314b1892-ea41-423e-bbc9-a5f5a90aaee9")]
            public virtual Ranorex.RadioButton HighlightButton
            {
                get
                {
                    return _highlightbuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The HighlightButton item info.
            /// </summary>
            [RepositoryItemInfo("314b1892-ea41-423e-bbc9-a5f5a90aaee9")]
            public virtual RepoItemInfo HighlightButtonInfo
            {
                get
                {
                    return _highlightbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The VAWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public partial class VAWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _columncontainerInfo;
            RepoItemInfo _rowcontainerInfo;
            RepoItemInfo _chartcontainerInfo;
            RepoItemInfo _cardtypeInfo;
            RepoItemInfo _freightInfo;
            RepoItemInfo _closewindowInfo;

            /// <summary>
            /// Creates a new VAWindow  folder.
            /// </summary>
            public VAWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VAWindow", "/form[@title~'^Visual\\ Analytics']", parentFolder, 30000, null, true, "28ef3ff7-5142-4c80-9fe2-5119aa3572c6", "")
            {
                _columncontainerInfo = new RepoItemInfo(this, "ColumnContainer", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='cols']//container[@name='panel']", 30000, null, "30b5c102-e23f-4876-b1fe-d43126f5aba7");
                _rowcontainerInfo = new RepoItemInfo(this, "RowContainer", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='rows']//container[@name='panel']", 30000, null, "6dbc236e-a75e-4d7b-a7f3-564ef84439f5");
                _chartcontainerInfo = new RepoItemInfo(this, "ChartContainer", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container[@name='_canvas']", 30000, null, "e8ee7e32-59e4-4ad5-b3ba-f4b1318a5579");
                _cardtypeInfo = new RepoItemInfo(this, "CardType", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Card Type']", 30000, null, "ffbb3bf3-09c3-47de-ba5e-e57a1bc2d76c");
                _freightInfo = new RepoItemInfo(this, "Freight", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(Freight)']", 30000, null, "9ca1252f-68d1-464f-aa26-a406ad6fdb91");
                _closewindowInfo = new RepoItemInfo(this, "CloseWindow", ".//button[@accessiblename='Close']", 30000, null, "eb7f4e53-1ab2-4471-9058-e4ab8e63fccd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ColumnContainer item.
            /// </summary>
            [RepositoryItem("30b5c102-e23f-4876-b1fe-d43126f5aba7")]
            public virtual Ranorex.Container ColumnContainer
            {
                get
                {
                    return _columncontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ColumnContainer item info.
            /// </summary>
            [RepositoryItemInfo("30b5c102-e23f-4876-b1fe-d43126f5aba7")]
            public virtual RepoItemInfo ColumnContainerInfo
            {
                get
                {
                    return _columncontainerInfo;
                }
            }

            /// <summary>
            /// The RowContainer item.
            /// </summary>
            [RepositoryItem("6dbc236e-a75e-4d7b-a7f3-564ef84439f5")]
            public virtual Ranorex.Container RowContainer
            {
                get
                {
                    return _rowcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RowContainer item info.
            /// </summary>
            [RepositoryItemInfo("6dbc236e-a75e-4d7b-a7f3-564ef84439f5")]
            public virtual RepoItemInfo RowContainerInfo
            {
                get
                {
                    return _rowcontainerInfo;
                }
            }

            /// <summary>
            /// The ChartContainer item.
            /// </summary>
            [RepositoryItem("e8ee7e32-59e4-4ad5-b3ba-f4b1318a5579")]
            public virtual Ranorex.Container ChartContainer
            {
                get
                {
                    return _chartcontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ChartContainer item info.
            /// </summary>
            [RepositoryItemInfo("e8ee7e32-59e4-4ad5-b3ba-f4b1318a5579")]
            public virtual RepoItemInfo ChartContainerInfo
            {
                get
                {
                    return _chartcontainerInfo;
                }
            }

            /// <summary>
            /// The CardType item.
            /// </summary>
            [RepositoryItem("ffbb3bf3-09c3-47de-ba5e-e57a1bc2d76c")]
            public virtual Ranorex.ListItem CardType
            {
                get
                {
                    return _cardtypeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CardType item info.
            /// </summary>
            [RepositoryItemInfo("ffbb3bf3-09c3-47de-ba5e-e57a1bc2d76c")]
            public virtual RepoItemInfo CardTypeInfo
            {
                get
                {
                    return _cardtypeInfo;
                }
            }

            /// <summary>
            /// The Freight item.
            /// </summary>
            [RepositoryItem("9ca1252f-68d1-464f-aa26-a406ad6fdb91")]
            public virtual Ranorex.ListItem Freight
            {
                get
                {
                    return _freightInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Freight item info.
            /// </summary>
            [RepositoryItemInfo("9ca1252f-68d1-464f-aa26-a406ad6fdb91")]
            public virtual RepoItemInfo FreightInfo
            {
                get
                {
                    return _freightInfo;
                }
            }

            /// <summary>
            /// The CloseWindow item.
            /// </summary>
            [RepositoryItem("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual Ranorex.Button CloseWindow
            {
                get
                {
                    return _closewindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseWindow item info.
            /// </summary>
            [RepositoryItemInfo("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual RepoItemInfo CloseWindowInfo
            {
                get
                {
                    return _closewindowInfo;
                }
            }
        }

        /// <summary>
        /// The VisualAnalyticsVATestsVizxAsteriAppFolder folder.
        /// </summary>
        [RepositoryFolder("4dd0e420-bbed-4779-9a51-55df336bc07f")]
        public partial class VisualAnalyticsVATestsVizxAsteriAppFolder : RepoGenBaseFolder
        {
            TC10557RepoFolders.ContainerContentPanelFolder _containercontentpanel;
            RepoItemInfo _colorInfo;
            PivotTableOverlayPanelInfoClass _pivottableoverlaypanelInfo;
            StartWindowInfoClass _startwindowInfo;

            /// <summary>
            /// Creates a new VisualAnalyticsVATestsVizxAsteri  folder.
            /// </summary>
            public VisualAnalyticsVATestsVizxAsteriAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VisualAnalyticsVATestsVizxAsteri", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[VA-te']", parentFolder, 30000, null, false, "4dd0e420-bbed-4779-9a51-55df336bc07f", "")
            {
                _containercontentpanel = new TC10557RepoFolders.ContainerContentPanelFolder(this);
                _colorInfo = new RepoItemInfo(this, "Color", "container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Color']", 30000, null, "252824ae-f361-486c-8580-81ecfddc87f7");
                _pivottableoverlaypanelInfo = new PivotTableOverlayPanelInfoClass(this);
                _startwindowInfo = new StartWindowInfoClass(this);
            }

            /// <summary>
            /// The PivotTableOverlayPanelInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("482a10fc-9418-471e-8902-4175d0491853")]
            public class PivotTableOverlayPanelInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PivotTableOverlayPanelInfoClass class constructor.
                /// </summary>
                public PivotTableOverlayPanelInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PivotTableOverlayPanel", "container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_gridPanel']/?/?/container[@type='PivotTableOverlayPanel']", 30000, null, "482a10fc-9418-471e-8902-4175d0491853")
                { }

                /// <summary>
                /// Gets the CardtypeColorChart item image.
                /// </summary>
                /// <returns>The CardtypeColorChart image.</returns>
                [RepositoryImage("73db7b88-6e9a-4460-80f9-510efce73703")]
                public CompressedImage GetCardtypeColorChart()
                {
                    return GetImage("73db7b88-6e9a-4460-80f9-510efce73703");
                }

                /// <summary>
                /// Gets the CardtypeColorChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("73db7b88-6e9a-4460-80f9-510efce73703")]
                public CompressedImage GetCardtypeColorChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("73db7b88-6e9a-4460-80f9-510efce73703", cropRect);
                }

                /// <summary>
                /// Gets the HighlightTable item image.
                /// </summary>
                /// <returns>The HighlightTable image.</returns>
                [RepositoryImage("440f8202-e2df-4fec-935d-9ad899e13345")]
                public CompressedImage GetHighlightTable()
                {
                    return GetImage("440f8202-e2df-4fec-935d-9ad899e13345");
                }

                /// <summary>
                /// Gets the HighlightTable item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("440f8202-e2df-4fec-935d-9ad899e13345")]
                public CompressedImage GetHighlightTable(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("440f8202-e2df-4fec-935d-9ad899e13345", cropRect);
                }

                /// <summary>
                /// Gets the ResultChart item image.
                /// </summary>
                /// <returns>The ResultChart image.</returns>
                [RepositoryImage("e4fe9227-35ee-4294-b74b-bba569fa3098")]
                public CompressedImage GetResultChart()
                {
                    return GetImage("e4fe9227-35ee-4294-b74b-bba569fa3098");
                }

                /// <summary>
                /// Gets the ResultChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e4fe9227-35ee-4294-b74b-bba569fa3098")]
                public CompressedImage GetResultChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e4fe9227-35ee-4294-b74b-bba569fa3098", cropRect);
                }

                /// <summary>
                /// Gets the SubTotalColorChart item image.
                /// </summary>
                /// <returns>The SubTotalColorChart image.</returns>
                [RepositoryImage("0f69bd07-b9e8-462f-abf9-4830999f30ab")]
                public CompressedImage GetSubTotalColorChart()
                {
                    return GetImage("0f69bd07-b9e8-462f-abf9-4830999f30ab");
                }

                /// <summary>
                /// Gets the SubTotalColorChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("0f69bd07-b9e8-462f-abf9-4830999f30ab")]
                public CompressedImage GetSubTotalColorChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("0f69bd07-b9e8-462f-abf9-4830999f30ab", cropRect);
                }

                /// <summary>
                /// Gets the TableChart1 item image.
                /// </summary>
                /// <returns>The TableChart1 image.</returns>
                [RepositoryImage("4e7bb564-bcc3-4510-a629-ba39cf604b3e")]
                public CompressedImage GetTableChart1()
                {
                    return GetImage("4e7bb564-bcc3-4510-a629-ba39cf604b3e");
                }

                /// <summary>
                /// Gets the TableChart1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("4e7bb564-bcc3-4510-a629-ba39cf604b3e")]
                public CompressedImage GetTableChart1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("4e7bb564-bcc3-4510-a629-ba39cf604b3e", cropRect);
                }
            }

            /// <summary>
            /// The StartWindowInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9f200710-0a18-4c35-806d-41bf4c188604")]
            public class StartWindowInfoClass : RepoItemInfo
            {
                /// <summary>
                /// StartWindowInfoClass class constructor.
                /// </summary>
                public StartWindowInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "StartWindow", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container", 30000, null, "9f200710-0a18-4c35-806d-41bf4c188604")
                { }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <returns>The VizxDataWindow image.</returns>
                [RepositoryImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e")]
                public CompressedImage GetVizxDataWindow()
                {
                    return GetImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e");
                }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e")]
                public CompressedImage GetVizxDataWindow(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4dd0e420-bbed-4779-9a51-55df336bc07f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4dd0e420-bbed-4779-9a51-55df336bc07f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Color item.
            /// </summary>
            [RepositoryItem("252824ae-f361-486c-8580-81ecfddc87f7")]
            public virtual Ranorex.Text Color
            {
                get
                {
                    return _colorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Color item info.
            /// </summary>
            [RepositoryItemInfo("252824ae-f361-486c-8580-81ecfddc87f7")]
            public virtual RepoItemInfo ColorInfo
            {
                get
                {
                    return _colorInfo;
                }
            }

            /// <summary>
            /// The PivotTableOverlayPanel item.
            /// </summary>
            [RepositoryItem("482a10fc-9418-471e-8902-4175d0491853")]
            public virtual Ranorex.Container PivotTableOverlayPanel
            {
                get
                {
                    return _pivottableoverlaypanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PivotTableOverlayPanel item info.
            /// </summary>
            [RepositoryItemInfo("482a10fc-9418-471e-8902-4175d0491853")]
            public virtual PivotTableOverlayPanelInfoClass PivotTableOverlayPanelInfo
            {
                get
                {
                    return _pivottableoverlaypanelInfo;
                }
            }

            /// <summary>
            /// The StartWindow item.
            /// </summary>
            [RepositoryItem("9f200710-0a18-4c35-806d-41bf4c188604")]
            public virtual Ranorex.Container StartWindow
            {
                get
                {
                    return _startwindowInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The StartWindow item info.
            /// </summary>
            [RepositoryItemInfo("9f200710-0a18-4c35-806d-41bf4c188604")]
            public virtual StartWindowInfoClass StartWindowInfo
            {
                get
                {
                    return _startwindowInfo;
                }
            }

            /// <summary>
            /// The ContainerContentPanel folder.
            /// </summary>
            [RepositoryFolder("2a4f2155-7159-47b8-acb9-ca934f07c38d")]
            public virtual TC10557RepoFolders.ContainerContentPanelFolder ContainerContentPanel
            {
                get { return _containercontentpanel; }
            }
        }

        /// <summary>
        /// The ContainerContentPanelFolder folder.
        /// </summary>
        [RepositoryFolder("2a4f2155-7159-47b8-acb9-ca934f07c38d")]
        public partial class ContainerContentPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cardtypeInfo;
            RepoItemInfo _sumsubtotalInfo;
            RepoItemInfo _rowsInfo;
            RepoItemInfo _multisplitworksheetdollarmultiglasspaneInfo;

            /// <summary>
            /// Creates a new ContainerContentPanel  folder.
            /// </summary>
            public ContainerContentPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerContentPanel", "container[@name='_mainPanel']/container[@name='_contentPanel']", parentFolder, 30000, null, false, "2a4f2155-7159-47b8-acb9-ca934f07c38d", "")
            {
                _cardtypeInfo = new RepoItemInfo(this, "CardType", "?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Card Type']", 30000, null, "a6405d51-4e21-4fc0-835a-8a90b340c975");
                _sumsubtotalInfo = new RepoItemInfo(this, "SUMSubTotal", "?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(Sub Total)']", 30000, null, "bc5cd462-b80d-4016-a99c-8a692bb63ec7");
                _rowsInfo = new RepoItemInfo(this, "Rows", "?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='rows']/?/?/text[@caption='Rows']", 30000, null, "b86802ba-6d98-427b-8c47-187688baa832");
                _multisplitworksheetdollarmultiglasspaneInfo = new RepoItemInfo(this, "MultiSplitWorksheetDollarMultiGlassPane", "?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']//element[@type='MultiSplitWorksheet$MultiGlassPane']", 30000, null, "ddf2ed10-41b2-4a92-9049-0ddd67a44390");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a4f2155-7159-47b8-acb9-ca934f07c38d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a4f2155-7159-47b8-acb9-ca934f07c38d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CardType item.
            /// </summary>
            [RepositoryItem("a6405d51-4e21-4fc0-835a-8a90b340c975")]
            public virtual Ranorex.ListItem CardType
            {
                get
                {
                    return _cardtypeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CardType item info.
            /// </summary>
            [RepositoryItemInfo("a6405d51-4e21-4fc0-835a-8a90b340c975")]
            public virtual RepoItemInfo CardTypeInfo
            {
                get
                {
                    return _cardtypeInfo;
                }
            }

            /// <summary>
            /// The SUMSubTotal item.
            /// </summary>
            [RepositoryItem("bc5cd462-b80d-4016-a99c-8a692bb63ec7")]
            public virtual Ranorex.ListItem SUMSubTotal
            {
                get
                {
                    return _sumsubtotalInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMSubTotal item info.
            /// </summary>
            [RepositoryItemInfo("bc5cd462-b80d-4016-a99c-8a692bb63ec7")]
            public virtual RepoItemInfo SUMSubTotalInfo
            {
                get
                {
                    return _sumsubtotalInfo;
                }
            }

            /// <summary>
            /// The Rows item.
            /// </summary>
            [RepositoryItem("b86802ba-6d98-427b-8c47-187688baa832")]
            public virtual Ranorex.Text Rows
            {
                get
                {
                    return _rowsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Rows item info.
            /// </summary>
            [RepositoryItemInfo("b86802ba-6d98-427b-8c47-187688baa832")]
            public virtual RepoItemInfo RowsInfo
            {
                get
                {
                    return _rowsInfo;
                }
            }

            /// <summary>
            /// The MultiSplitWorksheetDollarMultiGlassPane item.
            /// </summary>
            [RepositoryItem("ddf2ed10-41b2-4a92-9049-0ddd67a44390")]
            public virtual Ranorex.Unknown MultiSplitWorksheetDollarMultiGlassPane
            {
                get
                {
                    return _multisplitworksheetdollarmultiglasspaneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MultiSplitWorksheetDollarMultiGlassPane item info.
            /// </summary>
            [RepositoryItemInfo("ddf2ed10-41b2-4a92-9049-0ddd67a44390")]
            public virtual RepoItemInfo MultiSplitWorksheetDollarMultiGlassPaneInfo
            {
                get
                {
                    return _multisplitworksheetdollarmultiglasspaneInfo;
                }
            }
        }

        /// <summary>
        /// The DisplayWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("86c48c36-7d84-41a5-9bfd-48688233bff3")]
        public partial class DisplayWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _highlightbuttonInfo;

            /// <summary>
            /// Creates a new DisplayWindow  folder.
            /// </summary>
            public DisplayWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DisplayWindow", "/form", parentFolder, 30000, null, true, "86c48c36-7d84-41a5-9bfd-48688233bff3", "")
            {
                _highlightbuttonInfo = new RepoItemInfo(this, "HighlightButton", ".//container[@accessiblename='Display Style']/?/?/radiobutton[@text='Highlight Table']", 30000, null, "a5ed57ea-2eeb-48c4-a37c-7e48e8ec0fbc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86c48c36-7d84-41a5-9bfd-48688233bff3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86c48c36-7d84-41a5-9bfd-48688233bff3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HighlightButton item.
            /// </summary>
            [RepositoryItem("a5ed57ea-2eeb-48c4-a37c-7e48e8ec0fbc")]
            public virtual Ranorex.RadioButton HighlightButton
            {
                get
                {
                    return _highlightbuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The HighlightButton item info.
            /// </summary>
            [RepositoryItemInfo("a5ed57ea-2eeb-48c4-a37c-7e48e8ec0fbc")]
            public virtual RepoItemInfo HighlightButtonInfo
            {
                get
                {
                    return _highlightbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SaveChangesAppFolder folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public partial class SaveChangesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardbuttonInfo;

            /// <summary>
            /// Creates a new SaveChanges  folder.
            /// </summary>
            public SaveChangesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveChanges", "/form[@title='Save Changes']", parentFolder, 30000, null, true, "e023f516-9d72-4d93-987f-b52734da129a", "")
            {
                _discardbuttonInfo = new RepoItemInfo(this, "DiscardButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "2f6a6708-f14b-4f61-b831-60b96d7c607d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DiscardButton item.
            /// </summary>
            [RepositoryItem("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual Ranorex.Button DiscardButton
            {
                get
                {
                    return _discardbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DiscardButton item info.
            /// </summary>
            [RepositoryItemInfo("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual RepoItemInfo DiscardButtonInfo
            {
                get
                {
                    return _discardbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}