///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10566
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10566 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("b19716f3-5b11-45ed-b705-9fcb48a570dc")]
    public partial class TC10566 : RepoGenBaseFolder
    {
        static TC10566 instance = new TC10566();
        TC10566Folders.ApplicationAppFolder _application;

        /// <summary>
        /// Gets the singleton class instance representing the TC10566 element repository.
        /// </summary>
        [RepositoryFolder("b19716f3-5b11-45ed-b705-9fcb48a570dc")]
        public static TC10566 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10566() 
            : base("TC10566", "/", null, 0, false, "b19716f3-5b11-45ed-b705-9fcb48a570dc", ".\\RepositoryImages\\TC10566b19716f3.rximgres")
        {
            _application = new TC10566Folders.ApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b19716f3-5b11-45ed-b705-9fcb48a570dc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("5538c1fe-823f-4b9d-bdae-efb5851b299d")]
        public virtual TC10566Folders.ApplicationAppFolder Application
        {
            get { return _application; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10566Folders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("5538c1fe-823f-4b9d-bdae-efb5851b299d")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _executeexplainInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua\\ Data\\ Studio\\ ']", parentFolder, 30000, null, true, "5538c1fe-823f-4b9d-bdae-efb5851b299d", "")
            {
                _executeexplainInfo = new RepoItemInfo(this, "ExecuteExplain", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='toolBar']/button[@name='executeExplainButton']", 30000, null, "8c51c656-8da9-4c6e-a6db-04e04a99d42a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5538c1fe-823f-4b9d-bdae-efb5851b299d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5538c1fe-823f-4b9d-bdae-efb5851b299d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExecuteExplain item.
            /// </summary>
            [RepositoryItem("8c51c656-8da9-4c6e-a6db-04e04a99d42a")]
            public virtual Ranorex.Button ExecuteExplain
            {
                get
                {
                    return _executeexplainInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ExecuteExplain item info.
            /// </summary>
            [RepositoryItemInfo("8c51c656-8da9-4c6e-a6db-04e04a99d42a")]
            public virtual RepoItemInfo ExecuteExplainInfo
            {
                get
                {
                    return _executeexplainInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}