///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10568
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10568 element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("91623831-5c28-4f66-9b7e-a56269685aa6")]
    public partial class TC10568 : RepoGenBaseFolder
    {
        static TC10568 instance = new TC10568();
        TC10568Folders.ApplicationAppFolder _application;
        TC10568Folders.DatastudioAppFolder _datastudio;
        TC10568Folders.AmazonRedshiftAppFolder _amazonredshift;
        TC10568Folders.UntiltledApplicationAppFolder _untiltledapplication;

        /// <summary>
        /// Gets the singleton class instance representing the TC10568 element repository.
        /// </summary>
        [RepositoryFolder("91623831-5c28-4f66-9b7e-a56269685aa6")]
        public static TC10568 Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10568() 
            : base("TC10568", "/", null, 0, false, "91623831-5c28-4f66-9b7e-a56269685aa6", ".\\RepositoryImages\\TC1056891623831.rximgres")
        {
            _application = new TC10568Folders.ApplicationAppFolder(this);
            _datastudio = new TC10568Folders.DatastudioAppFolder(this);
            _amazonredshift = new TC10568Folders.AmazonRedshiftAppFolder(this);
            _untiltledapplication = new TC10568Folders.UntiltledApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("91623831-5c28-4f66-9b7e-a56269685aa6")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("5492682b-d918-4a14-ac17-280d173a98f4")]
        public virtual TC10568Folders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The Datastudio folder.
        /// </summary>
        [RepositoryFolder("6b6fe566-cfa1-48cd-93a6-ac3a3058cc84")]
        public virtual TC10568Folders.DatastudioAppFolder Datastudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The AmazonRedshift folder.
        /// </summary>
        [RepositoryFolder("338171eb-dab7-4f48-82d6-14e3294ebca2")]
        public virtual TC10568Folders.AmazonRedshiftAppFolder AmazonRedshift
        {
            get { return _amazonredshift; }
        }

        /// <summary>
        /// The UntiltledApplication folder.
        /// </summary>
        [RepositoryFolder("52c785d4-2758-4d09-b34e-e7b516728b4c")]
        public virtual TC10568Folders.UntiltledApplicationAppFolder UntiltledApplication
        {
            get { return _untiltledapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10568Folders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("5492682b-d918-4a14-ac17-280d173a98f4")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _databasetreeInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title='Aqua Data Studio']", parentFolder, 30000, null, true, "5492682b-d918-4a14-ac17-280d173a98f4", "")
            {
                _databasetreeInfo = new RepoItemInfo(this, "DatabaseTree", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/container[@name='myVerticalSplitter']/container[@name='myInnerComponent']/container[@name='myFirstComponent']//container[@name='viewport']/tree[@name='schemaTree']//treeitem[@text='Amazon Redshift']/treeitem[@text='Databases']", 30000, null, "3339f41a-8dd1-4875-9d72-96982f3f9d1f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5492682b-d918-4a14-ac17-280d173a98f4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5492682b-d918-4a14-ac17-280d173a98f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DatabaseTree item.
            /// </summary>
            [RepositoryItem("3339f41a-8dd1-4875-9d72-96982f3f9d1f")]
            public virtual Ranorex.TreeItem DatabaseTree
            {
                get
                {
                    return _databasetreeInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DatabaseTree item info.
            /// </summary>
            [RepositoryItemInfo("3339f41a-8dd1-4875-9d72-96982f3f9d1f")]
            public virtual RepoItemInfo DatabaseTreeInfo
            {
                get
                {
                    return _databasetreeInfo;
                }
            }
        }

        /// <summary>
        /// The DatastudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("6b6fe566-cfa1-48cd-93a6-ac3a3058cc84")]
        public partial class DatastudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _edittableInfo;

            /// <summary>
            /// Creates a new Datastudio  folder.
            /// </summary>
            public DatastudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "6b6fe566-cfa1-48cd-93a6-ac3a3058cc84", "")
            {
                _edittableInfo = new RepoItemInfo(this, "EditTable", ".//menuitem[@text~'^Edit\\ Table\\ Data\\ \\(Top\\ 1000']", 30000, null, "c8b7a053-dbdf-4783-9f7f-dff850a12be8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6b6fe566-cfa1-48cd-93a6-ac3a3058cc84")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6b6fe566-cfa1-48cd-93a6-ac3a3058cc84")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EditTable item.
            /// </summary>
            [RepositoryItem("c8b7a053-dbdf-4783-9f7f-dff850a12be8")]
            public virtual Ranorex.MenuItem EditTable
            {
                get
                {
                    return _edittableInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The EditTable item info.
            /// </summary>
            [RepositoryItemInfo("c8b7a053-dbdf-4783-9f7f-dff850a12be8")]
            public virtual RepoItemInfo EditTableInfo
            {
                get
                {
                    return _edittableInfo;
                }
            }
        }

        /// <summary>
        /// The AmazonRedshiftAppFolder folder.
        /// </summary>
        [RepositoryFolder("338171eb-dab7-4f48-82d6-14e3294ebca2")]
        public partial class AmazonRedshiftAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabledataInfo;
            RepoItemInfo _primarykeyInfo;
            RepoItemInfo _previewsqlInfo;
            RepoItemInfo _messagesInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new AmazonRedshift  folder.
            /// </summary>
            public AmazonRedshiftAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AmazonRedshift", "/form[@title~'^Amazon\\ Redshift\\ ']", parentFolder, 30000, null, true, "338171eb-dab7-4f48-82d6-14e3294ebca2", "")
            {
                _tabledataInfo = new RepoItemInfo(this, "TableData", ".//container[@name='contentPanel']//tabpage[@title='Table Data   ']", 30000, null, "d299a7c0-5efe-418c-845f-3b9c4ef30ec1");
                _primarykeyInfo = new RepoItemInfo(this, "PrimaryKey", ".//container[@name='contentPanel']//tabpage[@title~'^Primary\\ Key\\ -\\ ads_db\\.publ']", 30000, null, "77952b3b-62d1-4334-865b-3b6efd31c982");
                _previewsqlInfo = new RepoItemInfo(this, "PreviewSQL", ".//container[@name='contentPanel']//tabpage[@title='Preview SQL   ']", 30000, null, "a2b6b1c3-1e4f-4ba5-8b52-112841b5c3e5");
                _messagesInfo = new RepoItemInfo(this, "Messages", ".//container[@name='contentPanel']//tabpage[@title='Messages   ']", 30000, null, "1c867cb1-2886-4ddd-80fc-446eb2d8b0d6");
                _closeInfo = new RepoItemInfo(this, "Close", ".//button[@accessiblename='Close']", 30000, null, "2cb069bb-5649-4395-99b5-e5b11ce878ec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("338171eb-dab7-4f48-82d6-14e3294ebca2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("338171eb-dab7-4f48-82d6-14e3294ebca2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TableData item.
            /// </summary>
            [RepositoryItem("d299a7c0-5efe-418c-845f-3b9c4ef30ec1")]
            public virtual Ranorex.TabPage TableData
            {
                get
                {
                    return _tabledataInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TableData item info.
            /// </summary>
            [RepositoryItemInfo("d299a7c0-5efe-418c-845f-3b9c4ef30ec1")]
            public virtual RepoItemInfo TableDataInfo
            {
                get
                {
                    return _tabledataInfo;
                }
            }

            /// <summary>
            /// The PrimaryKey item.
            /// </summary>
            [RepositoryItem("77952b3b-62d1-4334-865b-3b6efd31c982")]
            public virtual Ranorex.TabPage PrimaryKey
            {
                get
                {
                    return _primarykeyInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The PrimaryKey item info.
            /// </summary>
            [RepositoryItemInfo("77952b3b-62d1-4334-865b-3b6efd31c982")]
            public virtual RepoItemInfo PrimaryKeyInfo
            {
                get
                {
                    return _primarykeyInfo;
                }
            }

            /// <summary>
            /// The PreviewSQL item.
            /// </summary>
            [RepositoryItem("a2b6b1c3-1e4f-4ba5-8b52-112841b5c3e5")]
            public virtual Ranorex.TabPage PreviewSQL
            {
                get
                {
                    return _previewsqlInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The PreviewSQL item info.
            /// </summary>
            [RepositoryItemInfo("a2b6b1c3-1e4f-4ba5-8b52-112841b5c3e5")]
            public virtual RepoItemInfo PreviewSQLInfo
            {
                get
                {
                    return _previewsqlInfo;
                }
            }

            /// <summary>
            /// The Messages item.
            /// </summary>
            [RepositoryItem("1c867cb1-2886-4ddd-80fc-446eb2d8b0d6")]
            public virtual Ranorex.TabPage Messages
            {
                get
                {
                    return _messagesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Messages item info.
            /// </summary>
            [RepositoryItemInfo("1c867cb1-2886-4ddd-80fc-446eb2d8b0d6")]
            public virtual RepoItemInfo MessagesInfo
            {
                get
                {
                    return _messagesInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("2cb069bb-5649-4395-99b5-e5b11ce878ec")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("2cb069bb-5649-4395-99b5-e5b11ce878ec")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The UntiltledApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("52c785d4-2758-4d09-b34e-e7b516728b4c")]
        public partial class UntiltledApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _executeeditInfo;

            /// <summary>
            /// Creates a new UntiltledApplication  folder.
            /// </summary>
            public UntiltledApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UntiltledApplication", "/form[@title~'^Aqua\\ Data\\ Studio\\ \\[Untitle']", parentFolder, 30000, null, true, "52c785d4-2758-4d09-b34e-e7b516728b4c", "")
            {
                _executeeditInfo = new RepoItemInfo(this, "ExecuteEdit", ".//container[@type='ToolWindowsPane']/container[@name='myLayeredPane']/?/?/container[@type='ThreeComponentsSplitter']/container[@name='myInnerComponent']//container[@type='QueryPanel']//container[@name='toolBar']/button[@name='executeEditButton']", 30000, null, "fe990cd2-a2bc-460e-8ec9-3fc53d26902c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("52c785d4-2758-4d09-b34e-e7b516728b4c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("52c785d4-2758-4d09-b34e-e7b516728b4c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExecuteEdit item.
            /// </summary>
            [RepositoryItem("fe990cd2-a2bc-460e-8ec9-3fc53d26902c")]
            public virtual Ranorex.Button ExecuteEdit
            {
                get
                {
                    return _executeeditInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ExecuteEdit item info.
            /// </summary>
            [RepositoryItemInfo("fe990cd2-a2bc-460e-8ec9-3fc53d26902c")]
            public virtual RepoItemInfo ExecuteEditInfo
            {
                get
                {
                    return _executeeditInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}