///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10591
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10591Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("8176ba2f-095b-47f7-81b2-b3903cf1705f")]
    public partial class TC10591Repo : RepoGenBaseFolder
    {
        static TC10591Repo instance = new TC10591Repo();
        TC10591RepoFolders.VAWindowAppFolder _vawindow;
        TC10591RepoFolders.ApplicationAppFolder _application;
        TC10591RepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        TC10591RepoFolders.OpenWindowAppFolder _openwindow;

        /// <summary>
        /// Gets the singleton class instance representing the TC10591Repo element repository.
        /// </summary>
        [RepositoryFolder("8176ba2f-095b-47f7-81b2-b3903cf1705f")]
        public static TC10591Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10591Repo() 
            : base("TC10591Repo", "/", null, 0, false, "8176ba2f-095b-47f7-81b2-b3903cf1705f", ".\\RepositoryImages\\TC10591Repo8176ba2f.rximgres")
        {
            _vawindow = new TC10591RepoFolders.VAWindowAppFolder(this);
            _application = new TC10591RepoFolders.ApplicationAppFolder(this);
            _sunawtwindow = new TC10591RepoFolders.SunAwtWindowAppFolder(this);
            _openwindow = new TC10591RepoFolders.OpenWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8176ba2f-095b-47f7-81b2-b3903cf1705f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The VAWindow folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public virtual TC10591RepoFolders.VAWindowAppFolder VAWindow
        {
            get { return _vawindow; }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public virtual TC10591RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
        public virtual TC10591RepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The OpenWindow folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public virtual TC10591RepoFolders.OpenWindowAppFolder OpenWindow
        {
            get { return _openwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10591RepoFolders
    {
        /// <summary>
        /// The VAWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public partial class VAWindowAppFolder : RepoGenBaseFolder
        {
            TC10591RepoFolders.ContainerLeftPanelFolder _containerleftpanel;
            TC10591RepoFolders.ContainerContentPanelFolder _containercontentpanel;
            TC10591RepoFolders.ContainerMainPanelFolder _containermainpanel;
            RepoItemInfo _closewindowInfo;
            RepoItemInfo _automaticInfo;
            RepoItemInfo _panelInfo;
            RepoItemInfo _panel1Info;
            VisualizationWindowInfoClass _visualizationwindowInfo;

            /// <summary>
            /// Creates a new VAWindow  folder.
            /// </summary>
            public VAWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VAWindow", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[Sampl']", parentFolder, 30000, null, true, "28ef3ff7-5142-4c80-9fe2-5119aa3572c6", "")
            {
                _containerleftpanel = new TC10591RepoFolders.ContainerLeftPanelFolder(this);
                _containercontentpanel = new TC10591RepoFolders.ContainerContentPanelFolder(this);
                _containermainpanel = new TC10591RepoFolders.ContainerMainPanelFolder(this);
                _closewindowInfo = new RepoItemInfo(this, "CloseWindow", ".//button[@accessiblename='Close']", 30000, null, "eb7f4e53-1ab2-4471-9058-e4ab8e63fccd");
                _automaticInfo = new RepoItemInfo(this, "Automatic", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 11']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']", 30000, null, "3608f27e-85e4-4f6d-88a2-2c60c0d595b6");
                _panelInfo = new RepoItemInfo(this, "Panel", "container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 11']/container[@name='_worksheetPanel']//container[@name='cols']//container[@name='panel']", 30000, null, "78744f76-d6e1-4a3f-a8f2-21371d0d0ef7");
                _panel1Info = new RepoItemInfo(this, "Panel1", "container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 11']/container[@name='_worksheetPanel']//container[@name='rows']//container[@name='panel']", 30000, null, "fbff7f12-6684-422f-8e9a-1fcc6cedaee0");
                _visualizationwindowInfo = new VisualizationWindowInfoClass(this);
            }

            /// <summary>
            /// The VisualizationWindowInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("041fff51-32d9-4879-a1b5-32771b9cb43a")]
            public class VisualizationWindowInfoClass : RepoItemInfo
            {
                /// <summary>
                /// VisualizationWindowInfoClass class constructor.
                /// </summary>
                public VisualizationWindowInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "VisualizationWindow", "container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 11']//container[@name='main']/container[@name='_cardPanel']/container[@name='_gridPanel']/?/?/container[@type='PivotTableOverlayPanel']", 30000, null, "041fff51-32d9-4879-a1b5-32771b9cb43a")
                { }

                /// <summary>
                /// Gets the ChangetoPieChart item image.
                /// </summary>
                /// <returns>The ChangetoPieChart image.</returns>
                [RepositoryImage("f0512ca6-a0b2-48d8-8469-7f59a125b9f5")]
                public CompressedImage GetChangetoPieChart()
                {
                    return GetImage("f0512ca6-a0b2-48d8-8469-7f59a125b9f5");
                }

                /// <summary>
                /// Gets the ChangetoPieChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("f0512ca6-a0b2-48d8-8469-7f59a125b9f5")]
                public CompressedImage GetChangetoPieChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("f0512ca6-a0b2-48d8-8469-7f59a125b9f5", cropRect);
                }

                /// <summary>
                /// Gets the DragPCtoColumn item image.
                /// </summary>
                /// <returns>The DragPCtoColumn image.</returns>
                [RepositoryImage("e839b2fb-4ae5-4f43-be65-9f37c24abef8")]
                public CompressedImage GetDragPCtoColumn()
                {
                    return GetImage("e839b2fb-4ae5-4f43-be65-9f37c24abef8");
                }

                /// <summary>
                /// Gets the DragPCtoColumn item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e839b2fb-4ae5-4f43-be65-9f37c24abef8")]
                public CompressedImage GetDragPCtoColumn(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e839b2fb-4ae5-4f43-be65-9f37c24abef8", cropRect);
                }

                /// <summary>
                /// Gets the DragStateandPCtoColumn item image.
                /// </summary>
                /// <returns>The DragStateandPCtoColumn image.</returns>
                [RepositoryImage("aafa5f74-2fb3-484c-92cb-0c73a696a014")]
                public CompressedImage GetDragStateandPCtoColumn()
                {
                    return GetImage("aafa5f74-2fb3-484c-92cb-0c73a696a014");
                }

                /// <summary>
                /// Gets the DragStateandPCtoColumn item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("aafa5f74-2fb3-484c-92cb-0c73a696a014")]
                public CompressedImage GetDragStateandPCtoColumn(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("aafa5f74-2fb3-484c-92cb-0c73a696a014", cropRect);
                }

                /// <summary>
                /// Gets the DragStatetoRwo item image.
                /// </summary>
                /// <returns>The DragStatetoRwo image.</returns>
                [RepositoryImage("f8ff6e6e-6f3a-4d90-b5cd-9227b9970384")]
                public CompressedImage GetDragStatetoRwo()
                {
                    return GetImage("f8ff6e6e-6f3a-4d90-b5cd-9227b9970384");
                }

                /// <summary>
                /// Gets the DragStatetoRwo item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("f8ff6e6e-6f3a-4d90-b5cd-9227b9970384")]
                public CompressedImage GetDragStatetoRwo(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("f8ff6e6e-6f3a-4d90-b5cd-9227b9970384", cropRect);
                }

                /// <summary>
                /// Gets the DragtoStatetoColumn item image.
                /// </summary>
                /// <returns>The DragtoStatetoColumn image.</returns>
                [RepositoryImage("5ae7a423-67d3-49de-8818-f27515f16767")]
                public CompressedImage GetDragtoStatetoColumn()
                {
                    return GetImage("5ae7a423-67d3-49de-8818-f27515f16767");
                }

                /// <summary>
                /// Gets the DragtoStatetoColumn item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("5ae7a423-67d3-49de-8818-f27515f16767")]
                public CompressedImage GetDragtoStatetoColumn(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("5ae7a423-67d3-49de-8818-f27515f16767", cropRect);
                }

                /// <summary>
                /// Gets the ProfitToRow item image.
                /// </summary>
                /// <returns>The ProfitToRow image.</returns>
                [RepositoryImage("056692f9-a9c0-4fa2-9537-d9034bff4384")]
                public CompressedImage GetProfitToRow()
                {
                    return GetImage("056692f9-a9c0-4fa2-9537-d9034bff4384");
                }

                /// <summary>
                /// Gets the ProfitToRow item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("056692f9-a9c0-4fa2-9537-d9034bff4384")]
                public CompressedImage GetProfitToRow(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("056692f9-a9c0-4fa2-9537-d9034bff4384", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseWindow item.
            /// </summary>
            [RepositoryItem("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual Ranorex.Button CloseWindow
            {
                get
                {
                    return _closewindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseWindow item info.
            /// </summary>
            [RepositoryItemInfo("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual RepoItemInfo CloseWindowInfo
            {
                get
                {
                    return _closewindowInfo;
                }
            }

            /// <summary>
            /// The Automatic item.
            /// </summary>
            [RepositoryItem("3608f27e-85e4-4f6d-88a2-2c60c0d595b6")]
            public virtual Ranorex.ComboBox Automatic
            {
                get
                {
                    return _automaticInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Automatic item info.
            /// </summary>
            [RepositoryItemInfo("3608f27e-85e4-4f6d-88a2-2c60c0d595b6")]
            public virtual RepoItemInfo AutomaticInfo
            {
                get
                {
                    return _automaticInfo;
                }
            }

            /// <summary>
            /// The Panel item.
            /// </summary>
            [RepositoryItem("78744f76-d6e1-4a3f-a8f2-21371d0d0ef7")]
            public virtual Ranorex.Container Panel
            {
                get
                {
                    return _panelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel item info.
            /// </summary>
            [RepositoryItemInfo("78744f76-d6e1-4a3f-a8f2-21371d0d0ef7")]
            public virtual RepoItemInfo PanelInfo
            {
                get
                {
                    return _panelInfo;
                }
            }

            /// <summary>
            /// The Panel1 item.
            /// </summary>
            [RepositoryItem("fbff7f12-6684-422f-8e9a-1fcc6cedaee0")]
            public virtual Ranorex.Container Panel1
            {
                get
                {
                    return _panel1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel1 item info.
            /// </summary>
            [RepositoryItemInfo("fbff7f12-6684-422f-8e9a-1fcc6cedaee0")]
            public virtual RepoItemInfo Panel1Info
            {
                get
                {
                    return _panel1Info;
                }
            }

            /// <summary>
            /// The VisualizationWindow item.
            /// </summary>
            [RepositoryItem("041fff51-32d9-4879-a1b5-32771b9cb43a")]
            public virtual Ranorex.Container VisualizationWindow
            {
                get
                {
                    return _visualizationwindowInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The VisualizationWindow item info.
            /// </summary>
            [RepositoryItemInfo("041fff51-32d9-4879-a1b5-32771b9cb43a")]
            public virtual VisualizationWindowInfoClass VisualizationWindowInfo
            {
                get
                {
                    return _visualizationwindowInfo;
                }
            }

            /// <summary>
            /// The ContainerLeftPanel folder.
            /// </summary>
            [RepositoryFolder("c0e90037-7361-4bfc-b406-56cbb3524236")]
            public virtual TC10591RepoFolders.ContainerLeftPanelFolder ContainerLeftPanel
            {
                get { return _containerleftpanel; }
            }

            /// <summary>
            /// The ContainerContentPanel folder.
            /// </summary>
            [RepositoryFolder("d3397e45-2457-4b53-93da-1eabfcbc2991")]
            public virtual TC10591RepoFolders.ContainerContentPanelFolder ContainerContentPanel
            {
                get { return _containercontentpanel; }
            }

            /// <summary>
            /// The ContainerMainPanel folder.
            /// </summary>
            [RepositoryFolder("3e3c0481-0469-4905-a589-9632efa3bb91")]
            public virtual TC10591RepoFolders.ContainerMainPanelFolder ContainerMainPanel
            {
                get { return _containermainpanel; }
            }
        }

        /// <summary>
        /// The ContainerLeftPanelFolder folder.
        /// </summary>
        [RepositoryFolder("c0e90037-7361-4bfc-b406-56cbb3524236")]
        public partial class ContainerLeftPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _productcategoryInfo;
            RepoItemInfo _stateInfo;
            RepoItemInfo _sumprofitInfo;
            RepoItemInfo _latitudeInfo;
            RepoItemInfo _longitudeInfo;

            /// <summary>
            /// Creates a new ContainerLeftPanel  folder.
            /// </summary>
            public ContainerLeftPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerLeftPanel", "container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_leftPanel']", parentFolder, 30000, null, false, "c0e90037-7361-4bfc-b406-56cbb3524236", "")
            {
                _productcategoryInfo = new RepoItemInfo(this, "ProductCategory", ".//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Product Category']", 30000, null, "286a1bae-11f4-4b11-9b28-799442fd4716");
                _stateInfo = new RepoItemInfo(this, "State", ".//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='State']", 30000, null, "a7843a01-0254-47fa-9673-ee72c3e00926");
                _sumprofitInfo = new RepoItemInfo(this, "SUMProfit", ".//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(Profit)']", 30000, null, "c08039f2-cf61-497c-8cf5-552f21879832");
                _latitudeInfo = new RepoItemInfo(this, "Latitude", ".//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Latitude']", 30000, null, "5ec4c377-c4a5-4632-aebf-949552f6af27");
                _longitudeInfo = new RepoItemInfo(this, "Longitude", ".//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Longitude']", 30000, null, "a6849b78-0a09-4a28-90e0-4b594668e0ba");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0e90037-7361-4bfc-b406-56cbb3524236")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0e90037-7361-4bfc-b406-56cbb3524236")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProductCategory item.
            /// </summary>
            [RepositoryItem("286a1bae-11f4-4b11-9b28-799442fd4716")]
            public virtual Ranorex.ListItem ProductCategory
            {
                get
                {
                    return _productcategoryInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProductCategory item info.
            /// </summary>
            [RepositoryItemInfo("286a1bae-11f4-4b11-9b28-799442fd4716")]
            public virtual RepoItemInfo ProductCategoryInfo
            {
                get
                {
                    return _productcategoryInfo;
                }
            }

            /// <summary>
            /// The State item.
            /// </summary>
            [RepositoryItem("a7843a01-0254-47fa-9673-ee72c3e00926")]
            public virtual Ranorex.ListItem State
            {
                get
                {
                    return _stateInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The State item info.
            /// </summary>
            [RepositoryItemInfo("a7843a01-0254-47fa-9673-ee72c3e00926")]
            public virtual RepoItemInfo StateInfo
            {
                get
                {
                    return _stateInfo;
                }
            }

            /// <summary>
            /// The SUMProfit item.
            /// </summary>
            [RepositoryItem("c08039f2-cf61-497c-8cf5-552f21879832")]
            public virtual Ranorex.ListItem SUMProfit
            {
                get
                {
                    return _sumprofitInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMProfit item info.
            /// </summary>
            [RepositoryItemInfo("c08039f2-cf61-497c-8cf5-552f21879832")]
            public virtual RepoItemInfo SUMProfitInfo
            {
                get
                {
                    return _sumprofitInfo;
                }
            }

            /// <summary>
            /// The Latitude item.
            /// </summary>
            [RepositoryItem("5ec4c377-c4a5-4632-aebf-949552f6af27")]
            public virtual Ranorex.ListItem Latitude
            {
                get
                {
                    return _latitudeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Latitude item info.
            /// </summary>
            [RepositoryItemInfo("5ec4c377-c4a5-4632-aebf-949552f6af27")]
            public virtual RepoItemInfo LatitudeInfo
            {
                get
                {
                    return _latitudeInfo;
                }
            }

            /// <summary>
            /// The Longitude item.
            /// </summary>
            [RepositoryItem("a6849b78-0a09-4a28-90e0-4b594668e0ba")]
            public virtual Ranorex.ListItem Longitude
            {
                get
                {
                    return _longitudeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Longitude item info.
            /// </summary>
            [RepositoryItemInfo("a6849b78-0a09-4a28-90e0-4b594668e0ba")]
            public virtual RepoItemInfo LongitudeInfo
            {
                get
                {
                    return _longitudeInfo;
                }
            }
        }

        /// <summary>
        /// The ContainerContentPanelFolder folder.
        /// </summary>
        [RepositoryFolder("d3397e45-2457-4b53-93da-1eabfcbc2991")]
        public partial class ContainerContentPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _worksheetpanelInfo;
            RepoItemInfo _panelInfo;
            RepoItemInfo _panel1Info;

            /// <summary>
            /// Creates a new ContainerContentPanel  folder.
            /// </summary>
            public ContainerContentPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerContentPanel", "container[@name='_mainPanel']/container[@name='_contentPanel']", parentFolder, 30000, null, false, "d3397e45-2457-4b53-93da-1eabfcbc2991", "")
            {
                _worksheetpanelInfo = new RepoItemInfo(this, "WorksheetPanel", "?/?/container[@name='_sheetsPane']/container[@name='Worksheet 11']//container[@type='WorksheetPanel']", 30000, null, "a733947d-705f-48b6-a1e9-0fe33f924ac9");
                _panelInfo = new RepoItemInfo(this, "Panel", "container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 11']/container[@name='_worksheetPanel']//container[@name='cols']//container[@name='panel']", 30000, null, "5349cebb-a501-4261-bf28-839711be58fb");
                _panel1Info = new RepoItemInfo(this, "Panel1", "container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 11']/container[@name='_worksheetPanel']//container[@name='rows']//container[@name='panel']", 30000, null, "613be8e8-f672-4300-93b2-83d640c38938");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d3397e45-2457-4b53-93da-1eabfcbc2991")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d3397e45-2457-4b53-93da-1eabfcbc2991")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WorksheetPanel item.
            /// </summary>
            [RepositoryItem("a733947d-705f-48b6-a1e9-0fe33f924ac9")]
            public virtual Ranorex.Container WorksheetPanel
            {
                get
                {
                    return _worksheetpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WorksheetPanel item info.
            /// </summary>
            [RepositoryItemInfo("a733947d-705f-48b6-a1e9-0fe33f924ac9")]
            public virtual RepoItemInfo WorksheetPanelInfo
            {
                get
                {
                    return _worksheetpanelInfo;
                }
            }

            /// <summary>
            /// The Panel item.
            /// </summary>
            [RepositoryItem("5349cebb-a501-4261-bf28-839711be58fb")]
            public virtual Ranorex.Container Panel
            {
                get
                {
                    return _panelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel item info.
            /// </summary>
            [RepositoryItemInfo("5349cebb-a501-4261-bf28-839711be58fb")]
            public virtual RepoItemInfo PanelInfo
            {
                get
                {
                    return _panelInfo;
                }
            }

            /// <summary>
            /// The Panel1 item.
            /// </summary>
            [RepositoryItem("613be8e8-f672-4300-93b2-83d640c38938")]
            public virtual Ranorex.Container Panel1
            {
                get
                {
                    return _panel1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Panel1 item info.
            /// </summary>
            [RepositoryItemInfo("613be8e8-f672-4300-93b2-83d640c38938")]
            public virtual RepoItemInfo Panel1Info
            {
                get
                {
                    return _panel1Info;
                }
            }
        }

        /// <summary>
        /// The ContainerMainPanelFolder folder.
        /// </summary>
        [RepositoryFolder("3e3c0481-0469-4905-a589-9632efa3bb91")]
        public partial class ContainerMainPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _containercanvasInfo;
            RepoItemInfo _productcategoryInfo;
            RepoItemInfo _colorInfo;

            /// <summary>
            /// Creates a new ContainerMainPanel  folder.
            /// </summary>
            public ContainerMainPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerMainPanel", "container[@name='_mainPanel']", parentFolder, 30000, null, false, "3e3c0481-0469-4905-a589-9632efa3bb91", "")
            {
                _containercanvasInfo = new RepoItemInfo(this, "ContainerCanvas", ".//container[@name='_sheetsPane']/container[@name='Worksheet 11']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container[@name='_canvas']", 30000, null, "0d8571f7-ac0a-4dad-8ae8-806eeb8248dc");
                _productcategoryInfo = new RepoItemInfo(this, "ProductCategory", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 11']/container[@name='_worksheetPanel']//container[@name='rows']//text[@caption='Product Category']", 30000, null, "3039692c-2a58-4d5a-9a92-3ebb4f7f061d");
                _colorInfo = new RepoItemInfo(this, "Color", "container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 11']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Color']", 30000, null, "a20b8e4d-6d96-4cf8-8941-8ea86ba20d7a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3e3c0481-0469-4905-a589-9632efa3bb91")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e3c0481-0469-4905-a589-9632efa3bb91")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerCanvas item.
            /// </summary>
            [RepositoryItem("0d8571f7-ac0a-4dad-8ae8-806eeb8248dc")]
            public virtual Ranorex.Container ContainerCanvas
            {
                get
                {
                    return _containercanvasInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerCanvas item info.
            /// </summary>
            [RepositoryItemInfo("0d8571f7-ac0a-4dad-8ae8-806eeb8248dc")]
            public virtual RepoItemInfo ContainerCanvasInfo
            {
                get
                {
                    return _containercanvasInfo;
                }
            }

            /// <summary>
            /// The ProductCategory item.
            /// </summary>
            [RepositoryItem("3039692c-2a58-4d5a-9a92-3ebb4f7f061d")]
            public virtual Ranorex.Text ProductCategory
            {
                get
                {
                    return _productcategoryInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ProductCategory item info.
            /// </summary>
            [RepositoryItemInfo("3039692c-2a58-4d5a-9a92-3ebb4f7f061d")]
            public virtual RepoItemInfo ProductCategoryInfo
            {
                get
                {
                    return _productcategoryInfo;
                }
            }

            /// <summary>
            /// The Color item.
            /// </summary>
            [RepositoryItem("a20b8e4d-6d96-4cf8-8941-8ea86ba20d7a")]
            public virtual Ranorex.Text Color
            {
                get
                {
                    return _colorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Color item info.
            /// </summary>
            [RepositoryItemInfo("a20b8e4d-6d96-4cf8-8941-8ea86ba20d7a")]
            public virtual RepoItemInfo ColorInfo
            {
                get
                {
                    return _colorInfo;
                }
            }
        }

        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filemenuInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "d54a3fac-3b92-4b4a-9c2b-770fb3053792", "")
            {
                _filemenuInfo = new RepoItemInfo(this, "FileMenu", ".//menuitem[@text='File']", 30000, null, "da992c0f-dfcc-4c8a-a60b-60218253b432");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileMenu item.
            /// </summary>
            [RepositoryItem("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual Ranorex.MenuItem FileMenu
            {
                get
                {
                    return _filemenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FileMenu item info.
            /// </summary>
            [RepositoryItemInfo("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual RepoItemInfo FileMenuInfo
            {
                get
                {
                    return _filemenuInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _piechartInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, false, "c3edb99e-6572-42f7-8b35-012be61bdeb6", "")
            {
                _piechartInfo = new RepoItemInfo(this, "PieChart", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Pie']", 30000, null, "5d463f06-5f0b-43b1-9078-8496a4951007");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3edb99e-6572-42f7-8b35-012be61bdeb6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PieChart item.
            /// </summary>
            [RepositoryItem("5d463f06-5f0b-43b1-9078-8496a4951007")]
            public virtual Ranorex.ListItem PieChart
            {
                get
                {
                    return _piechartInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The PieChart item info.
            /// </summary>
            [RepositoryItemInfo("5d463f06-5f0b-43b1-9078-8496a4951007")]
            public virtual RepoItemInfo PieChartInfo
            {
                get
                {
                    return _piechartInfo;
                }
            }
        }

        /// <summary>
        /// The OpenWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public partial class OpenWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filepathtextboxInfo;
            RepoItemInfo _openbuttonInfo;

            /// <summary>
            /// Creates a new OpenWindow  folder.
            /// </summary>
            public OpenWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenWindow", "/form[@title='Open']", parentFolder, 30000, null, true, "951fcb26-33b8-49e9-9d15-b9683c621e3f", "")
            {
                _filepathtextboxInfo = new RepoItemInfo(this, "FilePathTextbox", ".//element/container[@type='JPanel']/container[3]/container[2]/text[@accessiblename='File name:']", 30000, null, "5d62603f-d3ac-4200-9d2a-4347326a6699");
                _openbuttonInfo = new RepoItemInfo(this, "OpenButton", ".//element/container[@type='JPanel']/container[3]/container[3]/button[@text='Open']", 30000, null, "89dcbd3d-2d03-4a6b-ad50-32f672ff7e54");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilePathTextbox item.
            /// </summary>
            [RepositoryItem("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual Ranorex.Text FilePathTextbox
            {
                get
                {
                    return _filepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilePathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual RepoItemInfo FilePathTextboxInfo
            {
                get
                {
                    return _filepathtextboxInfo;
                }
            }

            /// <summary>
            /// The OpenButton item.
            /// </summary>
            [RepositoryItem("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual Ranorex.Button OpenButton
            {
                get
                {
                    return _openbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenButton item info.
            /// </summary>
            [RepositoryItemInfo("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual RepoItemInfo OpenButtonInfo
            {
                get
                {
                    return _openbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}