///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ADSAutomationPhaseII.TC_10563
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TC10563Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("c9c03efc-8068-4505-8787-94d7827036ad")]
    public partial class TC10563Repo : RepoGenBaseFolder
    {
        static TC10563Repo instance = new TC10563Repo();
        TC10563RepoFolders.ApplicationAppFolder _application;
        TC10563RepoFolders.DataStudioAppFolder _datastudio;
        TC10563RepoFolders.OpenWindowAppFolder _openwindow;
        TC10563RepoFolders.ChartPropertiesWindowAppFolder _chartpropertieswindow;
        TC10563RepoFolders.SunAwtWindowAppFolder _sunawtwindow;
        TC10563RepoFolders.SaveChangesAppFolder _savechanges;
        TC10563RepoFolders.LabelWindowAppFolder _labelwindow;
        TC10563RepoFolders.Datastudio1AppFolder _datastudio1;
        TC10563RepoFolders.VAWindowAppFolder _vawindow;
        TC10563RepoFolders.VATestAppFolder _vatest;

        /// <summary>
        /// Gets the singleton class instance representing the TC10563Repo element repository.
        /// </summary>
        [RepositoryFolder("c9c03efc-8068-4505-8787-94d7827036ad")]
        public static TC10563Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TC10563Repo() 
            : base("TC10563Repo", "/", null, 0, false, "c9c03efc-8068-4505-8787-94d7827036ad", ".\\RepositoryImages\\TC10563Repoc9c03efc.rximgres")
        {
            _application = new TC10563RepoFolders.ApplicationAppFolder(this);
            _datastudio = new TC10563RepoFolders.DataStudioAppFolder(this);
            _openwindow = new TC10563RepoFolders.OpenWindowAppFolder(this);
            _chartpropertieswindow = new TC10563RepoFolders.ChartPropertiesWindowAppFolder(this);
            _sunawtwindow = new TC10563RepoFolders.SunAwtWindowAppFolder(this);
            _savechanges = new TC10563RepoFolders.SaveChangesAppFolder(this);
            _labelwindow = new TC10563RepoFolders.LabelWindowAppFolder(this);
            _datastudio1 = new TC10563RepoFolders.Datastudio1AppFolder(this);
            _vawindow = new TC10563RepoFolders.VAWindowAppFolder(this);
            _vatest = new TC10563RepoFolders.VATestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c9c03efc-8068-4505-8787-94d7827036ad")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Application folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public virtual TC10563RepoFolders.ApplicationAppFolder Application
        {
            get { return _application; }
        }

        /// <summary>
        /// The DataStudio folder.
        /// </summary>
        [RepositoryFolder("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
        public virtual TC10563RepoFolders.DataStudioAppFolder DataStudio
        {
            get { return _datastudio; }
        }

        /// <summary>
        /// The OpenWindow folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public virtual TC10563RepoFolders.OpenWindowAppFolder OpenWindow
        {
            get { return _openwindow; }
        }

        /// <summary>
        /// The ChartPropertiesWindow folder.
        /// </summary>
        [RepositoryFolder("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
        public virtual TC10563RepoFolders.ChartPropertiesWindowAppFolder ChartPropertiesWindow
        {
            get { return _chartpropertieswindow; }
        }

        /// <summary>
        /// The SunAwtWindow folder.
        /// </summary>
        [RepositoryFolder("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
        public virtual TC10563RepoFolders.SunAwtWindowAppFolder SunAwtWindow
        {
            get { return _sunawtwindow; }
        }

        /// <summary>
        /// The SaveChanges folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public virtual TC10563RepoFolders.SaveChangesAppFolder SaveChanges
        {
            get { return _savechanges; }
        }

        /// <summary>
        /// The LabelWindow folder.
        /// </summary>
        [RepositoryFolder("86c48c36-7d84-41a5-9bfd-48688233bff3")]
        public virtual TC10563RepoFolders.LabelWindowAppFolder LabelWindow
        {
            get { return _labelwindow; }
        }

        /// <summary>
        /// The Datastudio1 folder.
        /// </summary>
        [RepositoryFolder("5f32d409-b531-4fb5-8144-70eecbd1e487")]
        public virtual TC10563RepoFolders.Datastudio1AppFolder Datastudio1
        {
            get { return _datastudio1; }
        }

        /// <summary>
        /// The VAWindow folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public virtual TC10563RepoFolders.VAWindowAppFolder VAWindow
        {
            get { return _vawindow; }
        }

        /// <summary>
        /// The VATest folder.
        /// </summary>
        [RepositoryFolder("81ca719e-496c-47ca-9b1b-ad15c41ce9e7")]
        public virtual TC10563RepoFolders.VATestAppFolder VATest
        {
            get { return _vatest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class TC10563RepoFolders
    {
        /// <summary>
        /// The ApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
        public partial class ApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filemenuInfo;

            /// <summary>
            /// Creates a new Application  folder.
            /// </summary>
            public ApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Application", "/form[@title~'^Aqua\\ Data\\ Studio']", parentFolder, 30000, null, true, "d54a3fac-3b92-4b4a-9c2b-770fb3053792", "")
            {
                _filemenuInfo = new RepoItemInfo(this, "FileMenu", ".//menuitem[@text='File']", 30000, null, "da992c0f-dfcc-4c8a-a60b-60218253b432");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d54a3fac-3b92-4b4a-9c2b-770fb3053792")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileMenu item.
            /// </summary>
            [RepositoryItem("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual Ranorex.MenuItem FileMenu
            {
                get
                {
                    return _filemenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FileMenu item info.
            /// </summary>
            [RepositoryItemInfo("da992c0f-dfcc-4c8a-a60b-60218253b432")]
            public virtual RepoItemInfo FileMenuInfo
            {
                get
                {
                    return _filemenuInfo;
                }
            }
        }

        /// <summary>
        /// The DataStudioAppFolder folder.
        /// </summary>
        [RepositoryFolder("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
        public partial class DataStudioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openfileInfo;
            RepoItemInfo _jsliderInfo;

            /// <summary>
            /// Creates a new DataStudio  folder.
            /// </summary>
            public DataStudioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DataStudio", "/form[@processname='datastudio']", parentFolder, 30000, null, true, "bd2e48e4-5445-4ec3-a9b7-23d20f08afdb", "")
            {
                _openfileInfo = new RepoItemInfo(this, "OpenFile", ".//menuitem[@text='Open']", 30000, null, "4f2dba1a-2292-46cf-a03d-955d59d8f39c");
                _jsliderInfo = new RepoItemInfo(this, "JSlider", "?/?/container[@accessiblename='Size Slider']/?/?/slider[@type='JSlider']", 30000, null, "fa947f6b-f813-48d8-8e90-0a37cf5371f3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bd2e48e4-5445-4ec3-a9b7-23d20f08afdb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenFile item.
            /// </summary>
            [RepositoryItem("4f2dba1a-2292-46cf-a03d-955d59d8f39c")]
            public virtual Ranorex.MenuItem OpenFile
            {
                get
                {
                    return _openfileInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The OpenFile item info.
            /// </summary>
            [RepositoryItemInfo("4f2dba1a-2292-46cf-a03d-955d59d8f39c")]
            public virtual RepoItemInfo OpenFileInfo
            {
                get
                {
                    return _openfileInfo;
                }
            }

            /// <summary>
            /// The JSlider item.
            /// </summary>
            [RepositoryItem("fa947f6b-f813-48d8-8e90-0a37cf5371f3")]
            public virtual Ranorex.Slider JSlider
            {
                get
                {
                    return _jsliderInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The JSlider item info.
            /// </summary>
            [RepositoryItemInfo("fa947f6b-f813-48d8-8e90-0a37cf5371f3")]
            public virtual RepoItemInfo JSliderInfo
            {
                get
                {
                    return _jsliderInfo;
                }
            }
        }

        /// <summary>
        /// The OpenWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
        public partial class OpenWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filepathtextboxInfo;
            RepoItemInfo _openbuttonInfo;

            /// <summary>
            /// Creates a new OpenWindow  folder.
            /// </summary>
            public OpenWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenWindow", "/form[@title='Open']", parentFolder, 30000, null, true, "951fcb26-33b8-49e9-9d15-b9683c621e3f", "")
            {
                _filepathtextboxInfo = new RepoItemInfo(this, "FilePathTextbox", ".//element/container[@type='JPanel']/container[3]/container[2]/text[@accessiblename='File name:']", 30000, null, "5d62603f-d3ac-4200-9d2a-4347326a6699");
                _openbuttonInfo = new RepoItemInfo(this, "OpenButton", ".//element/container[@type='JPanel']/container[3]/container[3]/button[@text='Open']", 30000, null, "89dcbd3d-2d03-4a6b-ad50-32f672ff7e54");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("951fcb26-33b8-49e9-9d15-b9683c621e3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilePathTextbox item.
            /// </summary>
            [RepositoryItem("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual Ranorex.Text FilePathTextbox
            {
                get
                {
                    return _filepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilePathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("5d62603f-d3ac-4200-9d2a-4347326a6699")]
            public virtual RepoItemInfo FilePathTextboxInfo
            {
                get
                {
                    return _filepathtextboxInfo;
                }
            }

            /// <summary>
            /// The OpenButton item.
            /// </summary>
            [RepositoryItem("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual Ranorex.Button OpenButton
            {
                get
                {
                    return _openbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenButton item info.
            /// </summary>
            [RepositoryItemInfo("89dcbd3d-2d03-4a6b-ad50-32f672ff7e54")]
            public virtual RepoItemInfo OpenButtonInfo
            {
                get
                {
                    return _openbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ChartPropertiesWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
        public partial class ChartPropertiesWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _automaticInfo;
            RepoItemInfo _selectpointInfo;
            RepoItemInfo _labelInfo;
            RepoItemInfo _axesInfo;
            RepoItemInfo _shipdateInfo;
            RepoItemInfo _cardtypeInfo;
            RepoItemInfo _optionsInfo;
            RepoItemInfo _standardcomboInfo;

            /// <summary>
            /// Creates a new ChartPropertiesWindow  folder.
            /// </summary>
            public ChartPropertiesWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ChartPropertiesWindow", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[VA-te']", parentFolder, 30000, null, true, "7c7be239-e782-4085-b7f6-08e0c4bd0bc5", "")
            {
                _automaticInfo = new RepoItemInfo(this, "Automatic", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']", 30000, null, "bd98091f-27c9-409b-80fb-c1053d253c93");
                _selectpointInfo = new RepoItemInfo(this, "SelectPoint", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/?/?/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//combobox[@type='MarkChartTypeSelector$1']/button[@text='']", 30000, null, "0920f1be-53cf-4c78-a2d8-266f9c5f1f73");
                _labelInfo = new RepoItemInfo(this, "Label", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Label']", 30000, null, "6b010cb4-fd39-4b79-bf27-00f442d6bc6d");
                _axesInfo = new RepoItemInfo(this, "Axes", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Axes']", 30000, null, "c8237154-5d8f-48a6-b244-206645e5de9a");
                _shipdateInfo = new RepoItemInfo(this, "ShipDate", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='cols']//text[@caption='YEAR(ShipDate)']", 30000, null, "e90efb67-ad2a-41c2-a64d-fa0831b973da");
                _cardtypeInfo = new RepoItemInfo(this, "CardType", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']//container[@name='rows']//text[@caption='Card Type']", 30000, null, "33db2d5a-aa5e-4548-be67-05ad1e83b559");
                _optionsInfo = new RepoItemInfo(this, "Options", ".//container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Options']", 30000, null, "0aefdb57-9ddc-4b5d-a706-3a777739ea31");
                _standardcomboInfo = new RepoItemInfo(this, "StandardCombo", ".//container[@type='CPanel']/combobox[@type='CComboBox']", 30000, null, "003db0ab-cc1b-4c36-873f-49a6d23d6e29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7c7be239-e782-4085-b7f6-08e0c4bd0bc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Automatic item.
            /// </summary>
            [RepositoryItem("bd98091f-27c9-409b-80fb-c1053d253c93")]
            public virtual Ranorex.ComboBox Automatic
            {
                get
                {
                    return _automaticInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The Automatic item info.
            /// </summary>
            [RepositoryItemInfo("bd98091f-27c9-409b-80fb-c1053d253c93")]
            public virtual RepoItemInfo AutomaticInfo
            {
                get
                {
                    return _automaticInfo;
                }
            }

            /// <summary>
            /// The SelectPoint item.
            /// </summary>
            [RepositoryItem("0920f1be-53cf-4c78-a2d8-266f9c5f1f73")]
            public virtual Ranorex.Button SelectPoint
            {
                get
                {
                    return _selectpointInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SelectPoint item info.
            /// </summary>
            [RepositoryItemInfo("0920f1be-53cf-4c78-a2d8-266f9c5f1f73")]
            public virtual RepoItemInfo SelectPointInfo
            {
                get
                {
                    return _selectpointInfo;
                }
            }

            /// <summary>
            /// The Label item.
            /// </summary>
            [RepositoryItem("6b010cb4-fd39-4b79-bf27-00f442d6bc6d")]
            public virtual Ranorex.Text Label
            {
                get
                {
                    return _labelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label item info.
            /// </summary>
            [RepositoryItemInfo("6b010cb4-fd39-4b79-bf27-00f442d6bc6d")]
            public virtual RepoItemInfo LabelInfo
            {
                get
                {
                    return _labelInfo;
                }
            }

            /// <summary>
            /// The Axes item.
            /// </summary>
            [RepositoryItem("c8237154-5d8f-48a6-b244-206645e5de9a")]
            public virtual Ranorex.Text Axes
            {
                get
                {
                    return _axesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Axes item info.
            /// </summary>
            [RepositoryItemInfo("c8237154-5d8f-48a6-b244-206645e5de9a")]
            public virtual RepoItemInfo AxesInfo
            {
                get
                {
                    return _axesInfo;
                }
            }

            /// <summary>
            /// The ShipDate item.
            /// </summary>
            [RepositoryItem("e90efb67-ad2a-41c2-a64d-fa0831b973da")]
            public virtual Ranorex.Text ShipDate
            {
                get
                {
                    return _shipdateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ShipDate item info.
            /// </summary>
            [RepositoryItemInfo("e90efb67-ad2a-41c2-a64d-fa0831b973da")]
            public virtual RepoItemInfo ShipDateInfo
            {
                get
                {
                    return _shipdateInfo;
                }
            }

            /// <summary>
            /// The CardType item.
            /// </summary>
            [RepositoryItem("33db2d5a-aa5e-4548-be67-05ad1e83b559")]
            public virtual Ranorex.Text CardType
            {
                get
                {
                    return _cardtypeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CardType item info.
            /// </summary>
            [RepositoryItemInfo("33db2d5a-aa5e-4548-be67-05ad1e83b559")]
            public virtual RepoItemInfo CardTypeInfo
            {
                get
                {
                    return _cardtypeInfo;
                }
            }

            /// <summary>
            /// The Options item.
            /// </summary>
            [RepositoryItem("0aefdb57-9ddc-4b5d-a706-3a777739ea31")]
            public virtual Ranorex.Text Options
            {
                get
                {
                    return _optionsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Options item info.
            /// </summary>
            [RepositoryItemInfo("0aefdb57-9ddc-4b5d-a706-3a777739ea31")]
            public virtual RepoItemInfo OptionsInfo
            {
                get
                {
                    return _optionsInfo;
                }
            }

            /// <summary>
            /// The StandardCombo item.
            /// </summary>
            [RepositoryItem("003db0ab-cc1b-4c36-873f-49a6d23d6e29")]
            public virtual Ranorex.ComboBox StandardCombo
            {
                get
                {
                    return _standardcomboInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The StandardCombo item info.
            /// </summary>
            [RepositoryItemInfo("003db0ab-cc1b-4c36-873f-49a6d23d6e29")]
            public virtual RepoItemInfo StandardComboInfo
            {
                get
                {
                    return _standardcomboInfo;
                }
            }
        }

        /// <summary>
        /// The SunAwtWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
        public partial class SunAwtWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contextmenuInfo;
            RepoItemInfo _pieInfo;
            RepoItemInfo _removeInfo;
            RepoItemInfo _entirewindowInfo;

            /// <summary>
            /// Creates a new SunAwtWindow  folder.
            /// </summary>
            public SunAwtWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SunAwtWindow", "/form[@class='SunAwtWindow']", parentFolder, 30000, null, true, "84776f98-4aaa-4246-9a0b-9355abb3cff6", "")
            {
                _contextmenuInfo = new RepoItemInfo(this, "ContextMenu", ".//contextmenu", 30000, null, "a21e0391-83f9-4568-8f40-951dfd79f0c6");
                _pieInfo = new RepoItemInfo(this, "Pie", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Pie']", 30000, null, "b7d64c0f-a02b-40e1-90b4-c3022f693064");
                _removeInfo = new RepoItemInfo(this, "Remove", ".//menuitem[@text='Remove']", 30000, null, "0f45ee56-4ec4-4009-a610-615a5f57b460");
                _entirewindowInfo = new RepoItemInfo(this, "EntireWindow", ".//container[@name='viewport']/list[@name='ComboBox.list']/listitem[@text='Entire View']", 30000, null, "01c44355-2853-40fd-b196-fa0c15e2f64f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84776f98-4aaa-4246-9a0b-9355abb3cff6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContextMenu item.
            /// </summary>
            [RepositoryItem("a21e0391-83f9-4568-8f40-951dfd79f0c6")]
            public virtual Ranorex.ContextMenu ContextMenu
            {
                get
                {
                    return _contextmenuInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The ContextMenu item info.
            /// </summary>
            [RepositoryItemInfo("a21e0391-83f9-4568-8f40-951dfd79f0c6")]
            public virtual RepoItemInfo ContextMenuInfo
            {
                get
                {
                    return _contextmenuInfo;
                }
            }

            /// <summary>
            /// The Pie item.
            /// </summary>
            [RepositoryItem("b7d64c0f-a02b-40e1-90b4-c3022f693064")]
            public virtual Ranorex.ListItem Pie
            {
                get
                {
                    return _pieInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Pie item info.
            /// </summary>
            [RepositoryItemInfo("b7d64c0f-a02b-40e1-90b4-c3022f693064")]
            public virtual RepoItemInfo PieInfo
            {
                get
                {
                    return _pieInfo;
                }
            }

            /// <summary>
            /// The Remove item.
            /// </summary>
            [RepositoryItem("0f45ee56-4ec4-4009-a610-615a5f57b460")]
            public virtual Ranorex.MenuItem Remove
            {
                get
                {
                    return _removeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Remove item info.
            /// </summary>
            [RepositoryItemInfo("0f45ee56-4ec4-4009-a610-615a5f57b460")]
            public virtual RepoItemInfo RemoveInfo
            {
                get
                {
                    return _removeInfo;
                }
            }

            /// <summary>
            /// The EntireWindow item.
            /// </summary>
            [RepositoryItem("01c44355-2853-40fd-b196-fa0c15e2f64f")]
            public virtual Ranorex.ListItem EntireWindow
            {
                get
                {
                    return _entirewindowInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The EntireWindow item info.
            /// </summary>
            [RepositoryItemInfo("01c44355-2853-40fd-b196-fa0c15e2f64f")]
            public virtual RepoItemInfo EntireWindowInfo
            {
                get
                {
                    return _entirewindowInfo;
                }
            }
        }

        /// <summary>
        /// The SaveChangesAppFolder folder.
        /// </summary>
        [RepositoryFolder("e023f516-9d72-4d93-987f-b52734da129a")]
        public partial class SaveChangesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _discardbuttonInfo;

            /// <summary>
            /// Creates a new SaveChanges  folder.
            /// </summary>
            public SaveChangesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveChanges", "/form[@title='Save Changes']", parentFolder, 30000, null, true, "e023f516-9d72-4d93-987f-b52734da129a", "")
            {
                _discardbuttonInfo = new RepoItemInfo(this, "DiscardButton", ".//container[@name='OptionPane.buttonArea']/button[@text='Discard']", 30000, null, "2f6a6708-f14b-4f61-b831-60b96d7c607d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e023f516-9d72-4d93-987f-b52734da129a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DiscardButton item.
            /// </summary>
            [RepositoryItem("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual Ranorex.Button DiscardButton
            {
                get
                {
                    return _discardbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DiscardButton item info.
            /// </summary>
            [RepositoryItemInfo("2f6a6708-f14b-4f61-b831-60b96d7c607d")]
            public virtual RepoItemInfo DiscardButtonInfo
            {
                get
                {
                    return _discardbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The LabelWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("86c48c36-7d84-41a5-9bfd-48688233bff3")]
        public partial class LabelWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _showdataInfo;
            RepoItemInfo _measuredvaluesInfo;

            /// <summary>
            /// Creates a new LabelWindow  folder.
            /// </summary>
            public LabelWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LabelWindow", "/form", parentFolder, 30000, null, true, "86c48c36-7d84-41a5-9bfd-48688233bff3", "")
            {
                _showdataInfo = new RepoItemInfo(this, "ShowData", ".//container[@accessiblename='Data Labels']/?/?/checkbox[@text='Show Data Labels']", 30000, null, "dfa9df49-e585-431d-8d78-85532a0b7e78");
                _measuredvaluesInfo = new RepoItemInfo(this, "MeasuredValues", ".//container[@accessiblename='Data Labels']/?/?/checkbox[@text='Show Measure Values']", 30000, null, "41761b76-f253-4f5f-b0be-9ec4af2192c4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("86c48c36-7d84-41a5-9bfd-48688233bff3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("86c48c36-7d84-41a5-9bfd-48688233bff3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ShowData item.
            /// </summary>
            [RepositoryItem("dfa9df49-e585-431d-8d78-85532a0b7e78")]
            public virtual Ranorex.CheckBox ShowData
            {
                get
                {
                    return _showdataInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ShowData item info.
            /// </summary>
            [RepositoryItemInfo("dfa9df49-e585-431d-8d78-85532a0b7e78")]
            public virtual RepoItemInfo ShowDataInfo
            {
                get
                {
                    return _showdataInfo;
                }
            }

            /// <summary>
            /// The MeasuredValues item.
            /// </summary>
            [RepositoryItem("41761b76-f253-4f5f-b0be-9ec4af2192c4")]
            public virtual Ranorex.CheckBox MeasuredValues
            {
                get
                {
                    return _measuredvaluesInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The MeasuredValues item info.
            /// </summary>
            [RepositoryItemInfo("41761b76-f253-4f5f-b0be-9ec4af2192c4")]
            public virtual RepoItemInfo MeasuredValuesInfo
            {
                get
                {
                    return _measuredvaluesInfo;
                }
            }
        }

        /// <summary>
        /// The Datastudio1AppFolder folder.
        /// </summary>
        [RepositoryFolder("5f32d409-b531-4fb5-8144-70eecbd1e487")]
        public partial class Datastudio1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jsliderInfo;
            RepoItemInfo _onbuttonInfo;

            /// <summary>
            /// Creates a new Datastudio1  folder.
            /// </summary>
            public Datastudio1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Datastudio1", "/form[@title='' and @processname='datastudio']", parentFolder, 30000, null, false, "5f32d409-b531-4fb5-8144-70eecbd1e487", "")
            {
                _jsliderInfo = new RepoItemInfo(this, "JSlider", "?/?/container[@accessiblename='Center Hole Size']/?/?/slider[@type='JSlider']", 30000, null, "1202d0c7-d258-4bad-9e79-b906db56444f");
                _onbuttonInfo = new RepoItemInfo(this, "ONButton", ".//container[@accessiblename='Show Empty Categories']/?/?/radiobutton[@text='On']", 30000, null, "fe071302-85cf-4a69-b4ab-ca19305f8425");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f32d409-b531-4fb5-8144-70eecbd1e487")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f32d409-b531-4fb5-8144-70eecbd1e487")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JSlider item.
            /// </summary>
            [RepositoryItem("1202d0c7-d258-4bad-9e79-b906db56444f")]
            public virtual Ranorex.Slider JSlider
            {
                get
                {
                    return _jsliderInfo.CreateAdapter<Ranorex.Slider>(true);
                }
            }

            /// <summary>
            /// The JSlider item info.
            /// </summary>
            [RepositoryItemInfo("1202d0c7-d258-4bad-9e79-b906db56444f")]
            public virtual RepoItemInfo JSliderInfo
            {
                get
                {
                    return _jsliderInfo;
                }
            }

            /// <summary>
            /// The ONButton item.
            /// </summary>
            [RepositoryItem("fe071302-85cf-4a69-b4ab-ca19305f8425")]
            public virtual Ranorex.RadioButton ONButton
            {
                get
                {
                    return _onbuttonInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The ONButton item info.
            /// </summary>
            [RepositoryItemInfo("fe071302-85cf-4a69-b4ab-ca19305f8425")]
            public virtual RepoItemInfo ONButtonInfo
            {
                get
                {
                    return _onbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The VAWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
        public partial class VAWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closewindowInfo;

            /// <summary>
            /// Creates a new VAWindow  folder.
            /// </summary>
            public VAWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VAWindow", "/form[@title~'^Visual\\ Analytics']", parentFolder, 30000, null, true, "28ef3ff7-5142-4c80-9fe2-5119aa3572c6", "")
            {
                _closewindowInfo = new RepoItemInfo(this, "CloseWindow", ".//button[@accessiblename='Close']", 30000, null, "eb7f4e53-1ab2-4471-9058-e4ab8e63fccd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28ef3ff7-5142-4c80-9fe2-5119aa3572c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseWindow item.
            /// </summary>
            [RepositoryItem("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual Ranorex.Button CloseWindow
            {
                get
                {
                    return _closewindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseWindow item info.
            /// </summary>
            [RepositoryItemInfo("eb7f4e53-1ab2-4471-9058-e4ab8e63fccd")]
            public virtual RepoItemInfo CloseWindowInfo
            {
                get
                {
                    return _closewindowInfo;
                }
            }
        }

        /// <summary>
        /// The VATestAppFolder folder.
        /// </summary>
        [RepositoryFolder("81ca719e-496c-47ca-9b1b-ad15c41ce9e7")]
        public partial class VATestAppFolder : RepoGenBaseFolder
        {
            TC10563RepoFolders.ContainerContentPanelFolder _containercontentpanel;
            RepoItemInfo _optionsInfo;
            PivotTableOverlayPanelInfoClass _pivottableoverlaypanelInfo;
            BIChartOverlayPanelInfoClass _bichartoverlaypanelInfo;
            ContainerCanvasInfoClass _containercanvasInfo;
            StartWindowInfoClass _startwindowInfo;

            /// <summary>
            /// Creates a new VATest  folder.
            /// </summary>
            public VATestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("VATest", "/form[@title~'^Visual\\ Analytics\\ -\\ \\[VA-te']", parentFolder, 30000, null, true, "81ca719e-496c-47ca-9b1b-ad15c41ce9e7", "")
            {
                _containercontentpanel = new TC10563RepoFolders.ContainerContentPanelFolder(this);
                _optionsInfo = new RepoItemInfo(this, "Options", "container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Options']", 30000, null, "e4359f12-ceae-4aa4-9069-bb87fc076aed");
                _pivottableoverlaypanelInfo = new PivotTableOverlayPanelInfoClass(this);
                _bichartoverlaypanelInfo = new BIChartOverlayPanelInfoClass(this);
                _containercanvasInfo = new ContainerCanvasInfoClass(this);
                _startwindowInfo = new StartWindowInfoClass(this);
            }

            /// <summary>
            /// The PivotTableOverlayPanelInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("28464fc5-c9c8-4068-9498-05aad270d2d5")]
            public class PivotTableOverlayPanelInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PivotTableOverlayPanelInfoClass class constructor.
                /// </summary>
                public PivotTableOverlayPanelInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "PivotTableOverlayPanel", "container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_gridPanel']/?/?/container[@type='PivotTableOverlayPanel']", 30000, null, "28464fc5-c9c8-4068-9498-05aad270d2d5")
                { }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <returns>The VizxDataWindow image.</returns>
                [RepositoryImage("26b1a6fa-5dfd-4ab5-9199-a95c8fd4a139")]
                public CompressedImage GetVizxDataWindow()
                {
                    return GetImage("26b1a6fa-5dfd-4ab5-9199-a95c8fd4a139");
                }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("26b1a6fa-5dfd-4ab5-9199-a95c8fd4a139")]
                public CompressedImage GetVizxDataWindow(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("26b1a6fa-5dfd-4ab5-9199-a95c8fd4a139", cropRect);
                }
            }

            /// <summary>
            /// The BIChartOverlayPanelInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("014debe6-d10d-4da2-8122-e815772f2ac3")]
            public class BIChartOverlayPanelInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BIChartOverlayPanelInfoClass class constructor.
                /// </summary>
                public BIChartOverlayPanelInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "BIChartOverlayPanel", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container", 30000, null, "014debe6-d10d-4da2-8122-e815772f2ac3")
                { }

                /// <summary>
                /// Gets the AfterRemoveCardtype item image.
                /// </summary>
                /// <returns>The AfterRemoveCardtype image.</returns>
                [RepositoryImage("7f028397-2c5c-4c18-aa0b-963048a9ae69")]
                public CompressedImage GetAfterRemoveCardtype()
                {
                    return GetImage("7f028397-2c5c-4c18-aa0b-963048a9ae69");
                }

                /// <summary>
                /// Gets the AfterRemoveCardtype item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7f028397-2c5c-4c18-aa0b-963048a9ae69")]
                public CompressedImage GetAfterRemoveCardtype(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7f028397-2c5c-4c18-aa0b-963048a9ae69", cropRect);
                }

                /// <summary>
                /// Gets the AfterRemoveShipdate item image.
                /// </summary>
                /// <returns>The AfterRemoveShipdate image.</returns>
                [RepositoryImage("c2e15e08-30aa-4dd2-8773-ecc71b1b9fc8")]
                public CompressedImage GetAfterRemoveShipdate()
                {
                    return GetImage("c2e15e08-30aa-4dd2-8773-ecc71b1b9fc8");
                }

                /// <summary>
                /// Gets the AfterRemoveShipdate item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c2e15e08-30aa-4dd2-8773-ecc71b1b9fc8")]
                public CompressedImage GetAfterRemoveShipdate(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c2e15e08-30aa-4dd2-8773-ecc71b1b9fc8", cropRect);
                }

                /// <summary>
                /// Gets the CurrencyCodetoLabel item image.
                /// </summary>
                /// <returns>The CurrencyCodetoLabel image.</returns>
                [RepositoryImage("974b705f-4767-4df1-97dc-dfedee3eebbd")]
                public CompressedImage GetCurrencyCodetoLabel()
                {
                    return GetImage("974b705f-4767-4df1-97dc-dfedee3eebbd");
                }

                /// <summary>
                /// Gets the CurrencyCodetoLabel item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("974b705f-4767-4df1-97dc-dfedee3eebbd")]
                public CompressedImage GetCurrencyCodetoLabel(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("974b705f-4767-4df1-97dc-dfedee3eebbd", cropRect);
                }

                /// <summary>
                /// Gets the DragCardtypetoColor item image.
                /// </summary>
                /// <returns>The DragCardtypetoColor image.</returns>
                [RepositoryImage("a1c0c5ad-979f-474d-b167-90e5d145d858")]
                public CompressedImage GetDragCardtypetoColor()
                {
                    return GetImage("a1c0c5ad-979f-474d-b167-90e5d145d858");
                }

                /// <summary>
                /// Gets the DragCardtypetoColor item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a1c0c5ad-979f-474d-b167-90e5d145d858")]
                public CompressedImage GetDragCardtypetoColor(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a1c0c5ad-979f-474d-b167-90e5d145d858", cropRect);
                }

                /// <summary>
                /// Gets the DragCardtypetoLabel item image.
                /// </summary>
                /// <returns>The DragCardtypetoLabel image.</returns>
                [RepositoryImage("4c31fd13-563a-416d-afc5-d29f26f11cc5")]
                public CompressedImage GetDragCardtypetoLabel()
                {
                    return GetImage("4c31fd13-563a-416d-afc5-d29f26f11cc5");
                }

                /// <summary>
                /// Gets the DragCardtypetoLabel item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("4c31fd13-563a-416d-afc5-d29f26f11cc5")]
                public CompressedImage GetDragCardtypetoLabel(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("4c31fd13-563a-416d-afc5-d29f26f11cc5", cropRect);
                }

                /// <summary>
                /// Gets the DragProfittoColorDeck item image.
                /// </summary>
                /// <returns>The DragProfittoColorDeck image.</returns>
                [RepositoryImage("22ee15bf-3f80-4051-8bc8-4b9ea2bb2085")]
                public CompressedImage GetDragProfittoColorDeck()
                {
                    return GetImage("22ee15bf-3f80-4051-8bc8-4b9ea2bb2085");
                }

                /// <summary>
                /// Gets the DragProfittoColorDeck item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("22ee15bf-3f80-4051-8bc8-4b9ea2bb2085")]
                public CompressedImage GetDragProfittoColorDeck(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("22ee15bf-3f80-4051-8bc8-4b9ea2bb2085", cropRect);
                }

                /// <summary>
                /// Gets the HoleMaxChart item image.
                /// </summary>
                /// <returns>The HoleMaxChart image.</returns>
                [RepositoryImage("10176682-b690-4e0f-b0a7-61586bfb5c8c")]
                public CompressedImage GetHoleMaxChart()
                {
                    return GetImage("10176682-b690-4e0f-b0a7-61586bfb5c8c");
                }

                /// <summary>
                /// Gets the HoleMaxChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("10176682-b690-4e0f-b0a7-61586bfb5c8c")]
                public CompressedImage GetHoleMaxChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("10176682-b690-4e0f-b0a7-61586bfb5c8c", cropRect);
                }

                /// <summary>
                /// Gets the ONButtonChart item image.
                /// </summary>
                /// <returns>The ONButtonChart image.</returns>
                [RepositoryImage("2d17a18e-d627-4cc6-8b76-29aa44e7f39d")]
                public CompressedImage GetONButtonChart()
                {
                    return GetImage("2d17a18e-d627-4cc6-8b76-29aa44e7f39d");
                }

                /// <summary>
                /// Gets the ONButtonChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("2d17a18e-d627-4cc6-8b76-29aa44e7f39d")]
                public CompressedImage GetONButtonChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("2d17a18e-d627-4cc6-8b76-29aa44e7f39d", cropRect);
                }

                /// <summary>
                /// Gets the PieChart item image.
                /// </summary>
                /// <returns>The PieChart image.</returns>
                [RepositoryImage("a43a447b-6dfa-4bbd-984b-3aa47462ba7b")]
                public CompressedImage GetPieChart()
                {
                    return GetImage("a43a447b-6dfa-4bbd-984b-3aa47462ba7b");
                }

                /// <summary>
                /// Gets the PieChart item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a43a447b-6dfa-4bbd-984b-3aa47462ba7b")]
                public CompressedImage GetPieChart(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a43a447b-6dfa-4bbd-984b-3aa47462ba7b", cropRect);
                }

                /// <summary>
                /// Gets the ShowData item image.
                /// </summary>
                /// <returns>The ShowData image.</returns>
                [RepositoryImage("a35fc165-5c9d-41a9-8851-b4098004d58d")]
                public CompressedImage GetShowData()
                {
                    return GetImage("a35fc165-5c9d-41a9-8851-b4098004d58d");
                }

                /// <summary>
                /// Gets the ShowData item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a35fc165-5c9d-41a9-8851-b4098004d58d")]
                public CompressedImage GetShowData(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a35fc165-5c9d-41a9-8851-b4098004d58d", cropRect);
                }

                /// <summary>
                /// Gets the ShowMeasuredValues item image.
                /// </summary>
                /// <returns>The ShowMeasuredValues image.</returns>
                [RepositoryImage("84e0f544-dc91-43a7-ac97-ea4b5403d31c")]
                public CompressedImage GetShowMeasuredValues()
                {
                    return GetImage("84e0f544-dc91-43a7-ac97-ea4b5403d31c");
                }

                /// <summary>
                /// Gets the ShowMeasuredValues item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("84e0f544-dc91-43a7-ac97-ea4b5403d31c")]
                public CompressedImage GetShowMeasuredValues(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("84e0f544-dc91-43a7-ac97-ea4b5403d31c", cropRect);
                }
            }

            /// <summary>
            /// The ContainerCanvasInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("879da9cd-1c6e-49ab-861f-8db19366e2c0")]
            public class ContainerCanvasInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ContainerCanvasInfoClass class constructor.
                /// </summary>
                public ContainerCanvasInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ContainerCanvas", "container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container[@name='_canvas']", 30000, null, "879da9cd-1c6e-49ab-861f-8db19366e2c0")
                { }

                /// <summary>
                /// Gets the HoleSizeMax item image.
                /// </summary>
                /// <returns>The HoleSizeMax image.</returns>
                [RepositoryImage("101085a5-dbb5-495e-b771-dbc29e97014f")]
                public CompressedImage GetHoleSizeMax()
                {
                    return GetImage("101085a5-dbb5-495e-b771-dbc29e97014f");
                }

                /// <summary>
                /// Gets the HoleSizeMax item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("101085a5-dbb5-495e-b771-dbc29e97014f")]
                public CompressedImage GetHoleSizeMax(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("101085a5-dbb5-495e-b771-dbc29e97014f", cropRect);
                }
            }

            /// <summary>
            /// The StartWindowInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9f200710-0a18-4c35-806d-41bf4c188604")]
            public class StartWindowInfoClass : RepoItemInfo
            {
                /// <summary>
                /// StartWindowInfoClass class constructor.
                /// </summary>
                public StartWindowInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "StartWindow", ".//container[@name='_mainPanel']//container[@name='_sheetsPane']/container[@name='Worksheet 1']//container[@name='main']/container[@name='_cardPanel']/container[@name='_chartPanel']/container", 30000, null, "9f200710-0a18-4c35-806d-41bf4c188604")
                { }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <returns>The VizxDataWindow image.</returns>
                [RepositoryImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e")]
                public CompressedImage GetVizxDataWindow()
                {
                    return GetImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e");
                }

                /// <summary>
                /// Gets the VizxDataWindow item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e")]
                public CompressedImage GetVizxDataWindow(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("38be7d7a-d02d-4e8c-9604-439d86bfbd4e", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("81ca719e-496c-47ca-9b1b-ad15c41ce9e7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("81ca719e-496c-47ca-9b1b-ad15c41ce9e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Options item.
            /// </summary>
            [RepositoryItem("e4359f12-ceae-4aa4-9069-bb87fc076aed")]
            public virtual Ranorex.Text Options
            {
                get
                {
                    return _optionsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Options item info.
            /// </summary>
            [RepositoryItemInfo("e4359f12-ceae-4aa4-9069-bb87fc076aed")]
            public virtual RepoItemInfo OptionsInfo
            {
                get
                {
                    return _optionsInfo;
                }
            }

            /// <summary>
            /// The PivotTableOverlayPanel item.
            /// </summary>
            [RepositoryItem("28464fc5-c9c8-4068-9498-05aad270d2d5")]
            public virtual Ranorex.Container PivotTableOverlayPanel
            {
                get
                {
                    return _pivottableoverlaypanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PivotTableOverlayPanel item info.
            /// </summary>
            [RepositoryItemInfo("28464fc5-c9c8-4068-9498-05aad270d2d5")]
            public virtual PivotTableOverlayPanelInfoClass PivotTableOverlayPanelInfo
            {
                get
                {
                    return _pivottableoverlaypanelInfo;
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel item.
            /// </summary>
            [RepositoryItem("014debe6-d10d-4da2-8122-e815772f2ac3")]
            public virtual Ranorex.Container BIChartOverlayPanel
            {
                get
                {
                    return _bichartoverlaypanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The BIChartOverlayPanel item info.
            /// </summary>
            [RepositoryItemInfo("014debe6-d10d-4da2-8122-e815772f2ac3")]
            public virtual BIChartOverlayPanelInfoClass BIChartOverlayPanelInfo
            {
                get
                {
                    return _bichartoverlaypanelInfo;
                }
            }

            /// <summary>
            /// The ContainerCanvas item.
            /// </summary>
            [RepositoryItem("879da9cd-1c6e-49ab-861f-8db19366e2c0")]
            public virtual Ranorex.Container ContainerCanvas
            {
                get
                {
                    return _containercanvasInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerCanvas item info.
            /// </summary>
            [RepositoryItemInfo("879da9cd-1c6e-49ab-861f-8db19366e2c0")]
            public virtual ContainerCanvasInfoClass ContainerCanvasInfo
            {
                get
                {
                    return _containercanvasInfo;
                }
            }

            /// <summary>
            /// The StartWindow item.
            /// </summary>
            [RepositoryItem("9f200710-0a18-4c35-806d-41bf4c188604")]
            public virtual Ranorex.Container StartWindow
            {
                get
                {
                    return _startwindowInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The StartWindow item info.
            /// </summary>
            [RepositoryItemInfo("9f200710-0a18-4c35-806d-41bf4c188604")]
            public virtual StartWindowInfoClass StartWindowInfo
            {
                get
                {
                    return _startwindowInfo;
                }
            }

            /// <summary>
            /// The ContainerContentPanel folder.
            /// </summary>
            [RepositoryFolder("2a59490c-e583-4146-9cac-ae6fdbaeae78")]
            public virtual TC10563RepoFolders.ContainerContentPanelFolder ContainerContentPanel
            {
                get { return _containercontentpanel; }
            }
        }

        /// <summary>
        /// The ContainerContentPanelFolder folder.
        /// </summary>
        [RepositoryFolder("2a59490c-e583-4146-9cac-ae6fdbaeae78")]
        public partial class ContainerContentPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cardtypeInfo;
            RepoItemInfo _currencycodeInfo;
            RepoItemInfo _colorInfo;
            RepoItemInfo _labelInfo;
            RepoItemInfo _sumprofitInfo;
            RepoItemInfo _optionsInfo;

            /// <summary>
            /// Creates a new ContainerContentPanel  folder.
            /// </summary>
            public ContainerContentPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("ContainerContentPanel", "container[@name='_mainPanel']/container[@name='_contentPanel']", parentFolder, 30000, null, false, "2a59490c-e583-4146-9cac-ae6fdbaeae78", "")
            {
                _cardtypeInfo = new RepoItemInfo(this, "CardType", "?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Card Type']", 30000, null, "f516dc9b-48e2-4e45-83f4-06fba73b9079");
                _currencycodeInfo = new RepoItemInfo(this, "CurrencyCode", "?/?/container[@name='_leftPanel']//container[@type='BIDimensionDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='Currency Code']", 30000, null, "528a908c-353d-4c6d-a6c9-014f9acaf4c6");
                _colorInfo = new RepoItemInfo(this, "Color", "container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Color']", 30000, null, "3bdf888b-bae3-4caf-9680-30acf2792189");
                _labelInfo = new RepoItemInfo(this, "Label", "container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Label']", 30000, null, "21e40361-ad55-481a-957a-5e28cffe7f29");
                _sumprofitInfo = new RepoItemInfo(this, "SUMProfit", "?/?/container[@name='_leftPanel']//container[@type='BIMeasureDataPane']//container[@name='viewport']/list[@type='BIDraggableList']/listitem[@text='SUM(Profit)']", 30000, null, "e6c97fa7-d58b-4fdc-b0e3-546c8664b1b8");
                _optionsInfo = new RepoItemInfo(this, "Options", "container[@name='_mainPanel']/container[@name='_contentPanel']/container[@name='_splitPane']/container[@name='_sheetsPane']/container[@name='Worksheet 1']/container[@name='_worksheetPanel']/container[@name='_contentPanel']//container[@name='marks']//text[@caption='Options']", 30000, null, "9eb7f618-7e19-4c24-a7ef-568487200f15");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a59490c-e583-4146-9cac-ae6fdbaeae78")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a59490c-e583-4146-9cac-ae6fdbaeae78")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CardType item.
            /// </summary>
            [RepositoryItem("f516dc9b-48e2-4e45-83f4-06fba73b9079")]
            public virtual Ranorex.ListItem CardType
            {
                get
                {
                    return _cardtypeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CardType item info.
            /// </summary>
            [RepositoryItemInfo("f516dc9b-48e2-4e45-83f4-06fba73b9079")]
            public virtual RepoItemInfo CardTypeInfo
            {
                get
                {
                    return _cardtypeInfo;
                }
            }

            /// <summary>
            /// The CurrencyCode item.
            /// </summary>
            [RepositoryItem("528a908c-353d-4c6d-a6c9-014f9acaf4c6")]
            public virtual Ranorex.ListItem CurrencyCode
            {
                get
                {
                    return _currencycodeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CurrencyCode item info.
            /// </summary>
            [RepositoryItemInfo("528a908c-353d-4c6d-a6c9-014f9acaf4c6")]
            public virtual RepoItemInfo CurrencyCodeInfo
            {
                get
                {
                    return _currencycodeInfo;
                }
            }

            /// <summary>
            /// The Color item.
            /// </summary>
            [RepositoryItem("3bdf888b-bae3-4caf-9680-30acf2792189")]
            public virtual Ranorex.Text Color
            {
                get
                {
                    return _colorInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Color item info.
            /// </summary>
            [RepositoryItemInfo("3bdf888b-bae3-4caf-9680-30acf2792189")]
            public virtual RepoItemInfo ColorInfo
            {
                get
                {
                    return _colorInfo;
                }
            }

            /// <summary>
            /// The Label item.
            /// </summary>
            [RepositoryItem("21e40361-ad55-481a-957a-5e28cffe7f29")]
            public virtual Ranorex.Text Label
            {
                get
                {
                    return _labelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label item info.
            /// </summary>
            [RepositoryItemInfo("21e40361-ad55-481a-957a-5e28cffe7f29")]
            public virtual RepoItemInfo LabelInfo
            {
                get
                {
                    return _labelInfo;
                }
            }

            /// <summary>
            /// The SUMProfit item.
            /// </summary>
            [RepositoryItem("e6c97fa7-d58b-4fdc-b0e3-546c8664b1b8")]
            public virtual Ranorex.ListItem SUMProfit
            {
                get
                {
                    return _sumprofitInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SUMProfit item info.
            /// </summary>
            [RepositoryItemInfo("e6c97fa7-d58b-4fdc-b0e3-546c8664b1b8")]
            public virtual RepoItemInfo SUMProfitInfo
            {
                get
                {
                    return _sumprofitInfo;
                }
            }

            /// <summary>
            /// The Options item.
            /// </summary>
            [RepositoryItem("9eb7f618-7e19-4c24-a7ef-568487200f15")]
            public virtual Ranorex.Text Options
            {
                get
                {
                    return _optionsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Options item info.
            /// </summary>
            [RepositoryItemInfo("9eb7f618-7e19-4c24-a7ef-568487200f15")]
            public virtual RepoItemInfo OptionsInfo
            {
                get
                {
                    return _optionsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}